### ISSUE TITLE
V2: Payments

### ISSUE THREAD

**Issue by tucnak** [tucnak/telebot#101]
https://core.telegram.org/bots/api#payments

**Comment by demget** [comment]
Done! https://github.com/tucnak/telebot/commit/76c2cedf6f513e73436fb23638e6f4b80942b2db, https://github.com/tucnak/telebot/commit/16e74b8025acf4bdc643ddeca16fbd8ea05796f4, https://github.com/tucnak/telebot/commit/7a1d59c7d95330f38c63bfc0416e8470cd265f6e
