### ISSUE TITLE
Is this graceful shutdown works?

### ISSUE THREAD

**Issue by borovskyav** [tucnak/telebot#106]
Hi, i watch on your stop method (https://github.com/tucnak/telebot/commit/31f0da895eefbe5edbd214995b51d10ab4ca8791) and don't understand, is this really works? After you calls stop() updates cycle https://github.com/tucnak/telebot/blob/3329d982493e1ec98db22c7bc50c733e3e1fd981/bot.go#L130 will never end. The presented test confirms this: 

https://play.golang.org/p/jA-iV-_nKo

**Comment by tucnak** [comment]
Cheers mate!
