### ISSUE TITLE
Example with webhook?

### ISSUE THREAD

**Issue by angelabad** [tucnak/telebot#107]
I'm writing a telegram bot in AWS Lambda, so, its possible you provide a webhook poll example?

Cheers, and thanks for your work!

**Comment by tucnak** [comment]
Telebot doesn't support webhooks yet and you would have known that if only you cared to at least Ctrl+F "webhook" the readme.

Feel free to implement it.

**Comment by cybervagabond** [comment]
г@нд0н, создал либу, ни примеров ни чего, документы нормально не отправляются. Работа с  вебхуком сделана через пизду. На ишьюсы не отвечает месяцами, нет даже не одного примера.

**Comment by liyishuai** [comment]
For webhook, don't use telebot; use telegram-bot-api: https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/README.md#example
