### ISSUE TITLE
I want to send a message to ID 123456

### ISSUE THREAD

**Issue by Mohammad-Reza-Rahimi-Zade** [tucnak/telebot#109]
Hello
I want to send a message to ID "123456"  or  "@xman"
How should I do this?

**Comment by irgendwr** [comment]
```golang
    chat := tb.Chat{ID: 123456}
    _, err := bot.Send(&chat, "foobar")

**Comment by tucnak** [comment]
@irgendwr Cheers on that! Oi, @irgendwr, the fastest hand in the wild west!
