### ISSUE TITLE
ReplyKeyboardRemove

### ISSUE THREAD

**Issue by mmcdole** [tucnak/telebot#114]
Any chance we can get `remove_keyboard` added as one of the ReplyMarkup options?

Official API:
https://core.telegram.org/bots/api#replykeyboardremove

Example from similar library:
https://github.com/irazasyed/telegram-bot-sdk/issues/300

Apologies if this was something I missed.  Besides the OneTimeKeyboard options, in my bot, I wanted to have a generic "SendError" which would remove any active custom keyboards, but didn't see this option exposed.

Thank you for all your hard work on this API! It is truly well done.

**Comment by equt** [comment]
@mmcdole I've added this in my fork #116.
