### ISSUE TITLE
Send and Receive to and from channels 

### ISSUE THREAD

**Issue by ngopher** [tucnak/telebot#122]
Can the bor read a channel's messages or send messages to a channel?
If it can, please help and some explain how to do that?

**Comment by tucnak** [comment]
Yeah sure. In order to receive messages from a channel, use endpoint `tb.OnChannelPost` https://godoc.org/gopkg.in/tucnak/telebot.v2#pkg-constants

**Comment by ngopher** [comment]
@tucnak 
My main issue is adding a bot to a channel, how we can add it to a channel?

**Comment by irgendwr** [comment]
see #123 

nice, that rhymes 😉
