### ISSUE TITLE
How to join a bot to the Channel?

### ISSUE THREAD

**Issue by ngopher** [tucnak/telebot#123]
Hi @tucnak 
Please guide me to join a bot to a channel.
It is clear that a bot just is able to process a channel that has joined.

**Comment by tucnak** [comment]
Just kidding.

**Comment by tucnak** [comment]
No I'm really not.

**Comment by tucnak** [comment]
Jokes aside, Bots API doesn't let you do that.

**Comment by irgendwr** [comment]
This is neither an issue with the library nor the documentation.

Just add the bot as channel-administrator via it's username.

![channel settings](https://i.imgur.com/Tc5BxjV.png)
![channel settings](https://i.imgur.com/NJCCySt.png)
![channel settings](https://i.imgur.com/AipPhSs.png)
![channel settings](https://i.imgur.com/yIyz8PD.png)
