### ISSUE TITLE
m.MigrateFrom not getting a correct value

### ISSUE THREAD

**Issue by clm2609** [tucnak/telebot#129]
I'm trying to support chat migration in my bot but m.MigrateFrom wont show the chat i was in but 0:
`
	b.Handle(tb.OnAddedToGroup, func(m *tb.Message) {
		fmt.Println("Added to chat " + strconv.Itoa(int(m.Chat.ID)))
	})
`

`
	b.Handle(tb.OnMigration, func(from, to int64) {
		fmt.Println("This was chat " + strconv.Itoa(int(from)) + " and now its the chat " + strconv.Itoa(int(to)))
	})
`

This is what i get:
Added to chat -250070354
This was chat 0 and now its the chat -1001176978932

**Comment by demget** [comment]
I don't know how relevant this problem is now. If it is, please re-open and I will check it.
