### ISSUE TITLE
Telegram issued new APIs to download file from server

### ISSUE THREAD

**Issue by Ronmi** [tucnak/telebot#13]
Do you have any plan about implementing these APIs? I'm willing to help but need your suggestion :)

I read the docs of new APIs, found that new `File` structure is identical to `File struct` in telebot. But that structure is only used for download file from server, so I think something like `func (b Bot) SaveFile(f File, localFile string) error` should be enough. Do you think this implementation is fine?

**Comment by tucnak** [comment]
I am unfortunately too busy with studies recently, so deffo not planning to implement any of new things from API. I just took a look at `getFile()` from the original API and found out it might be a little bit more complex. Gimme a while, I'll text you back once I come up with any reasonable solution.

**Comment by Ronmi** [comment]
Ok. I can do some experiments these days, too :)

**Comment by Ronmi** [comment]
After implementing few features at work, I think one single `DownloadFile` would be enough.

Whenever a file is downloaded by bot, we might want to save it for later use, or parse it to get some useful information. Neither of them should download the file again. Instead, we might choose to cache the parsing result more likely.

But this implementation might introduce performance issue. In `telebot`, we upload a file by providing only file name, `telebot` do the file opening job. So we might better use `DownloadFile(f File, localName string) error` to ensure this newly created API keep the same logic with file uploading, which means we need to open the file twice for parsing task: one when `telebot` do the download job, and parser open it again to read data.

[I have rewritten `telebot` for my work](https://github.com/Patrolavia/botgoram/blob/master/telegram/api_methods.go#L221), which implements file upload/download using stream. Maybe you can take a look, hopefully we can have some inspirations.

**Comment by ejamesc** [comment]
Is help still wanted for this, @tucnak? No promises yet, but I can take a look at this in the near future.

**Comment by tucnak** [comment]
@ejamesc I just feel flown with.. stuff (studying kills). I still don't feel that `DownloadFile` is the right thing to implement. That said, I'd love you to help me out here.

**Comment by tucnak** [comment]
Is it in master already? Seems like it is.
