### ISSUE TITLE
Timeout when post

### ISSUE THREAD

**Issue by ihciah** [tucnak/telebot#130]
```
http.Post failed: Post https://api.telegram.org/botXXXXX/sendMediaGroup: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
This error happens randomly expecially when sending big medium such as albums. Maybe it can be solved by adding a timeout init parameter?

**Comment by irgendwr** [comment]
You can now provide a custom http client with a custom timeout, see #132 

/cc @tucnak This can be closed

**Comment by ihciah** [comment]
Thanks, I already solved it though a similar approach.
