### ISSUE TITLE
Voice handler doesn't fire

### ISSUE THREAD

**Issue by kifirkin** [tucnak/telebot#131]
Can't get OnVoice handler to work :cry: 
also can't handle messages with games posted via `@gamee`

**Comment by irgendwr** [comment]
> Can't get OnVoice handler to work 😢

Can you share your code with us?

> also can't handle messages with games posted via `@gamee`

Bots are unable to receive messages from other bots.
This is a deliberate limitation by telegram to prevent feedback loops.

**Comment by kifirkin** [comment]
It's simple one
```
	b, err := tb.NewBot(tb.Settings{
		Token:  cfg.Token,
		Poller: &tb.LongPoller{Timeout: 1 * time.Second},
	})

	b.Handle(tb.OnVoice, func(m *tb.Message) {
		b.Delete(m)
	})
```

also I've set up almost all available handlers to see wich one fires up and got only silence on voice messages

```
b.Handle("/start", func(m *tb.Message) {
    log.Println(m)
b.Handle("/activate", func(m *tb.Message) {
    ...
b.Handle(tb.OnText, func(m *tb.Message) {
b.Handle(tb.OnPhoto, func(m *tb.Message) {
b.Handle(tb.OnAudio, func(m *tb.Message) {
b.Handle(tb.OnDocument, func(m *tb.Message) {
b.Handle(tb.OnSticker, func(m *tb.Message) {
b.Handle(tb.OnVideo, func(m *tb.Message) {
b.Handle(tb.OnVideoNote, func(m *tb.Message) {
b.Handle(tb.OnContact, func(m *tb.Message) {
b.Handle(tb.OnLocation, func(m *tb.Message) {
b.Handle(tb.OnVenue, func(m *tb.Message) {
```

also sending audio with `@music` fires up `OnAudio`


with `@gamee` I'am expecting that it wil also fire some event, because I'am sending it manually with inline query to group

**Comment by kifirkin** [comment]
Thanks !
