### ISSUE TITLE
Is there any way to upload file from memory?

### ISSUE THREAD

**Issue by DevAlone** [tucnak/telebot#137]
I haven't found. It would be great to not create temporary files for data from memory.

**Comment by stek29** [comment]
No, there's not.

Shouldn't be hard to implement new file type based on io.Reader or bytes slice (I'd go for first one), and maybe refactoring sendFiles a bit so it accepts io.Reader slice for files (or even better -- interface{} slice, and add handling for io.Reader conforming types and for string).

I'm sure PRs are welcome, would you be able to work on this?

**Comment by DevAlone** [comment]
Hi, unfortunately, I don't have much time now

**Comment by ilyaglow** [comment]
@stek29 already has a working branch here https://github.com/stek29/telebot/tree/thumb. By the way, any plans to merge it here soon? :)

**Comment by stek29** [comment]
@ilyaglow I want to debug thumbnails before submitting PR

**Comment by ilyaglow** [comment]
Oh, is it possible to split `io.Reader` type support and thumbnails feature in two separated PRs?

**Comment by ilyaglow** [comment]
If someone wants to play with `io.Reader` as a file attachment - I've cherry-picked the commit https://github.com/stek29/telebot/commit/56519659734f4afe5183eb6a8cb8db0e13677c67 to my fork, so you can use the following import: `gopkg.in/ilyaglow/telebot.v3`.

**Comment by stek29** [comment]
@ilyaglow of course it is, and that's what I am going to do, I just wanted to make sure it works, and I wanted to test that with thumbnails.

I'll submit a PR once I'm sure that it works fine, and doesn't leave unclosed files.
