### ISSUE TITLE
Example at gdoc is out-dated

### ISSUE THREAD

**Issue by suntong** [tucnak/telebot#140]
I first tried the Example at gdoc
https://godoc.org/gopkg.in/tucnak/telebot.v2
but found it is out-dated:

```
./demo0.go:12:29: too few values in struct initializer
./demo0.go:19:11: undefined: telebot.OnMessage
```

Just logging the issue. No rush. I get it working from readme.

**Comment by stek29** [comment]
interestingly, there's no universal handler anymore, like one on message was.
