### ISSUE TITLE
any event type

### ISSUE THREAD

**Issue by wanhoop** [tucnak/telebot#142]
hi
sorry for my English
Is there any way to track that the bot just came in, and divide it into classes already in the function itself?

**Comment by kifirkin** [comment]
@wanhoop Sorry I cant understand what you trying to solve

What does it mean "the bot just came in"?

probably you want to handle "/start" event?

**Comment by wanhoop** [comment]
@alexmironof хех, ну раз Москва то
есть вот OnText, OnLocation и прочее
а если мне надо отслеживать любое сообщение которое пришло боту, и разделять его в обработчике на тип эвента?

**Comment by wanhoop** [comment]
@alexmironof как-то всё я не ясно выражаюсь,
ну вот псевдокода немного, чтоб хотя бы можно было понять что мне надо

here's a pseudo-code a little, so that at least you could understand what I need

b.Handle(tb.**OnAnyUpdate**, func(upd *tb.**AnyUpdate**)(
   switch u:= upd.(type){
      case Message:
      case Location
      ....
   }
))

**Comment by kifirkin** [comment]
@wanhoop  понял, тебе нужно poller расширять по типу SpamProtected вот как тут написано https://github.com/tucnak/telebot#poller

you need to chain default poller with your custom one

**Comment by wanhoop** [comment]
@alexmironof thx!
