### ISSUE TITLE
FileName not work when use Send tb.Document

### ISSUE THREAD

**Issue by mritd** [tucnak/telebot#147]
FileName not work when use Send tb.Document；
Here is the sample code:

``` golang
package main

import (
	"net/http"
	"time"
	"net/url"
	tb "gopkg.in/tucnak/telebot.v2"
)

func main() {

	p := func(_ *http.Request) (*url.URL, error) {
		return url.Parse("http://PROXY_ADDRESS:8123")
	}
	client := &http.Client{
		Timeout: 20 * time.Second,
		Transport: &http.Transport{Proxy: p},
	}

	bot, _ := tb.NewBot(tb.Settings{
		Token:  "BOT_TOKEN",
		Poller: &tb.LongPoller{Timeout: 10 * time.Second},
		Client: client,
	})
	bot.Send(&tb.Chat{ID: int64(305893639)}, &tb.Document{
		File:     tb.FromDisk("/Users/mritd/gopath/src/github.com/mritd/test/main.go"),
		FileName: "test",
	})
}
```

![image](https://user-images.githubusercontent.com/13043245/42120117-5c5e6e78-7c48-11e8-893b-d010e8aa838d.png)

**Comment by olehbozhok** [comment]
you need specify caption
https://core.telegram.org/bots/api#senddocument

FileName is not "" when you got file

**Comment by mritd** [comment]
@Oleg-MBO  I added the caption parameter, but the file name has not changed.

![image](https://user-images.githubusercontent.com/13043245/42131154-c40a7ec8-7d2d-11e8-9a43-2461c417d834.png)

**Comment by ilyaglow** [comment]
Same thing for `tb.FromReader` [call](https://github.com/tucnak/telebot/blob/v2/api.go#L52).

**Comment by ilyaglow** [comment]
Hmm, it seems that 6264ba6 doesn't work for the OP case either. Reproduced the same issue with `tb.FromDisk` too. Ping @tucnak @stek29.  

We should probably add filename parameter to `addFileToWriter` function.

**Comment by stek29** [comment]
hm, I don't think that'd be enough. FileName needs to be passed from `(Object).Send` to `(*Bot) sendObject`, and from there to `(*Bot) sendFiles`, and from there to `addFileToWriter`.

Also, what should we do with files created from file_id/url? There's no way to set filename there, is there?
