### ISSUE TITLE
Can't get OnText handle to work

### ISSUE THREAD

**Issue by simonerom** [tucnak/telebot#152]
Hi,
I'm trying to learn go lang by porting my telegram bot from C# to go, and I'm using Telebot because it seems quite easy to use.

I could manage to get the "/hello" handle to work; after that I added the "OnText" handle because I want to check text messages for spam but, while the "/hello" handle works the OnText handle seems to never get fired. I added the bot to a group and I expect the OnText to get fired each time I write a text message.

Here is my simple code:

```go
package main

import (
	"time"
	"log"

	tb "github.com/tucnak/telebot"
)

func main() {
	log.Println("Starting the bot...")
	b, err := tb.NewBot(tb.Settings{
		Token:  "MY TOKEN",
		Poller: &tb.LongPoller{Timeout: 10 * time.Second},
	})

	if err != nil {
		log.Fatal(err)
		return
	}

	// This doesn't get fired!!
	b.Handle(tb.OnText, func(m *tb.Message) {
		b.Send(m.Chat, "Got a text message")
	})

	// This works
	b.Handle("/hello", func(m *tb.Message) {
		options := new(tb.SendOptions)
		options.ReplyTo = m
		b.Send(m.Chat, "Hi "+m.Sender.FirstName+", I'm the Bot!", options)
	})

	b.Start()
}
```

**Comment by simonerom** [comment]
Ok, I did some more tests and it seems the OnText handle gets actually fired if my message starts with "/" (assuming it's not "/hello"). Any other text message not starting by "/" does not trigger the OnText hendle. I configured my bot privacy setting to off (I get "Has access to messages" under the bot user).

Is this normal behavior? How am I supposed to catch any group text message?

**Comment by stek29** [comment]
@simonerom just to make sure: same bot works as expected with C#? Does it work if bot is mentioned (by username)?

**Comment by GTANAdam** [comment]
Yep, that's true.

**Comment by stek29** [comment]
@GTANAdam what is true?

**Comment by GTANAdam** [comment]
> @GTANAdam what is true?

The bot isn't reading the messages posted in groups, but only commands.

**Comment by stek29** [comment]
@GTANAdam then disable bot privacy in botfather

**Comment by GTANAdam** [comment]
@stek29 That somehow didn't solve it.
I'll look into it and keep you in touch.

**Comment by TangMonk** [comment]
same problem

**Comment by mgwyness** [comment]
i had the same issue lately with my bot in a chat. i could trigger the OnText handler only by a text message starting with "/", even though my bot was configured to have access to all messages in a chat.
the problem was resolved by removing the bot from a chat and adding it back after making privacy off. 
i guess it's just how telegram works
