### ISSUE TITLE
Command alias

### ISSUE THREAD

**Issue by suntong** [tucnak/telebot#153]
How to deal with the case that I want to give an alias (short-form) to my command? 

```go
	b.Handle("/hello", func(m *tb.Message) {
		b.Send(m.Sender, "hello world")
	})
```

This deals with the `/hello` command. How to define a `/hi` command that does exactly what the above does? 

I tried to refactor the above function to `func sayHi(m *tb.Message) {...}` but found that I cannot use `b` within it any more. 

Sorry for the noob question, & thx

**Comment by stek29** [comment]
Golang has closures :)
