### ISSUE TITLE
Groups and Middlewares for dedicated groups and handlers

### ISSUE THREAD

**Issue by savely-krasovsky** [tucnak/telebot#155]
Like it works in many web frameworks. Can I provide such PR or you don't like this approach in bot library?

**Comment by lukaszraczylo** [comment]
I'd give it a go regardless :)

**Comment by tucnak** [comment]
I'd definitely vouch for such functionality! Sounds great, please share your code if you have any.

**Comment by demget** [comment]
Moved to #291
