### ISSUE TITLE
Channel messages is empty when there are full messages Telegram queue

### ISSUE THREAD

**Issue by aladine** [tucnak/telebot#16]
Hi Tucnak, I use your example to run my bot. when the traffic is risen up, I occasionally encounter no more messages are processed, even I restart the bot.

```
messages := make(chan telebot.Message)
    bot.Listen(messages, 1*time.Second)

    for message := range messages {
        if message.Text == "/hi" {
            bot.SendMessage(message.Chat,
                "Hello, "+message.Sender.FirstName+"!", nil)
        }
    }
```

If I use curl command in terminal curl -X POST [api_url]/getUpdates , then I got 100 messages queuing. Is there any reason why messages channel is not able to pick up these messages.

**Comment by tucnak** [comment]
Hey,

I just realized that underlying interfaces are absolutely synchronous, which is quite strange, since I remember writing them with concurrency in mind. Anyway, I see the problem, but don't see any clear reasonable solution here. Gimme some time, I'll dive into tonight.

**Comment by aladine** [comment]
Hi Ilya, I temporarily solve the issue. After checking the log, I realize 1/2 of pending messages are "/start" command. 
I use another library to pick up those "/start" command and run sending response message to this type individually. After that, the origin go process is able to pick up and clear the messages in channel.
Btw, I don't find any bug in "/start" command code of my bot.

**Comment by ejamesc** [comment]
I've been running a fairly successful bot with this library for some time, and I see this problem every few weeks. (Basically no more new messages come through to my bot, despite a full Telegram queue and no auth errors).

The problem is with supplying an `offset` param to getUpdates. If one doesn't periodically supply an `offset` message id, Telegram's API servers will never mark old messages as confirmed, and will hold on to them until the message buffer is completely filled. 

I manually made a request to Telegram's API servers with an offset param, and messages immediately started pouring through again.

Tell me if I'm missing something, @tucnak. (Say, if there's a feature to supply `offset` that I'm not aware of). 

I'll take a stab at fixing this before the week is over.

**Comment by ejamesc** [comment]
Ok this is really odd. I see in your source code that you're incrementing the offset by 1 in `Listen()`, so why am I seeing this problem? I'll do more tests and report back.

**Comment by tucnak** [comment]
@ejamesc Unfortunately, I couldn't reproduce this issue you and @aladine are talking about so far. The whole "offset based on the latest update id+1" idea is the only good idea I came up while hacking the fetcher and it seemed to work for me.

**Comment by aladine** [comment]
Until now I still get the same error every few weeks. 
Is there any case @ejamesc, you skip sendMessase in processing channel and the index keeps increments continuously. You probably reach a point where update_index is larger than the actual index on Telegram server.

**Comment by tucnak** [comment]
By the way, is there a chance it's an issue with Telegram servers? Just askin'.

**Comment by ejamesc** [comment]
Interesting! That's a good hypothesis @aladine, I've started logging my message ids, and will be watching out for this. Will confirm back in this thread if I find anything. 

    _____________________________

**Comment by Ronmi** [comment]
@aladine @ejamesc  The `offset` is counter of `Update.ID` not `Message.ID`, so sending message should not affect it.

But another possible case is maybe the `offset` is actually a 64bit integer. By using `int` type in `telebot`, this will be a problem on 32bit machines. Is your bot running bot on 32bit machine or compiled on 32bit machine without cross compiling? Unlike chat id, the size `offset` is not specified in API documentation, so I'm not quite sure if this is the case.
