### ISSUE TITLE
any example to handle inline query

### ISSUE THREAD

**Issue by jjhesk** [tucnak/telebot#160]
1. I tried to figure out how to use the inline button to call feedback to the bot by using inline query
2. I tried to trigger a popup banner on the top of the chat room

**Comment by kfreiman** [comment]
@jjhesk, there is great examples about [inline buttons](https://github.com/tucnak/telebot#keyboards) and [inline queries](https://github.com/tucnak/telebot#inline-mode) in README. Show some your code to define the problem. Did you look at the sources? It's the best way for deep understanding how to use it.

**Comment by jjhesk** [comment]
yes, i have tried out the samples but it doesnt work for me. are there much difference from the v2 and v1?

**Comment by jjhesk** [comment]
@kfreiman there is an issue that the Text button does not support emoji.

**Comment by kfreiman** [comment]
```
inlineBtn := tb.InlineButton{
	Unique: "sad_moon",
	Text: "🌚 Button #2",
}
```
What you mean?
