### ISSUE TITLE
Send photo? 

### ISSUE THREAD

**Issue by Dontmindmes** [tucnak/telebot#162]
I have this code

b.Handle("/hello", func(m *tb.Message) {
		p := &tb.Photo{File: tb.FromDisk("saber.jpg")}
		b.Send(m.Sender, p)
	})

but it does let me send a photo, how can i make it send a photo?

**Comment by kifirkin** [comment]
@Dontmindmes First, try to log `p` within this handler, to be sure that bot receives message, photo isn't empty and there is no network errors

**Comment by stek29** [comment]
also, b.Send returns message and error, check them
