### ISSUE TITLE
Proposal to create a handler interface for all handlers.

### ISSUE THREAD

**Issue by berkant** [tucnak/telebot#165]
Since I'm trying to add some kind of minimal middleware functionality to the library, and besides having problems with strong type assertion over interfaces in [Bot#handle](https://github.com/tucnak/telebot/blob/v2/bot.go#L381) I can't specify the custom type for returning literal in my own app as per the below:

 ```golang

   type msgHandler func(*tb.Message)

   requireAuth := func(next msgHandler) func(*tb.Message) {
		return func(m *tb.Message) {
			_, ok := users[m.Sender.Recipient()]
			if !ok {
				bot.Send(m.Sender, "Not reg!")
				return
			}

			next(m)
		}
	}

	bot.Handle("/ping", requireAuth(func(m *tb.Message) {
		bot.Send(m.Sender, "PONG!")
	}))
```
net/http itself does also incorporate a similar thing here. It has a function type, defined HandlerFunc and despite it being a function it also has a ServeHTTP method just to comply with an interface (http.Handler) to congree with outside declarations.

So, it'd be better and make things simpler if we added an interface and a handler alike, I guess. It'd also help creating a middleware chain system native to the library.

**Comment by demget** [comment]
It's about middlewares rework. #155
