### ISSUE TITLE
How to manage global variables in handle functions?

### ISSUE THREAD

**Issue by kv-gits** [tucnak/telebot#166]
If you try to place handler in separate function, global variable problem occures

```
func startHandler(m *tb.Message) {
	if !m.Private() {
		return
	}
	b.Send(m.Sender, "\xF0\x9F\x92\xAA hello world") // b should be global but global variable is unleasant
}
```
Is there any way of more declarative programming with telebot?

PS

Also somehow it does not work if handler is separeate func, only inline.

**Comment by stek29** [comment]
Rewriting with interfaces instead of raw functions would probably be better, but doing it without breaking backward compatibility is important.

I'd do something like this for now:

```go
import tb "gopkg.in/tucnak/telebot.v2"

type Handler struct {
	Bot *tb.Bot
}

func (h *Handler) startHandler(m *tb.Message) {
	if !m.Private() {
		return
	}
	h.Bot.Send(m.Sender, "hello world")
}

func (h *Handler) StartHandler() func(m *tb.Message) {
	return func(m *tb.Message) { h.startHandler(m) }
}
```

**Comment by stek29** [comment]
@kv-gits it's still an issue though :)

**Comment by kifirkin** [comment]
@kv-gits I guess it's not an issue with `telebot` instead it's a common application architecture problem. You could use some sort of `DI` or just global variables.

There are some posts about structuring golang apps [here](https://www.alexedwards.net/blog/organising-database-access) or [here](https://medium.com/@benbjohnson/structuring-applications-in-go-3b04be4ff091)

**Comment by stek29** [comment]
@alexmironof It's telebot's architecture problem.
It should accept objects conforming to some Handler interface -- that's what most libraries do.

**Comment by kifirkin** [comment]
@kv-gits Oh didn't get it at first glance! yeah actually it's the best option here!

**Comment by stek29** [comment]
oh, it's #165 related
