### ISSUE TITLE
Recommended approach for inline buttons

### ISSUE THREAD

**Issue by nadiamoe** [tucnak/telebot#167]
Hey,

First let me thank your for your effort on this library, I've been poking around a bit and it seems quite nice.

I've been struggling with one thing, however, which I can't find an elegant solution for. I have this simple bot which manages a number of entities for each user. Each of this entities have its own properties, which the user can modify. Pretty straight forward. Until now, all bots I've seen follow more or less the same approach to let the user change stuff:

* List entities using some `/list` command
* Edit entities using something like `/edit`

Now, the usual approach is to show the user a message with some inline buttons to select which entity they want to edit. The thing is, these inline buttons must be instantiated programatically, since the text and the action depends on the user and the entity which is going to be managed. I haven't found any way to do this with telebot. I can send the user an inline button, but when it is pressed, nothing happens, despite setting the `InlineButton.Action` to a simple function which just sends a message.

As I haven't found any examples on the docs about creating `InlineButton`s on the fly with an associated action and sending them back, I wonder if this is a supported operation at all, and if it isn't, what is the way to create this kind of functionality using telebot.

Thanks in advance and sorry for the wall of text

**Comment by kfreiman** [comment]
Hi @roobre! I think, the usual approach is using sessions. It provide better UX, because does not require additional data from user, like item's ID or forcing him to reply on exact message. Similar approach used at BotFather.

In your case it can looks like this
1. Predefined `/list` command which creates callback handler for every listed item (`chooseItemForEdit`)
2. Callback handler sets session state and tells user that he should send new name for choosed item
3. Each time when message receaved, `OnText` message checks the state of session. So, if user is in the item editing context, the message should be passed to `editItemName` handler.

```go
const (
  StateEditItemName int = 0
)

type SessionInterface interface {
  Set(key string, value interface{}) error
  Get(key string) interface{}
}

type UsecaseInterface interface {
  GetItemsByUser(userID int) (items []*Items, err error)
  GetItemByID(ID string) (item *Item, err error)
  EditItemName(ID string, name string) (item *Item, err error)
  GetSession(userID string) (sess SessionInterface, err error)
}

type Item struct {
  ID string
  Name string
}

type Handler struct {
  Bot          *tb.Bot
  Usecase      UsecaseInterface
}

func NewHandler(bot *tb.Bot, usecase UsecaseInterface) {
  h := &Handler{
    Bot:          bot,
    Usecase:      usecase,
  }

  bot.Handle("/list", h.listCommand)
  bot.Handle(tb.OnText, h.onText)
}

func (h *Handler) listCommand(m *tb.Message) {
  items, _ := h.Usecase.GetItemsByUser(m.Sender.ID)

  inlineKeys := h.getItemsListBtns(items)

  h.Bot.Send(sess.Msg.Sender, "Choose item:", &tb.ReplyMarkup{
    InlineKeyboard: inlineKeys,
  })
}

func (h *Handler) getItemsListBtns(items []*Item) [][]tb.InlineButton {
  inlineKeys := [][]tb.InlineButton{}
  for _, item := range items {
    inlineBtn := tb.InlineButton{
      Unique: "edit_item"+item.ID,
      Text:   item.Name,
      Data:   item.ID, // must be copatible with base64url or encoded to it
    }
    inlineKeys = append(inlineKeys, []tb.InlineButton{inlineBtn})
    h.Bot.Handle(&inlineBtn, h.chooseItemForEdit)
  }
  return inlineKeys
}

func (h *Handler) chooseItemForEdit(c *tb.Callback) {
  sess, _ := h.Usecase.GetSession(c.Sender.ID)
  itemID := c.Data
  item, _ := h.Usecase.GetItemByID(itemID)

  h.Bot.Send(
    c.Sender,
    `You're edit item `+item.Name+`, send me new name for it.`,
  )

  sess.Set("state", StateEditItemName)
  sess.Set("item_id", item.ID)
}

func (h *Handler) onText(m *tb.Message) {
  sess, _ := h.Usecase.GetSession(m.Sender.ID)

  if sess.Get("state") == StateEditItemName {
    h.editItemName(sess, m)
    return
  }
}

func (h *Handler) editItemName(sess, m *tb.Message) {
  itemID := sess.Get("item_id")
  err := h.Usecase.EditItemName(itemID, m.Text)

  if err == nil {
    h.Bot.Send( sess.Msg.Sender, `Item renamed!`)
  }
}
```

**Comment by nadiamoe** [comment]
I see, so basically you keep a context for every user and the last action they made, and then you use a generic handler and pivot depending on that context.

I  have thought about something like that before, but I wasn't entirely sure about the details. I appreciate your input and I'll give it a try to see if it fits my implementation, thanks!
