### ISSUE TITLE
Setting Content directly to Result

### ISSUE THREAD

**Issue by phrozen** [tucnak/telebot#178]
Hi, I'm trying to send some simple **Results** to an inline Query, but I want to be able to set the **ParseMode** to _Markdown_ or _HTML_ in an **ArticleResult**, but I can't set the embedded struct setting, as there is a shortcut Text which says it is mutually exclusive to that. How can I set it?

I tried creating a custom type that satisfies **Result**, but then **inferIQR** is called and totally wrecks my custom type (even if I set the **r.Type** manually to 'article'). Is this intended? I have checked most of the code and can't find a simple way to set my own **InputTextMessageContent** to a known type cause the **Content** field is shadowed.

**Comment by demget** [comment]
Fixed in #225
