### ISSUE TITLE
ReplyButton: endpoint doesn't work when I require Contact or Location.

### ISSUE THREAD

**Issue by berkant** [tucnak/telebot#179]
Using a `*ReplyButton` as an endpoint when `Contact` or `Location` is `true` doesn't work. I am having to listen on the generic event `OnContact` to receive contact data.

**Comment by pushax** [comment]
Same problem here

**Comment by bin16** [comment]
+1 for that 🤷‍♂️

**Comment by demget** [comment]
You can't use `ReplyButton` in the such way. Use `OnContact` and `OnLocation` handlers.
