### ISSUE TITLE
proposal: bot: identify the button by its callback

### ISSUE THREAD

**Issue by bazuker** [tucnak/telebot#185]
When you are putting a handler for an inline button, all you get in the callback is a reference to a callback object
```Go
func handler(c *tb.Callback) {
	...
}
```
but there is no way to identify which inline button this callback was made from. This prevents a developer from creating a handler middleware for inline buttons aggregation as there is no easy way to find the button that was pressed, as you just assume that every button has its own handler.

Something that would be great to have is
```Go
func handler(button *tb.InlineButton, c *tb.Callback) {
	...
}
```
or for the callback to have any button-related information. Even the unique id that is used in creation of an inline button would be very handy.

A good package anyways,
Thanks

**Comment by demget** [comment]
It's real with the context-based routing I described [here](https://github.com/tucnak/telebot/issues/158#issuecomment-605683512). Marked it as a feature, seems quite helpful.

**Comment by demget** [comment]
You can use `c.Callback().Unique` to identify the button.
