### ISSUE TITLE
Add payments

### ISSUE THREAD

**Issue by CssHammer** [tucnak/telebot#186]
When payments will be available?

**Comment by michaellee8** [comment]
@tucnak Do you have any plan to integrate it?

**Comment by tucnak** [comment]
Payments are already partially implemented in master, but it's not a complete implementation, so I didn't announce it. I'm currently maybe too busy to implement the remaining bits, but will do so eventually.

**Comment by michaellee8** [comment]
It is great, I can see that from godoc. hope that it will come eventually

**Comment by michaellee8** [comment]
@tucnak I actually have a bot that may uses Telegram Payment in active development. If I am in that stage of development before you have done that, may I contribute it?

**Comment by tucnak** [comment]
Yes please!

**Comment by stek29** [comment]
duplicate of #101
