### ISSUE TITLE
 FileURL and FilePath from Photo message is empty 

### ISSUE THREAD

**Issue by robatipoor** [tucnak/telebot#188]
> I would  download photo but FilePath and FileUrl is empty why ???

bot.Handle(tb.OnPhoto, func(m *tb.Message) {
		log.Println(m.Photo.FileURL) // FileURL  is empty  ; (
                log.Println(m.Photo.FilePath) // FilePath  is empty  ; (
                downloadPhotoFromUrl(m.Photo.FileURL) // error FileUrl is empty
		bot.Send(m.Sender, "ok download photo !")
})

**Comment by thapakazi** [comment]
Same here with *Document* :thinking:

**Comment by mrThe** [comment]
Same here. Temporary workaround:
Use `FileURLByID` method and download by `m.Photo.FileID`.

**Comment by equt** [comment]
FYI, telebot provides a `Download` function to download any files from Telegram server. See [`Bot.Download`](https://godoc.org/gopkg.in/tucnak/telebot.v2#Bot.Download).

P.S, maybe a much detailed documentation should be annotated in the `File` struct.

**Comment by demget** [comment]
`FileURL` and `FilePath` are used only for uploading. Use `Download` function to get your photo from Telegram servers by `file_id`.
