### ISSUE TITLE
How do I deploy a bot use webhook on Heroku?

### ISSUE THREAD

**Issue by robatipoor** [tucnak/telebot#200]

**Comment by demget** [comment]
Hi! You can use `Webhook` type that is implementing `Poller` interface.

Simple example:
```go
package main

import (
	"log"
	"os"

	tb "github.com/tucnak/telebot"
)

func main() {
	var (
		port      = os.Getenv("PORT")
		publicURL = os.Getenv("PUBLIC_URL") // you must add it to your config vars
		token     = os.Getenv("TOKEN")      // you must add it to your config vars
	)

	webhook := &tb.Webhook{
		Listen:   ":" + port,
		Endpoint: &tb.WebhookEndpoint{PublicURL: publicURL},
	}

	pref := tb.Settings{
		Token:  token,
		Poller: webhook,
	}

	b, err := tb.NewBot(pref)
	if err != nil {
		log.Fatalln(err)
	}

	b.Handle("/start", func(m *tb.Message) {
		b.Send(m.Sender, "Hi!")
	})

	b.Start()
}
```

**Comment by robatipoor** [comment]
thank you very much

**Comment by talentlessguy** [comment]
What about adding this to README?

**Comment by v1rtl** [comment]
> Hi! You can use `Webhook` type that is implementing `Poller` interface.
> 
> Simple example:
> 
> ```go
> package main
> 
> import (
> 	"log"
> 	"os"
> 
> 	tb "github.com/tucnak/telebot"
> )
> 
> func main() {
> 	var (
> 		port      = os.Getenv("PORT")
> 		publicURL = os.Getenv("PUBLIC_URL") // you must add it to your config vars
> 		token     = os.Getenv("TOKEN")      // you must add it to your config vars
> 	)
> 
> 	webhook := &tb.Webhook{
> 		Listen:   ":" + port,
> 		Endpoint: &tb.WebhookEndpoint{PublicURL: publicURL},
> 	}
> 
> 	pref := tb.Settings{
> 		Token:  token,
> 		Poller: webhook,
> 	}
> 
> 	b, err := tb.NewBot(pref)
> 	if err != nil {
> 		log.Fatalln(err)
> 	}
> 
> 	b.Handle("/start", func(m *tb.Message) {
> 		b.Send(m.Sender, "Hi!")
> 	})
> 
> 	b.Start()
> }
> ```

Where can I get heroku port? and public URL is app's url?

**Comment by demget** [comment]
> Where can I get heroku port? and public URL is app's url?

`PORT` variable sets by Heroku automatically. `PUBLIC_URL` is your application's url, for example `https://yourbot.herokuapp.com`

**Comment by v1rtl** [comment]
> > Where can I get heroku port? and public URL is app's url?
> 
> `PORT` variable sets by Heroku automatically. `PUBLIC_URL` is your application's url, for example `https://yourbot.herokuapp.com`

Thank you for explanation :). Would be great to put this into README

**Comment by demget** [comment]
> Would be great to put this into README

I would be very happy in contributing to the project, but it seems that the author of repository hadn't any activity on it for a long time. So, there is only one way to make `telebot` better - fork it and improve the package yourself.
