### ISSUE TITLE
Need bot's examples for new users

### ISSUE THREAD

**Issue by cybervagabond** [tucnak/telebot#201]
Dear community, at first thank you for library.
Started to learn Go, and got some troubles at starting with library.

There are many people that don't know language good, about patterns, UML, etc.
by reading README pepople can't start to write some production code without good knowledge of Go.
What are you think about creating some bot's examples for some cases, for example:
- Integrating bot with database
- Using FSM
- Create some good helpers handlers for creating buttons, etc.
- Right way of creating project structure.

If you want earn more popularity and stars it will be good idea to provide some bot's templates.
For example like in this library:
https://github.com/python-telegram-bot/python-telegram-bot/tree/master/examples

And very strange thing:
Library for creating Telegram bot's but without Telegram group?

**Comment by erkexzcx** [comment]
Or at least any examples...

**Comment by mitinarseny** [comment]
@cybervagabond @erkexzcx 
You can take a look at [telego](https://github.com/mitinarseny/telego) template project that is intended exactly for these reasons. 
If something is not clear or there is some errors or suggestions, please, do not hesitate to create an issue and describe it there.

**Comment by demget** [comment]
> You can take a look at [telego](https://github.com/mitinarseny/telego) template project that is intended exactly for these reasons.

Hmm good job, but as for me, repo architecture isn't the best choice for Telegram bot. You shouldn't have `utils` package at least, following to [Package names Guide](https://blog.golang.org/package-names) and [Effective Golang](https://golang.org/doc/effective_go.html). It's also better to use `gofmt` tool or something. Anyway, best luck in improving your template.

I can share my vision of good bot architecture and package structure, that I used for all of my works. It also uses my forked telebot, adapted to json config files and Go "text/template" package. I will left it here later.

**Comment by mitinarseny** [comment]
> Hmm good job, but as for me, repo architecture isn't the best choice for Telegram bot. You shouldn't have `utils` package at least, following to [Package names Guide](https://blog.golang.org/package-names) and [Effective Golang](https://golang.org/doc/effective_go.html). It's also better to use `gofmt` tool or something. 

@demget Sure, it's still in work. I am still implementing some features, but thank you for having a look and feedback!
P.S.: I definitely will remove `utils` package, you're right...

**Comment by demget** [comment]
I will think about it and maybe prepare some examples as soon as `v2.1` will be finished

**Comment by x777** [comment]
> architecture

Hi, where I can see 

> I can share my vision of good bot architecture and package structure, that I used for all of my works. It also uses my forked telebot, adapted to json config files and Go "text/template" package. I will left it here later.

Hi, where I can see it? Would be good to see the best practice of good bot architecture. Thx!
