### ISSUE TITLE
added go.mod breaks things

### ISSUE THREAD

**Issue by quite** [tucnak/telebot#202]
It seems the addition of go.mod broke things slightly. I'm importing `gopkg.in/tucnak/telebot.v2` (and using go mod), and I'm now getting this from `go get -u` (to bump deps):

    go: finding gopkg.in/tucnak/telebot.v2 latest
    go: gopkg.in/tucnak/telebot.v2@v2.0.0-20190329142548-9b714b274c8a: go.mod has non-....v2 module path "github.com/tucnak/telebot" at revision 9b714b274c8a
    go get: error loading module requirements

**Comment by stek29** [comment]
probably `github.com/tucnak/telebot` needs to be replaced with `github.com/tucnak/telebot.v2`.

See olivere/elastic#869

**Comment by quite** [comment]
telebot's `go.mod` needs to say `module gopkg.in/tucnak/telebot.v2`, then. Yes that makes sense to me... It's hard to fork and test it out, precisely due to the gopkg.in-resolver

**Comment by tucnak** [comment]
Thank you! Yes it is still confusing to build things with the new module system...
