### ISSUE TITLE
ChatByID returns error if chat id is provided without @

### ISSUE THREAD

**Issue by DevAlone** [tucnak/telebot#207]
https://godoc.org/github.com/tucnak/telebot#Bot.ChatByID

Would be awesome if it worked both with and without @

**Comment by stek29** [comment]
I don’t think it’s a good idea — why should telebot add @ automatically? How should it be implemented? What if TG changes how BotAPI getChat works?

**Comment by DevAlone** [comment]
It's been long time and I don't actually remember why I opened this issue, but it seems that it wasn't obvious that you should add @ manually.
