### ISSUE TITLE
docs broken after API change

### ISSUE THREAD

**Issue by nf** [tucnak/telebot#21]
The docs say that to send a message in response to receiving a message, you should write

```
bot.SendMessage(message.Chat, ...)
```

but with recent API changes, `SendMessage` takes a `User`, not a `Chat`. At the least, the docs are wrong.

But there seems to be a shortcoming here. The `Message` type has a `Sender` field of type `User`, but the docs say it may be empty for group chats. My bot receives messages from a group. How do I send messages back to the group?

**Comment by tucnak** [comment]
Goddamn, looks like the last commit broke the whole thing, gimme some time to fix it.

**Comment by nf** [comment]
My code compiles after 72ce8fae88cff87483f2dc0689f12283b4dc08b6

**Comment by tucnak** [comment]
Yeah, I just introduced a `Recipient` interface for both chats and users. Might do a trick. I am still really sorry for braking compatibility, will look into PRs more carefully next time.

**Comment by nf** [comment]
Thanks!
