### ISSUE TITLE
How to make a handler for specific situations?

### ISSUE THREAD

**Issue by MasterGroosha** [tucnak/telebot#210]
First of all, thank you for this library! I'm coming from [pyTelegramBotAPI](https://github.com/eternnoir/pyTelegramBotAPI), where I can define specific handlers for specific messages, for example:
```python
@bot.message_handler(func=lambda message: message.from_user.id == 1234567)
def message_from_myself(message):
    print("Hello, me!")
```
Function `message_from_myself()` will only "fire" if statement `message.from_user.id == 1234567` is True), so that I can handle a very specific situation in a separate piece of code, increasing overall readability. Generally any statement can be put in that lambda, like `lambda message: message.text == "Hello"` or `lambda message: message.text and len(message.text) > 20`
Is it possible to do something like that with your telebot?
Thanks in advance.

**Comment by demget** [comment]
Move your bot specific commands to another package, like `bot`. Wrap original `tb.Bot` type with your own, and implement additional logic. For example, we want to handle some admin-only commands. Let's create `WithFilter` package function, which wraps your handler and make it execute only if `filter` returns `true`.

```go 
package bot

// bot.go

type Bot struct {
	*tb.Bot
}

func New() (*Bot, error) {
	b, err := tb.NewBot(pref)
	if err != nil {
		return nil, err
	}
	return &Bot{b}, nil
}

func WithFilter(handler func(*tb.Message), filter func(*tb.Message) bool) func(*tb.Message) {
	return func(m *tb.Message) {
		if filter(m) {
			handler(m)
		}
	}
}

// stats.go

func (b *Bot) HandleStats(m *tb.Message) {
	// send some admin statistics
}
```

Finally,
```go
package main

func main() {
	b, err := bot.New()
	if err != nil {
		log.Fatalln(err)
	}

	// ...
	b.Handle("/stats", bot.WithFilter(b.HandleStats, adminOnly))
	b.Start()
}

var conf config.Config // parsed config

func adminOnly(m *tb.Message) bool {
	return m.Sender.ID == conf.AdminID
}
``` 

But remember, for filtering callbacks or queries, you should extend `WithFilter` or create one more. You can also store your filters in another file or package.
