### ISSUE TITLE
Vague "Could not fetch new updates" error if webhook is set

### ISSUE THREAD

**Issue by MasterGroosha** [tucnak/telebot#214]
I had `2019/07/24 22:49:53 telebot: could not fetch new updates` errors when starting a bot. It doesn't tell me that another webhook is set neither it provides method `RemoveWebhook`

**Comment by v1rtl** [comment]
Same issue when using with [Taskfile](taskfile.dev) with flag `--watch` (e.g. restarting on change)

**Comment by demget** [comment]
I don't know how relevant this problem is now. If it is, please re-open and I will check it.

**Comment by stek29** [comment]
seems relevant to me

<img width="581" alt="image" src="https://user-images.githubusercontent.com/11808223/77974643-6b8fc580-7300-11ea-9c46-6286ce091d8c.png">

**Comment by demget** [comment]
@stek29 Oh, you're right.. There is no implemented `deleteWebhook`. Gonna fix it in `2.1`.

**Comment by demget** [comment]
I also noticed that there is no implemented [`getWebhookInfo`](https://core.telegram.org/bots/api#getwebhookinfo) method to check if bot using a webhook or not. We still have some work on here. Gonna keep it for this issue.

**Comment by demget** [comment]
Implemented in https://github.com/tucnak/telebot/commit/1157f8b301813dfdc61495f9a12867baf0dd62ad. `WebhookInfo` fields are available in the `Webhook` type.
