### ISSUE TITLE
Serverless support?

### ISSUE THREAD

**Issue by phrozen** [tucnak/telebot#219]
Hey, is there a way you could expose a method to process a single update for serverless (cloud functions, lambdas, etc...) support of bots? Usually all providers (AWS, Azure, GCN, etc...) stick to Go's standard library of executing a singe handler `func Handle(res http.ResponseWriter, req *http.Request)`. 

It would be amazing to pass that to my bot like `bot.HandleUpdate(res, req)` and forget about it. The bot already does that but it is unexposed and inside the `Start()` and `Poller()` methods. I don't want to start a server, just handle a single update from a request, route, execute a handler and write a response. Is that possible?

That would also make it super easy to include the bot into an existing server/codebase on an endpoint.

**Comment by demget** [comment]
#279 related? I think we can close it now.
