### ISSUE TITLE
Example of inline button callback?

### ISSUE THREAD

**Issue by v1rtl** [tucnak/telebot#221]
I've read both [Telegram bot API docs](https://core.telegram.org/bots/api#callbackquery) and [GoDoc](https://godoc.org/gopkg.in/tucnak/telebot.v2#CallbackResponse) and I'm confused. How do I implement sending messages on inline button click?

I have this:

```go
inlineBtn := tb.InlineButton{
		Unique: "sad_moon",
		Text: "ФИО",
	}

	inlineKeys := [][]tb.InlineButton{
		[]tb.InlineButton{inlineBtn},
	}

        // Doesn't even trigger
	b.Handle(&inlineBtn, func(m *tb.Message) {
		b.Send(m.Sender, "You pressed the button!")
	})

	b.Handle(&inlineBtn, func(c *tb.Callback) {
		b.Respond(c, &tb.CallbackResponse{
			Text: "Hello World",
                        // What should I put here?
		})
	})


	b.Handle("/start", func(m *tb.Message) {
		b.Send(
			m.Sender, "Hello World", &tb.ReplyMarkup{ InlineKeyboard: inlineKeys })
	})
```

How do I pass `b.Send` to callback of a button?

Seems like related to #66.

**Comment by demget** [comment]
Try this
```go
b.Handle(&inlineBtn, func(c *tb.Callback) {
	b.Send(c.Sender, "You pressed the button!")
})
```

Use:
`func(m *tb.Message)` for simple text messages
`func(c *tb.Callback)` for inline buttons
`func(q *tb.Query)` for inline queries

What kind of object for specific situation is coming you can check [here](https://github.com/tucnak/telebot/blob/v2/bot.go#L185).

**Comment by v1rtl** [comment]
@demget thanks! that worked!

```go
	inlineBtn := tb.InlineButton{
		Unique: "name",
		Text:   "ФИО",
	}

	inlineKeys := [][]tb.InlineButton{
		[]tb.InlineButton{inlineBtn},
	}

	b.Handle(&inlineBtn, func(c *tb.Callback) {
		b.Respond(c, &tb.CallbackResponse{
			ShowAlert: false,
		})
		b.Send(c.Sender, "You pressed the button!")
	})
```
