### ISSUE TITLE
Photo sendable forgets caption on multiple sends

### ISSUE THREAD

**Issue by JustAnOpossum** [tucnak/telebot#228]
I have a photo sendable object and the caption works great when I send it to one person, but when I loop to send to more than one person the caption is lost.

```go
	sendPhoto := tgAPI.Photo{
		File:    tgAPI.FromReader(img.ImgReader),
		Caption: photoCaption,
	}
```

The photo is sent in a loop like this
```go
	_, err := sendPhoto.Send(bot, &tgUser, &tgAPI.SendOptions{
			ParseMode: tgAPI.ModeMarkdown,
	})
```

The first person gets an image with the correct caption, but anyone after them is missing the caption.

**Comment by demget** [comment]
Hello! 

My last #226 PR fixed this issue. 
Please, check if you have the last version of telebot package.

This code is working for me:
```go
photo := &tb.Photo{
	File:    tb.FromReader(),
	Caption: "caption",
}
b.Send(&user, photo, tb.ModeMarkdown) // sends "caption"
b.Send(&user, photo, tb.ModeMarkdown) // sends "caption"
b.Send(&user, photo, tb.ModeMarkdown) // sends "caption"

**Comment by JustAnOpossum** [comment]
I updated with 
```
go get -u gopkg.in/tucnak/telebot.v2
```

And the problem is still happening, is there another way to update the plugin?

**Comment by stek29** [comment]
@NerdyRedPanda do you use go modules? What’s the version listed in go.sum?

**Comment by demget** [comment]
Again, code I sent above works pretty fine. I think all is ok here.
