### ISSUE TITLE
Add debug mod

### ISSUE THREAD

**Issue by Kohinor46** [tucnak/telebot#233]
Hi!
 
All is great, but please add debug mod to log all actions

**Comment by stek29** [comment]
What exactly do you mean by “all actions”?

Is using custom http Client which logs requests (see https://github.com/motemen/go-loghttp for example) enough?

**Comment by Kohinor46** [comment]
log.Println (Message.Sender.Username or Message.Sender.Chat.Username and Message.Text) for all updates get from telegram.

**Comment by stek29** [comment]
Just use MiddleWarePoller:
```go
poller := &tb.LongPoller{Timeout: 15 * time.Second}
debugPoller := tb.NewMiddlewarePoller(poller, func(upd *tb.Update) bool {
    if upd.Message != nil {
        log.Println(upd.Message.Sender.Username, upd.Message.Chat.Username, upd.Message.Text)
    }
    return true
})
bot, _ := tb.NewBot(tb.Settings{
	// ...
	Poller: debugPoller,
})
```
