### ISSUE TITLE
Why get the same image from https://thispersondoesnotexist.com/image with tb.fromURL

### ISSUE THREAD

**Issue by shkabaturd** [tucnak/telebot#234]
When i update the page in browser image new every time, i want use it in my program, but in program image from time to time the same. I suppose the problem is caching, but I don’t know how to check it. i create image:
photo := &tb.Photo{File: tb.FromURL("https://thispersondoesnotexist.com/image"), Caption: s} 
then send it.

**Comment by demget** [comment]
Show your full code please. Do you create photo every time before sending?

**Comment by shkabaturd** [comment]
> Show your full code please. Do you create photo every time before sending?

	b.Handle(tb.OnText, func(m *tb.Message) {
		s := ""
		if m.Sender.FirstName != "" {
			s += m.Sender.FirstName + " "
			if m.Sender.LastName != "" {
				s += m.Sender.LastName
			}
		} else {
			if m.Sender.Username != "" {
				s += m.Sender.Username
			}
		}

		s += " says: " + m.Text
		photo := &tb.Photo{File: tb.fromURL("https://thispersondoesnotexist.com/image"), Caption: s, Width: 100, Height: 120}
		for _, user := range users {
			//if user.ID != m.Sender.ID {
			b.Send(&user, photo)
			//}
		}

**Comment by demget** [comment]
Try to create new photo instance for each user inside the loop, like here:
```go
for _, user := range users {
        b.Send(&user, &tb.Photo{
                File:    tb.FromURL("https://thispersondoesnotexist.com/image"), 
                Width:   100, 
                Height:  120,
                Caption: s, 
        })
}
```

**Comment by shkabaturd** [comment]
> Try to create new photo instance for each user inside the loop, like here:
> 
> ```go
> for _, user := range users {
>         b.Send(&user, &tb.Photo{
>                 File:    tb.FromURL("https://thispersondoesnotexist.com/image"), 
>                 Width:   100, 
>                 Height:  120,
>                 Caption: s, 
>         })
> }
> ```

i have the same result, the same photo. 
The photo does not change between program restarts and computer restart.
when i save photo to disk and use tb.FromDisk() it's works fine.

**Comment by demget** [comment]
It seems that Telegram caches photo by url on its side. Then try to download photos manually.

This piece of code is working for me:
```go
b.Handle(tb.OnText, func(m *tb.Message) {
    var name string
    if m.Sender.Username != "" {
        name = m.Sender.Username
    } else {
        name = strings.TrimSpace(strings.Join([]string{
            m.Sender.FirstName,
            m.Sender.LastName,
        }, " "))
    }

    for i := 0; i < 5; i++ {
        resp, err := http.Get("https://thispersondoesnotexist.com/image")
        if err != nil {
            log.Println(err)
        }

        b.Send(m.Sender, &tb.Photo{
            File:    tb.FromReader(resp.Body),
            Width:   100,
            Height:  120,
            Caption: fmt.Sprintf("%s says: %s", name, m.Text),
        })

        resp.Body.Close()
    }
})
```

**Comment by shkabaturd** [comment]
Thank You!
