### ISSUE TITLE
InlineButton Action callback not working

### ISSUE THREAD

**Issue by indes** [tucnak/telebot#235]
Hi, I find `Action` in the struct InlineButton definetion, but the following code is not working.

```golang
tb.InlineButton{
	Unique:          "confirm_btn",
	Text:            "confirm",
	Data:            "c",
	Action: func(callback *tb.Callback) {
		log.Println(callback.ID)
	},
}
```

Is that the only way to bind InlineButton callback function by use `Handle()`?

**Comment by demget** [comment]
This is not used anywhere, so the only way to handle callbacks is to use `Handle()`.

**Comment by indes** [comment]
Thanks!
