### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by mixazya** [tucnak/telebot#236]
Hello. Latest release v2 was 2 years ago. Could you make new with current features ( maybe 2.1? ) to simply use in go projects.

**Comment by cybervagabond** [comment]
+1
Interested in updates of this repository
also there are interesting fork https://github.com/demget/telebot

Go is blazing fast and awesome for developing telegram bots, but libraries in Python are instrumented much better.

Why @tucnak made just only API implementation, doing wrapper will be much better.
Maybe author busy on another work, but lot of people what to know about feature of this awesome library :)

**Comment by demget** [comment]
Hey! I agree with an idea of releasing something new and interesting.

My [https://github.com/demget/telebot](fork) is very helpful in configuring **all** things outside Go code. Messages, buttons, inline markups, query results – you can store them in single file, with no need to change the source code.

I use it for all of my highly loaded bots, but there are still some problems. I use json to configure main bot's instances, which is awkwardly when a template pipeline return number or you just need to comment some section. So I'm going to move to the yaml, as main config language.

`Content` updates are something new to try in new `v3` release of this library. Main contributors may check this out and if It's ok I'll be happy to help with implementing new features in original repositiory.

**Comment by demget** [comment]
Working on it! I hope `v2.1` will be released very soon!
