### ISSUE TITLE
Bot reply user chat

### ISSUE THREAD

**Issue by mpermperpisang** [tucnak/telebot#238]
Hello, 

can the bot reply the user chat like this? because I try the func Reply and the behaviour is just like func Send.
anyone try this before?

<img width="276" alt="Screen Shot 2019-12-13 at 19 21 50" src="https://user-images.githubusercontent.com/20101521/70800128-0ad68e80-1dde-11ea-9a66-04adfdcf0c66.png">

**Comment by demget** [comment]
Yes, `b.Reply(msg, ...)` must work. Can you show your code please?

**Comment by mpermperpisang** [comment]
hi @demget 

this in package main and func main
```
	bot.Handle(telebot.OnText, func(m *telebot.Message) {
		command.Main(bot, m, group)
	})
```

this in package command and func Main
```
func Main(bot *telebot.Bot, m *telebot.Message, group string) {
	var contentMessage string

	readMember()

	replyTo := telebot.Message{ID: m.ID}
        contentMessage := "testing"

	bot.Reply(&replyTo, contentMessage, telebot.ModeHTML)
}
```

**Comment by demget** [comment]
Try this code:
```go
func Main(bot *telebot.Bot, m *telebot.Message, group string) {
	readMember()

        contentMessage := "testing"
	bot.Reply(m, contentMessage, telebot.ModeHTML)
}
```

**Comment by mpermperpisang** [comment]
nice it works
thanks @demget 

<img width="828" alt="Screen Shot 2019-12-13 at 19 56 22" src="https://user-images.githubusercontent.com/20101521/70801917-acf87580-1de2-11ea-9cc3-7df8712c43f0.png">

**Comment by mpermperpisang** [comment]
solved
