### ISSUE TITLE
Update location broken?

### ISSUE THREAD

**Issue by rengglian** [tucnak/telebot#239]
I have trouble updating the live location of my bot.
Send text and send location work as expected.

```
	go func() {
		var _tempMessage = &tb.Message{}
		for _botResponse := range botResponse {
			fmt.Println("AutoResponse")
			switch _botResponse.Reply {
			case "text":
				bot.Send(chatGroup, _botResponse.Msg.Text)
			case "location":
				_tempMessage, _ = bot.Send(chatGroup, _botResponse.Msg.Location)
			case "updateLocation":
				fmt.Println(_tempMessage.MessageSig())
				fmt.Println(tb.Location{Lat: _botResponse.Lat, Lng: _botResponse.Lng})
				bot.Edit(_tempMessage, tb.Location{Lat: _botResponse.Lat, Lng: _botResponse.Lng})
			default:
			}
		}
	}()
```

The console output shows the correct message and chat id. 

Any ideas what is wrong?
If you need more information let me know

**Comment by demget** [comment]
Hm.. Seems like it's a bug. I will extend `Edit` with `editMessageLiveLocation` method in `v2.1`.

**Comment by demget** [comment]
Fixed in https://github.com/tucnak/telebot/commit/4e2f28c4f3c15423a75af0f5b514c8b2090e209e of `develop` branch
