### ISSUE TITLE
Add to album files from directory

### ISSUE THREAD

**Issue by Kohinor46** [tucnak/telebot#243]
Hi!

Can you please help me?
I try to create album with files in directory. I use cycle for it.
But go returns me errors.
How i can autoadd files from dir to album?

**Comment by demget** [comment]
Can you show your code please?

**Comment by Kohinor46** [comment]
`b.Handle(&Menu, func(m *tb.Message) {
		var album tb.Album
		for index, photo := range config.Menu_photo{
			album = append(album, tb.InputMedia(tb.FromDisk(photo)))
		}
		b.Send(m.Sender, album)
}`

It returns me error:
cannot convert telebot.FromDisk(photo) (type telebot.File) to type telebot.InputMedia: telebot.File does not implement telebot.InputMedia (missing MediaFile method)

**Comment by demget** [comment]
First of all, check out package's readme: https://github.com/tucnak/telebot#sendable
It shows how sendable objects and album wokrs.

`tb.From*` functions returns a `tb.File`, that you have to pass into another media type like `tb.Photo`, `tb.Video`... `tb.Album` can contains any of this, but always use `b.SendAlbum` to send your message correctly.

This code inside your handler will work:
```go
var album tb.Album
for _, photo := range photos {
    album = append(album, &tb.Photo{
        File: tb.FromDisk(photo),
    })
}
_, err := b.SendAlbum(m.Sender, album)
if err != nil {
    log.Println(err)
}
```

**Comment by Kohinor46** [comment]
now telebot returns error:
`album entry #0 doesn't exist anywhere`
But when i add `log.Println (photo)` it see pwd to files:
`2020/01/07 14:08:37 /Users/anatolijgracev/go/src/XXX/menu1
2020/01/07 14:08:37 /Users/anatolijgracev/go/src/XXX/menu2
2020/01/07 14:08:37 telebot: album entry #0 doesn't exist anywhere`

**Comment by Kohinor46** [comment]
Sorry my mistake.
Thank you!
