### ISSUE TITLE
telebot: could not fetch new updates

### ISSUE THREAD

**Issue by Aoi-hosizora** [tucnak/telebot#246]
I create a telebot through `telebot.NewBot` and `telebot.LongPoller`(it says `telebot: can't start without a poller` so I set timeout 1 hour), but it panic frequently of the message `telebot: could not fetch new updates`.

I also tried in windows 10 1803 and golang 1.13.5, and it won't panic.

My environment:
+ go 1.13.7 linux/amd64
+ ubuntu 16.04

Here is some of my code and panic stacktrace:

```go
poller := &telebot.LongPoller{
	Timeout: 3600 * time.Second,
}
bot, err := telebot.NewBot(telebot.Settings{
	Token:  'xxx',
	Poller: poller,
})
// bot.Handle(xxx)
go b.Bot.Start()
// for { xxx }
```

```bash
2020/02/09 09:33:28 telebot: could not fetch new updates
gopkg.in/tucnak/telebot%2ev2.init
        /root/go/pkg/mod/gopkg.in/tucnak/telebot.v2@v2.0.0-20200120165535-b6c3367fed99/poller.go:10
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5222
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5217
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5217
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5217
runtime.main
        /usr/local/go/src/runtime/proc.go:190
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
gopkg.in/tucnak/telebot%2ev2.(*Bot).debug
        /root/go/pkg/mod/gopkg.in/tucnak/telebot.v2@v2.0.0-20200120165535-b6c3367fed99/util.go:12
gopkg.in/tucnak/telebot%2ev2.(*LongPoller).Poll
        /root/go/pkg/mod/gopkg.in/tucnak/telebot.v2@v2.0.0-20200120165535-b6c3367fed99/poller.go:97
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```

**Comment by demget** [comment]
Make sure you correctly terminated previous running programs. There is only one poller at the same time allowed for your bot.

Also, it's better to call `Start()` in current goroutine, remove `go` keyword before your start function.

**Comment by Aoi-hosizora** [comment]
@demget Oh, I find that my IDE was running and listening my bot all the time, and I have modified my code to the following, thanks :)

```go
defer func() {
    bot.Stop()
)()
go someFunction() // for { xxx }
bot.Start()
```

**Comment by suntong** [comment]
I suddenly got this too, every minutes or two. 

- I've made sure there is only one poller at the same time by changing to all those bots that I never used before.

Yet I'm still getting the above error. 
My code is as simple as [this](https://github.com/suntong/kuaizh/blob/master/telebot/demo0.go) and I run with `go run demo0.go`.
What could be wrong?
