### ISSUE TITLE
Is it possible to get message by id?

### ISSUE THREAD

**Issue by stromperton** [tucnak/telebot#247]
I don`t found any methods to get tb.Message entity from chat by id of this message.
I need to get last bot message(tb.Message.id - 1) to make a system for update user name. Is better solution for this?
Example:
- User send command "/editname"
- Bot handle command and send message like a "Send me your new name"
- User send new user name
- So... How bot can handle it for update?

I just save every tb.Message when Bot.Send to my database and check it every OnText handler.
It is ok or i am fool?

**Comment by demget** [comment]
I think you need something like finite state machine

```go
b.Handle(tb.OnText, onText)
b.Handle("/editname", onEditName)

func onText(m *tb.Message) {
    // go to your db or local cache to know what kind of data you waiting
    // we need different actions to do for each command

    state, err := db.UserState(m.Sender.ID)
    // check err

    switch state {
    case "edit_name":
        db.UpdateUserName(m.Sender.ID, m.Text)
    case "edit_something_else":
        // ...
    }
}

// Your `/editname` command handler
func onEditName(m *tb.Message) {
    db.SetUserState(m.Sender.ID, "edit_name")
}
```

**Comment by stromperton** [comment]
@demget, thank you! You are awesome. Really ashamed for this easy thing...
By the way, get message by id is possible? I thing someone else will needing this.

**Comment by demget** [comment]
> By the way, get message by id is possible? I thing someone else will needing this.

There is no way to get message info by id with Bot API. Take a look at [Client API](https://core.telegram.org/api).

**Comment by stromperton** [comment]
Thank you!
