### ISSUE TITLE
How to create and handle callback for inlineKeyboardButton in a for-loop?

### ISSUE THREAD

**Issue by BennyThink** [tucnak/telebot#252]
Hi dear developers, 
firstly thanks for creating this amazing library!

I want to create multiple inlineKeyboardButton is a for-loop, and then when user click the button, we response with different handlers, send different text

I've tried the following code, the button is okay, but callback never works.

```go
var count = 3
	var btns []tb.InlineButton
	for i := 0; i <= count; i++ {
		var temp = tb.InlineButton{
			Unique: fmt.Sprintf("u %d", i),
			Text:   fmt.Sprintf("text %d", i),
		}
		btns = append(btns, temp)
	}

	inlineKeys := [][]tb.InlineButton{
		btns,
	}


	for i := 0; i <= count; i++ {
		b.Handle(&btns[i], func(c *tb.Callback) {
			_ = b.Respond(c, &tb.CallbackResponse{Text: "hello"})
			_, _ = b.Send(c.Sender, "hey")
		})
	}

	b.Handle("/run", func(m *tb.Message) {
		_, _ = b.Send(m.Sender, "Hello!", &tb.ReplyMarkup{
			InlineKeyboard: inlineKeys,
		})
	})
```

* button is okay
![image](https://user-images.githubusercontent.com/14024832/76135105-00373880-605f-11ea-80c7-9997056e5a89.png)

* but the click never returns

## try 1 : handler paste
I tried to manually copy&paste the inlineKeyBoardbutton a few times, write handler by copy & paste, just like this:
```go
inlineBtn1 := tb.InlineButton{
		Unique: "btn1",
		Text:   "Button #1",
	}

	inlineBtn2 := tb.InlineButton{
		Unique: "btn2",
		Text:   "Button #2",
	}
	inlineKeys := [][]tb.InlineButton{
		[]tb.InlineButton{inlineBtn1},
		[]tb.InlineButton{inlineBtn2},
	}

	b.Handle(&inlineBtn1, func(c *tb.Callback) {
		_ = b.Respond(c, &tb.CallbackResponse{Text: "ok1"})
		_, _ = b.Send(c.Sender, "hey1")
	})
	b.Handle(&inlineBtn2, func(c *tb.Callback) {
		_ = b.Respond(c, &tb.CallbackResponse{Text: "ok2"})
		_, _ = b.Send(c.Sender, "hey2")
	})

```
And it works
![image](https://user-images.githubusercontent.com/14024832/76135179-83f12500-605f-11ea-8e1a-2ad2a6443d5b.png)

## try 2, manually write handlers
just manually write handers, `tb.InlineButton` in a loop
```go
b.Handle(&btns[0], func(c *tb.Callback) {
		_ = b.Respond(c, &tb.CallbackResponse{Text: "dsdsa"})
		_, _ = b.Send(c.Sender, "hey")
	})
	b.Handle(&btns[1], func(c *tb.Callback) {
		_ = b.Respond(c, &tb.CallbackResponse{Text: "dsdsa"})
		_, _ = b.Send(c.Sender, "hey")
	})
```

It's not working

## try 3 manually add inlinebutton, and others in a loop
```go
var btns []tb.InlineButton
	inlineBtn1 := tb.InlineButton{
		Unique: "btn1",
		Text:   "Button #1",
	}

	inlineBtn2 := tb.InlineButton{
		Unique: "btn2",
		Text:   "Button #2",
	}

	btns = append(btns, inlineBtn1)
	btns = append(btns, inlineBtn2)
	inlineKeys := [][]tb.InlineButton{
		btns,
	}

	for i:=0;i<=1;i++{
		b.Handle(&btns[i], func(c *tb.Callback) {
			_ = b.Respond(c, &tb.CallbackResponse{Text: "dsdsa"})
			_, _ = b.Send(c.Sender, "hey")
		})
	}
```
and it works!

## conclusion
so from my point, it seems the reason is I can't create `tb.InlineButton` in  for-loop. But I really need to do this in a loop.
I just don't know what's wrong with this for-loop, it's really confusing. Any hint would be appreciate and help me a lot. Thanks!

**Comment by demget** [comment]
The problem is in space inside your `Unique` string, just remove it.

```go
tb.InlineButton{
    Unique: fmt.Sprintf("u%d", i),
    Text:   fmt.Sprintf("text %d", i),
}
```

Reason: ```cbackRx = regexp.MustCompile(`^\f(\w+)(\|(.+))?$`)```
