### ISSUE TITLE
Hope to support Polls Event Listen, Thanks!

### ISSUE THREAD

**Issue by du5** [tucnak/telebot#253]
Docs: https://core.telegram.org/bots/api#january-23-2020

**Comment by demget** [comment]
Implemented, #257. Changes are available in `develop` branch.

**Comment by setval** [comment]
Hello. You can try polls from the [develop](https://github.com/tucnak/telebot/tree/develop#poll) branch

**Comment by du5** [comment]
> Hello. You can try polls from the [develop](https://github.com/tucnak/telebot/tree/develop#poll) branch

Thank you! I will try

**Comment by demget** [comment]
Some new [updates ](https://core.telegram.org/bots/api#april-24-2020) on Polls.

**Comment by demget** [comment]
Polls 2.0 is fully supported and available in `develop` branch for now! https://github.com/tucnak/telebot/commit/9b11223d561c29911398d6372cfd90c9c673487a
