### ISSUE TITLE
InlineButton doesn't work as excepted if some string be used as Unique field

### ISSUE THREAD

**Issue by guest6379** [tucnak/telebot#258]
```golang

package main

import (
	"fmt"
	tb "gopkg.in/tucnak/telebot.v2"
	"time"
)

func foo() {
	fmt.Println("hello")
}

func main() {
	token := "BOT_TOKEN"
	uid := 123456 // UID

	b, err := tb.NewBot(tb.Settings{
		Poller: &tb.LongPoller{Timeout: 10 * time.Second},
		Token:  token,
	})
	if err != nil {
		fmt.Println(err)
		return
	}

	btn1 := tb.InlineButton{
		Unique: "一", // won't work as unique?
		Text:   "Button1",
		Action: func(callback *tb.Callback) {
			foo()
		},
	}

	btn2 := tb.InlineButton{
		Unique: "btn1",
		Text:   "Button2",
		Action: func(callback *tb.Callback) {
			foo()
		},
	}

	inlineKeys := [][]tb.InlineButton{
		[]tb.InlineButton{btn1, btn2},
	}

	menu := tb.ReplyMarkup{
		InlineKeyboard: inlineKeys,
	}

	b.Handle(&btn1, btn1.Action)
	b.Handle(&btn2, btn2.Action)

	b.Send(&tb.User{
		ID: uid,
	},
		"Food Menu:", &menu)

	b.Start()
}

```

when click `btn1`, bot will not respond, the callback `foo()` will not be invoked, but if click `bnt2`, it will print "hello" in the console.

It may not work if the Unique string is:  japanese, korean, chinese and others except english string.

**Comment by demget** [comment]
I recommend you to use only English for `Unique`, without spaces or other characters. Just the one word, that describes your button.

**Comment by guest6379** [comment]
> I recommend you to use only English for `Unique`, without spaces or other characters. Just the one word, that describes your button.

My InlineButton will be created dynamically, and register the callback to bot's handler.
At the begining, I used only english words, like UnixNao and some random characters for `Unique`, but soon I noticed that it will register lots of duplicated callbacks, which may has the same `Action`,  that's why I changed the way of naming `Unique`, and find this issue.

As a workaround, I'm using the MD5 hash string for `Unique`, which will not register the duplicated callback.

Thanks a lot

**Comment by guest6379** [comment]
@demget By the way, it would be great that if you can point out that why this will not work, thanks.

**Comment by demget** [comment]
@guest6379 it is regex, and I think it's not worth it to allow something else except of word characters.

https://github.com/tucnak/telebot/blob/3458aeb2e7be22d99897da4ae9934bc25fa3b47f/bot.go#L149

**Comment by guest6379** [comment]
> @guest6379 it is regex, and I think it's not worth it to allow something else except of word characters.
> 
> https://github.com/tucnak/telebot/blob/3458aeb2e7be22d99897da4ae9934bc25fa3b47f/bot.go#L149

thanks so much for your explanation
