### ISSUE TITLE
After client send me something, my server is fail and it write to log

### ISSUE THREAD

**Issue by truebest** [tucnak/telebot#26]
2015/12/04 07:39:03 failed to get updates: json: cannot unmarshal number into Go value of type string

many
many times

**Comment by tucnak** [comment]
Dunno, it rather seems like Telegram servers provide you malformed json... I still can't say much about it, no details.

**Comment by truebest** [comment]
Ок. I share my source and key. I don't have linux and gdb for debug golang programs. Thank you for understading.

	bot, err := telebot.NewBot("150837607:AAE8zuauo8j9d8hwpQWT7mOjMldwEk5LxHs")
	if err != nil {
		return
	}
	log.Println("Bot has been running")
	messages := make(chan telebot.Message)
	bot.Listen(messages, 1 * time.Second)

it code return that error. When you make new bot and change api key some time it work without problems.

**Comment by tucnak** [comment]
Woooow, I just managed to reproduce it and it's frustrating! Gimme a while.
