### ISSUE TITLE
Proposal: Default ParseMode

### ISSUE THREAD

**Issue by demget** [tucnak/telebot#260]
Helpful feature to make Send and Edit calls clearer.
All you need is define default parse mode before bot initialization.

Possible example:
```go
pref := tb.Settings{
    ParseMode: tb.ModeMarkdown,
    // ...
}

b, err := tb.NewBot(pref)
// handle err

// Sends bold text:
b.Send(user, "*Hello!*") 

// Passing new parse mode overrides default:
b.Send(user, "<b>Hello!</b>", tb.ModeHTML)
```

**Comment by guest6379** [comment]
Add a new filed `ParseMode` to `tb.Settings`? 

I think the default parse mode is `tb.ModeDefault`  is good  to `b.Send(user, "TEXT TO SEND")` 

It depends on how often  plain text/markdown/html the  bot needs to send.
In my option, plain text should be the most often sent stuff :smile: 

In addtion, the telebot user may write a help wrapper for b.send(...) :smile:

**Comment by guest6379** [comment]
It's me again, the max text size which can be sent is 4096, can you implement an offical helper function to send large text into multiple chunks?
It's shoud be more useful than ParseMode,  :sweat_smile: 

thanks.

**Comment by demget** [comment]
> I think the default parse mode is tb.ModeDefault is good to b.Send(user, "TEXT TO SEND")

This proposal solves a problem of repeating code. My bot has 72 HTML-formatted texts. So I had to wirte `tb.ModeHTML` 72 times (but actually a little less). Isn't it better to define global parse mode once before creating bot and make my code clearer?

**Comment by guest6379** [comment]
>  My bot has 72 HTML-formatted texts. So I had to wirte `tb.ModeHTML` 72 times (but actually a little less). Isn't it better to define global parse mode once before creating bot and make my code clearer?

In this case, I agree with you. For telebot users, It may be better than writing helper function , such as `ReplyHtml(...)`, `ReplyMarkdown(...)`, ...  by themselves, let committers take care of the rest :+1: 

thanks.

**Comment by demget** [comment]
https://github.com/tucnak/telebot/commit/98a898f4c7cbcbecb95fdec0cb087b6cd0e15057
