### ISSUE TITLE
Proposal: Command description in Handle

### ISSUE THREAD

**Issue by demget** [tucnak/telebot#261]
Looks really great now, after Bot API 4.7 update and [setMyCommands](https://core.telegram.org/bots/api#setmycommands) method.

```go
pref := tb.Settings{
    SetCommands: true,
    // ...
}

b, err := tb.NewBot(pref)
// handle err

b.Handle("/start", onStart, "Start the bot")
b.Handle("/help", onHelp) // description is optional
```
![изображение](https://user-images.githubusercontent.com/30910794/78549601-4f61bc00-780b-11ea-8602-e82afefbb1ae.png)

**Comment by guest6379** [comment]
Does it mean that we can override the bot's command list without bothering `@BotFather`?

**Comment by demget** [comment]
> Does it mean that we can override the bot's command list without bothering `@BotFather`?

Yes
