### ISSUE TITLE
Is it possible to provide a way of removing bot's handler?

### ISSUE THREAD

**Issue by guest6379** [tucnak/telebot#267]
```golang
func (b *Bot) Handle(endpoint interface{}, handler interface{}) {
	switch end := endpoint.(type) {
	case string:
		b.handlers[end] = handler
	case CallbackEndpoint:
		b.handlers[end.CallbackUnique()] = handler
	default:
		panic("telebot: unsupported endpoint")
	}
}
```
It's easy to register an endpoint to the Handler, but in some cases, we may need to remove the endpoint from the `handlers` map.

For example,
we automatically generates differents `inlinekeyboard` buttons accroding to the results queried from database, along with callback actions,  and we don't need them anymore after the user click them.

But if there are too many users of the bot, the `handlers` map may grow too large, the request is simple, drop the handler when its callback is invoked.
Can you provide some helper methods like: `bot.RemoveHandler(endpoint)` ?

**Comment by demget** [comment]
> we automatically generates differents inlinekeyboard buttons accroding to the results queried from database, along with callback actions, and we don't need them anymore after the user click them.

First off, it's not right to register handlers in runtime, as the `handlers` map is not protected from asynchronous read and writes. Neither of my bots was needed dynamic handling.  And I'd rather keep it as it is, intentionally. So, there is no need for removing as well.
