### ISSUE TITLE
Switch from Webhook to LongPoller

### ISSUE THREAD

**Issue by grkamil** [tucnak/telebot#277]
If you switch from Webhook to LongPoller, you will receive the next message 

> telegram unknown: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first (409)

When you apply webhook, Telebot sends the SetWebhook command itself. Maybe it will be better when you switch from Webhook to LongPoller to call RemoveWebhook automatically too?

**Comment by stek29** [comment]
I'm not sure that removing webhook silently is a good idea.
If such behavior is introduced, it should be enabled with some option.

Also, what if WebHook is added after first remove request? Maybe RemoveWebhook should be executed each time when `can't use getUpdated method while webhook is active` error is returned?

I.e. something like this:

```
if err != nil {
  if err == ErrWebhookConflict {
    b.RemoveWebhook()
  } else {
    b.debug(err)
    b.debug(ErrCouldNotUpdate)
  }
  continue
}
```

I think we should check what other popular libraries are doing, and consider that when choosing what behavior should be default.

**Comment by stek29** [comment]
Also, that error should be added to `errors.go` for sure, and maybe silently logging errors with debug level in `(*LongPoller).Poll` isn't the greatest idea.

**Comment by demget** [comment]
Totally agreed with @stek29, silent behaviour is not always good.
