### ISSUE TITLE
Support for inline-mode

### ISSUE THREAD

**Issue by gloob** [tucnak/telebot#28]
Hi!

First, thanks for this library it really helps me to create a pair of bot telegrams.

Second, are you willing to implement or to accept pull request for support [inline-mode](https://core.telegram.org/bots/api#inline-mode)? As you should noticed Telegram recently added this interesting feature for bots that I think it will fit into telebot.

**Comment by tucnak** [comment]
Omw!

**Comment by gloob** [comment]
Great @tucnak if you need additional help for developing it or a testing platform just tell me. Thanks!
