### ISSUE TITLE
Markdown and HTML not working

### ISSUE THREAD

**Issue by kamushadenes** [tucnak/telebot#282]
Hello folks,

Perhaps I'm just being dumb, but I'm not able to use either HTML or Markdown formatting.

I'm sending like that:

```go
b.Send(USER, fmt.Sprintf("Query Finished in %.2f seconds\n**No results**", duration.Seconds()), &tb.SendOptions{ParseMode: tb.ModeMarkdown})
```

I also tried just specifying `tb.ModeMarkdown` directly instead of putting it inside `tb.SendOptions`.

I'm receiving `**No results**` in plaintext instead of the expected bold. Changing to ```<b>``` and using HTML also doesn't work.

What am I doing wrong?

**Comment by demget** [comment]
Make sure you follow [formatting options](https://core.telegram.org/bots/api#formatting-options) syntax

**Comment by kamushadenes** [comment]
Found the problem(s):

- You must use MarkdownV2
- You must escape dots `\.`
- You must escape dashes `\-`
