### ISSUE TITLE
ReplyTo message within a group

### ISSUE THREAD

**Issue by BrendanThompson** [tucnak/telebot#284]
Hi there,

I am trying to make a bot that will do an action based on a reply. What I mean by this is; when someone says something in a group I reply to that message with a bot command (e.g. `/dosomething`) however, I do not seem to be able to access the properties of that message, merely returns nil. Below is the code I am trying to use currently:

```go
func main() {
	bot, err := t.NewBot(t.Settings{
		Token:  token,
		Poller: &t.LongPoller{Timeout: 10 * time.Second},
	})
	if err != nil {
		log.Fatal(err)
	}
	bot.Handle("/raw", func(m *t.Message) {
		log.Printf("Message Payload: %s", m.Payload)
		log.Printf("Original Message: %s", m.ReplyTo)
	})

	log.Print("starting telegram bot")
	bot.Start()
}
```

Not 100% on where to go from here :)

**Comment by chy168** [comment]
just pass `m` to Reply():
```
	bot.Handle("/raw", func(m *t.Message) {
		bot.Reply(m, "hello world")
	})
```

**Comment by BrendanThompson** [comment]
Hey @chy168 thanks fr the reply, I don't want the bot to do the reply, like the below screen shot I want the command to be done as part of a user replying to another user:
<img width="233" alt="image" src="https://user-images.githubusercontent.com/2595712/81368525-4da15600-9133-11ea-87e9-8d2c9c5ac179.png">

I want to be able to access the ID of the message in which I am replying to as a user.

**Comment by stek29** [comment]
@BrendanThompson is full access enabled for your bot (check with botfather, can access all messages or something like that)?

**Comment by demget** [comment]
@BrendanThompson, have you looked at the ForceReply option?

**Comment by BrendanThompson** [comment]
@demget I have not looked at that, no. Are you able to link to any collateral?

**Comment by demget** [comment]
> 
> 
> @demget I have not looked at that, no. Are you able to link to any collateral?

https://core.telegram.org/bots/api#forcereply

Usage:
```go
b.Send(m.Sender, "Hello!", tb.ForceReply)
// or
b.Send(m.Sender, "Hello!", &tb.ReplyMarkup{
    ForceReply: true,
    Selective:  true,
})
```
