### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by tucnak** [tucnak/telebot#291]
Telebot currently allows global middleware via `MiddlewarePoller`, which is a decent way to implement spam–control, rate–limiting and whatnot. Unfortunately, it lacks capability in the sense there's insufficient granularity to handlers.

This issue explores the idea to have middleware on per-handler basis. There's also case to be made for groups of handlers, and therefore, group middleware.

This is what we are doing at the moment:

```go
bot.Handle("/start", start)
bot.Handle("/hello", hello)
bot.Handle("/help", help)
bot.Handle("/action_1", action)
bot.Handle("/action_2", action)
bot.Handle(tele.OnPhoto, onPhoto)
bot.Handle(tele.OnDocument, onDocument)
```

As you can see, in order to share behaviour, `start`, `hello` and others—must manually implement some shared logic.

```go
//bot.Use(globalMiddleware)

b := bot.Group("")
b.Use(rateLimiter(60)) // will apply to all handlers in the pack
b.Handle("/start", start)
b.Handle("/hello", hello)
b.Handle("/help", hello)

action := b.Group("/action_") // inherits parent's middleware
action.Use(adminOnly)
action.Handle("1", actionOne)
action.Handle("2", actionTwo)

bot.Handle(tele.OnPhoto, onPhoto) // no middleware
bot.Handle(tele.OnDocument, maxFsize(5), onDocument) // on-handle basis
```

You can see that in the code above the nested nature of the middleware. The only question remains: what's the signature of the middleware function and how does it behave? There are handlers for everything: messages, inline queries and inline button callbacks; therefore, there must be middleware for all.

```go
func middlewareFn func(*Update) error

// Example middleware constructor:
func rateLimiting(limit int) middlewareFunc {
	return func(update *Update) error {
		// return true if message is supposed to be passed further
	}
}
```

Cheers,
Ian

**Comment by septs** [comment]
I need use middleware for pre-handle.

auto leave unapproved chat and send unapproved hint message.

**Comment by demget** [comment]
> 
> 
> I need use middleware for pre-handle.
> 
> auto leave unapproved chat and send unapproved hint message.

Middleware functionality is already available in `v3`, but keep in mind the branch is still under development. You can try it in case if you're beginning a new bot.

Usage example:
```go
import tele "gopkg.in/tucnak/telebot.v3"

func main() {
    b, err := tele.NewBot(...)
    if err != nil {
        log.Fatal(err)
    }

    // Global middleware
    b.Use(leaveUnapprovedChats)

    b.Handle("/start", onStart)
    // ...

    b.Start()
}

func leaveUnapprovedChats(next tele.HandlerFunc) tele.HandlerFunc {
    return func(c tele.Context) error {
        approved, err := db.IsChatApproved(c.Chat().ID)
        if err != nil {
            return err
        }

        if !approved {
            return b.Leave(c.Chat())
        }

        return next(c)
    }
}
```

**Comment by septs** [comment]
@demget Why `telebot.Context` not provide `telebot.Bot` reference?

**Comment by demget** [comment]
@septs You can check my extended template https://github.com/demget/telebot-template. It has a special handler package which handles every piece of logic of the bot and includes internationalization and from-configuration loading examples as well. So, there is a handler struct which contains all the external application context such as configs, databases and API clients. I have the bot reference here as well. I stand by this strcture and idea, so there is no need in providing the bot from the tele.Context. But surely, you can create a proposal with your explanations. As I said, the branch's currently developing and we can afford breaking changes. If you also interested in the developing process, I'd happily accept your remarks.

**Comment by septs** [comment]
@demget if you accept, i commit a pull request expose `nativeContext` for `*Bot` reference.

https://github.com/tucnak/telebot/blob/0b46db3041f490dff0ede03b0d609ae9a170529c/context.go#L125-L126

**Comment by demget** [comment]
@septs It makes no sense as the `Context` is interface. For now, just store your bot reference in the global or struct scope, and you'll be able to use it.

**Comment by septs** [comment]
middleware no care of bot instance

as you said:

```go
b.Use(leaveUnapprovedChats)
```

otherwise:

```go
b.Use(makeUserDefinedMiddleware(bot)) // provide a `Bot` instance to middleware
```

**Comment by demget** [comment]
@septs Any way you want, it was just an example

**Comment by septs** [comment]
@demget OK, Suggest to write to FAQ documentation.

**Comment by septs** [comment]
https://github.com/tucnak/telebot/blob/0b46db3041f490dff0ede03b0d609ae9a170529c/middleware.go#L5

i think this is better.
```go
type MiddlewareFunc func(*Bot, HandlerFunc) HandlerFunc
```
