### ISSUE TITLE
Payment.Currency must be of type string not Currency

### ISSUE THREAD

**Issue by EmJiHash** [tucnak/telebot#299]
[`SuccessfulPayment`](https://core.telegram.org/bots/api#successfulpayment) has a field "currency" of type string. But in `Payment` struct `Currency` field is declared as `Currency` type not `string`.
This causes **Error** when a SuccessfulPayment Message is received: 

> json: cannot unmarshal string into Go struct field Payment.Result.message.successful_payment.currency of type telebot.Currency

**Comment by demget** [comment]
#300
