### ISSUE TITLE
How to handle multiple endpoints as one

### ISSUE THREAD

**Issue by Taaanos** [tucnak/telebot#308]
I want to be able to handle the same endpoint for "Abc", "ABC" etc
```go
b.Handle("abc", func(m *tb.Message) {...}
```
I don't use "/abc" but "abc" since I want the bot to respond to keywords. I would like to avoid replicating the same handle for each case.

**Comment by demget** [comment]
Currently, you can not handle multiple endpoints at once. Define your handler function and register it as many as you need, for each endpoint.

```go
func onAbc(m *tb.Message) {
    // ...
}

b.Handle("abc", onAbc)
b.Handle("Abc", onAbc)
b.Handle("ABC", onAbc)
```
