### ISSUE TITLE
type Message does not contain forward_sender_name entry

### ISSUE THREAD

**Issue by D31F43** [tucnak/telebot#309]
Hi,

Recently I am making a bot which has a feature that to reveal the sender’s name of a forwarded message. Since some of the users hide their identity when forwarding the message, so telegram api provides a `forward_sender_name` under Message to specify the name of the hidden original sender.

However, In the latest version 2.3, there is no such entry inside of type Message. So, the entire process is gonna be hacky (I need to get the raw json string to extract the name)

I wonder if you have any plan on this? Or maybe we could make a fast PR.

Thank you

**Comment by demget** [comment]
There are also missed `forward_from_message_id` and `forward_signature`. I'll fix it soon.

**Comment by demget** [comment]
Fixed in [v2.3.1](https://github.com/tucnak/telebot/releases/tag/v2.3.1) release.
