### ISSUE TITLE
Can't get the button response

### ISSUE THREAD

**Issue by jjmengze** [tucnak/telebot#310]
I define Inline button as following below.But user click the btn2 or btn , user can't get any response.
```
menu := &tb.ReplyMarkup{}
btn := menu.Text("⬅")
btn2 := menu.Text("➡")

b.Handle(&btn, func(c *tb.Callback) {
  fmt.Println(c.Text)
})

b.Handle(&btn2, func(c *tb.Callback) {
  b.Respond(c, &tb.CallbackResponse{
			Text: "apple",
  })
})
menu.Inline(menu.Row(btn, btn2))
```

so i trace the workflow ,If any event occurs, the ProcessUpdate function will be triggered.

I simulate user behavior and ambush here,but I can't get any data.
```
func (b *Bot) ProcessUpdate(upd Update) {
	if upd.Message != nil {
```

**Comment by demget** [comment]
Every button you register must have a _unique_—special ID used to recognize your callback.
