### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by aofei** [tucnak/telebot#312]
I found that this project already [supports Go modules](https://github.com/tucnak/telebot/blob/v2/go.mod). But sadly, the [tags](https://github.com/tucnak/telebot/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions. For example, `v2.3` actually becomes `v2.0.0-20200610105239-359b733e3a5b`, you can find it here: https://pkg.go.dev/gopkg.in/tucnak/telebot.v2?tab=versions.

So, I propose this project to follow Semantic Versioning in future versions. For example, `v2.3.1`, `v2.4.0`, `v3.0.0-alpha`, `v3.0.0-beta.2`, `v3.0.0` etc.

**Comment by demget** [comment]
It's a shame we didn't notice this! To be honest, I was hoping that Go mod handles missed minor version, but it's not. All new and previous tags are fixed now and available as separate versions. Thank you for your catch.
