### ISSUE TITLE
User/Sender ID is int

### ISSUE THREAD

**Issue by mousehead** [tucnak/telebot#314]
The number of telegram users is most likely to reach 2^31 in a year or two, and the int type is the 32-bit signed int on 32-bit machines (if someone still uses those). Should we start worrying already?

**Comment by mousehead** [comment]
official API reference: https://core.telegram.org/bots/api#chat

> id  | Unique identifier for this chat. This number may be greater than 32  bits and some programming languages may have difficulty/silent defects  in interpreting it. But it is smaller than 52 bits, so a signed 64 bit  integer or double-precision float type are safe for storing this  identifier.

please consider refactoring to `int64`

**Comment by ItalyPaleAle** [comment]
I second this issue. Looks like Telebot uses `int` types a bit everywhere, including for message IDs.

32-bit machines are fairly common in the ARM world, e.g. Raspberry Pi's.

**Comment by ciricc** [comment]
Really important

**Comment by ofstudio** [comment]
Viable workaround

```go
import (
	"gopkg.in/tucnak/telebot.v2"
	"unsafe"
)

func MustTgUserId64() {
	var u telebot.User
	if unsafe.Sizeof(u.ID) < 8 {
		panic("this application should run only on 64-bit architecture")
	}
}

func init() {
	MustTgUserId64()
}

func main() {
// ...
}

```

**Comment by ItalyPaleAle** [comment]
@ofstudio I wouldn't call that a "workaround" but more like enforcing a requirement. Anyways that's what I've added to my code too. Here's another option that doesn't require the `unsafe` package:

```go
if int64(int(1<<60)) != int64(1<<60) {
	panic("This app should only be executed on a 64-bit system")
}
```

**Comment by demget** [comment]
https://github.com/tucnak/telebot/commit/8f725d434e5137851faa7674214ff8421a5434cd
