### ISSUE TITLE
Bad serialization for Rights

### ISSUE THREAD

**Issue by ghost** [tucnak/telebot#315]
Some bot methods have [`Rights`](https://github.com/tucnak/telebot/blob/b9ba8c453575510d2ad20c4335b4441f36f9f6e4/admin.go#L103-L123) included in their params and using `embedRights` to patch `Rights` to request params. However, in `embedRights`, while `Rights` is a struct of `bool`s, `Rights` is patched to a `map[string]string`, which caused values in the map are set to `""`. Whatever the content in `Rights` is, they become `false` in Telegram's view.

Related code snippets:
https://github.com/tucnak/telebot/blob/b9ba8c453575510d2ad20c4335b4441f36f9f6e4/util.go#L188-L191

See also: <https://play.golang.org/p/lJCE0Zu2v36>

Telegram bot API doc section: <https://core.telegram.org/bots/api#chatmember>

It seems the following bot methods are affected: (in my case, using `Restrict` to unset the restriction of a user to send messages is broken)
```go
/* admin.go */
func (b *Bot) Restrict(chat *Chat, member *ChatMember) error
func (b *Bot) Promote(chat *Chat, member *ChatMember) error
/* util.go */
func (b *Bot) SetGroupPermissions(chat *Chat, perms Rights) error
```

I can open a PR on this. What do you think about changing the type of `p` in `embedRights` from `map[string]string` to `map[string]interface{}`?

**Comment by MiXerek** [comment]
You can change it to whatever you want, just make it work, please ♥️

**Comment by demget** [comment]
[v2.3.3](https://github.com/tucnak/telebot/releases/tag/v2.3.3)
