### ISSUE TITLE
i can't get the simple example to work

### ISSUE THREAD

**Issue by tonymj76** [tucnak/telebot#321]
i keep getting this error
2020/09/07 04:45:04 [verbose] telebot: sent request
Method: getMe
Params: null
Response: {
        "ok": false,
        "error_code": 404,
        "description": "Not Found"
}
2020/09/07 04:45:04 telegram: Not Found (404)
exit status 1
exited: exit status 1

i just copied an past the example code to test it first

**Comment by demget** [comment]
Probably, your token is invalid

**Comment by tonymj76** [comment]
no is not i have verified iti
