### ISSUE TITLE
Add new Hanlder on run time ( after bot has been started)

### ISSUE THREAD

**Issue by yuseferi** [tucnak/telebot#325]
Hi,

does anybody know how can I update ( add or remove, but mostly add) a handler after the bot has been started?
I tried to stop then start the bot again but, but it doesn't help.

**Comment by demget** [comment]
Hi, I highly recommend you to avoid adding handlers in runtime, as it may cause concurrent write and read panics and mess your handling logic. You never define your HTTP routes on the fly, do you? The concept is to specify all possible ways of interacting with the bot, and then here, you may have dynamic context as you need. You make requests to the database or cache to have the current state and, depending on the value, perform further operations you want.

**Comment by yuseferi** [comment]
thanks, @demget for your attention and reply. do you have any sample of this interaction? unfortunately, I haven't found any example of interact but with the user on "telebot".

something like the user can add some items to his/her list. then has N items on database, then if you use choose to delete action, the bot prompts the user to show N buttons to let the user choose which items he/she wants to delete and so on.
I appreciate you if you help me with this.

**Comment by demget** [comment]
It should look close to this

```go
var (
    btnDelete     = &tb.InlineButton{Unique: "delete"}
    btnDeleteItem = &tb.InlineButton{Unique: "delete_item"}
)

func main() {
    // ...

    b.Handle(&btnDelete, onDelete)
    b.Handle(&btnDeleteItem, onDeleteItem)

    b.Start()
}

func onDelete(c *tb.Callback) {

    // 1. Query items by user ID

    items, err := db.ItemsToDelete(msg.Sender.ID)
    if err != nil {
        log.Println("onDelete:", err)
        return
    }

    // 2. Generate a list of buttons

    m := b.NewMarkup()
    for _, item := range items {
        // Passing a button text, its unique and an item ID as callback data
        btn := m.Data(item.Name, btnDeleteItem.Unique, item.ID).Inline()
        m.InlineKeyboard = append(m.InlineKeyboard, []tb.InlineButton{btn}))
    }

    b.Edit(c.Message, "...", m, tb.ModeHTML)
}

func onDeleteItem(c *tb.Callback) {
    itemID := c.Data // we passed it earlier

    if err := db.DeleteItem(itemID); err != nil {
        log.Println("onDeleteItem:", err)
        return
    }

    b.Respond(c, &tb.CallbackResponse{
        Text: "Item successfully deleted!",
    })
}
```

**Comment by demget** [comment]
A lot of things can be done with mere callback logic and its payload. Also, consider trying an alpha v3 of Telebot, as it deals with many boilerplate troubles and simplifies managing the content of the bot. The only omission that there is no documentation for a quick start yet.

**Comment by yuseferi** [comment]
Hi @demget 
thanks a lot for the sample you provide for me. that's great. 
just one error

on 

	btn := m.Data(item.Name, btnDeleteItem.Unique, item.ID).Inline()
	m.InlineKeyboard = append(m.InlineKeyboard, []tb.InlineButton{btn})

I"m receiving 

       cannot use btn (type *telebot.InlineButton) as type telebot.InlineButton in slice literal


I'm using v2, is this happening because of version?
what is your sample version? v3?

**Comment by demget** [comment]
@yuseferi the sample is written in v2. Replace with:
`m.InlineKeyboard = append(m.InlineKeyboard, []tb.InlineButton{*btn})`

**Comment by yuseferi** [comment]
@demget I fixed it. 
another error

`panic: telebot: unsupported endpoint` on     `b.Handle(&btnDelete, onDelete)`

**Comment by yuseferi** [comment]
@demget I guess they should be

var	btnDelete     = &tb.InlineButton{Unique: "off"}
var	btnDeleteItem = &tb.InlineButton{Unique: "off_item"}


?

**Comment by demget** [comment]
@yuseferi Remove `&` from Handle calls

**Comment by yuseferi** [comment]
@demget  this is what I have, it runs with no error, bot nothing happened on "delete" or "/delete" ( even on the terminal ( fmt.println I mean). any thought?

```
package main

import (
	"fmt"
	_ "github.com/mattn/go-sqlite3"
	tb "gopkg.in/tucnak/telebot.v2"
	"time"
)


var	btnDelete     = &tb.InlineButton{Unique: "delete"}
var	btnDeleteItem = &tb.InlineButton{Unique: "delete_item"}

type dataItem struct {
	Name  string
	ID 	  string
}

func main() {

	b, _ := tb.NewBot(tb.Settings{
		// You can also set custom API URL.
		Token:  "MyT_KEN",
		Poller: &tb.LongPoller{Timeout: 10 * time.Second},

	})


	b.Handle(btnDelete, func (c *tb.Callback){

		items := make([]dataItem,0,3)

		items = append(items,dataItem{Name: "test",ID: "3"})
		items = append(items,dataItem{Name: "test1",ID: "4"})

		fmt.Println(items)

		m := b.NewMarkup()
		for _, item := range items {
			// Passing a button text, its unique and an item ID as callback data
			btn := m.Data(item.Name, btnDeleteItem.Unique, item.ID).Inline()
			m.InlineKeyboard = append(m.InlineKeyboard, []tb.InlineButton{*btn})
		}
		fmt.Println(items)

		b.Edit(c.Message, "...", m, tb.ModeHTML)
	})

	b.Handle(btnDeleteItem, func(c *tb.Callback) {
		fmt.Println(c.Data)
		b.Respond(c, &tb.CallbackResponse{
			Text: "Item successfully deleted!",
		})
	})

	b.Start()
}

```

**Comment by demget** [comment]
It's just a snippet of a basic example of how your bot can interact with the user without registering multiple handlers. It won't work from scratch, you have to integrate to your bot by yourself.

As you can see, you're registering the buttons, so you need to have them in the conversation to interact with them...

**Comment by yuseferi** [comment]
@demget you helped a lot. thanks.
