### ISSUE TITLE
Unspecified Telegram errors

### ISSUE THREAD

**Issue by Gowee** [tucnak/telebot#330]
ErrByDescription does not recognize ErrMessageNotModified

Instead, it gets `telegram unknown`:

`telegram unknown: Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message (400)`

The problem appears to be the whole description is used to match a concrete error type, where only the first part `Bad Request: message is not modified` is expected.

https://github.com/tucnak/telebot/blob/bd4747d3ef2f947d988d0f04d34c9ec1958a22cd/util.go#L58

In my case, I want to update previously sent messages and ignore any `ErrMessageNotModified` error while properly propagating other kinds of errors.

telebot version:
`gopkg.in/tucnak/telebot.v2 v2.3.4`

**Comment by demget** [comment]
Actually there're lots of unspecified errors. FloodWait error is got parsed wrongly as well... PR are welcome, I can merge it into `v2`.

Let's collect all missed errors here to add them one day:
1. `Too Many Requests: retry after 1828","parameters":{"retry_after (429)`
2. `Bad Request: message can't be edited (400)`
3. `Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message (400)`

**Comment by demget** [comment]
Fixed for version `v2.3.5`. Feel free to drop other unspecified errors here. The idea is to handle them all.

**Comment by Gowee** [comment]
Another one I just found:
`telegram unknown: Bad Request: chat description is not modified (400)`

**Comment by demget** [comment]
I believe we can find missed errors here:https://github.com/tdlib/telegram-bot-api/blob/master/telegram-bot-api/Client.cpp
So it's possible now to complete the list.

**Comment by demget** [comment]
Most of the useful errors are covered: f0291132d3c33f66eb0dd0db28ef5951925b45d3.
