### ISSUE TITLE
Support error and params

### ISSUE THREAD

**Issue by Hirama** [tucnak/telebot#334]
Telegram returns error `Bad Request: group chat was upgraded to a supergroup chat` with new chat id but bot cuts this info and I can't get a new chat id
```
{
    "ok": false,
    "error_code": 400,
    "description": "Bad Request: group chat was upgraded to a supergroup chat",
    "parameters": {
        "migrate_to_chat_id": -1001432162429
    }
}
```

**Comment by Enrico204** [comment]
I'm having the same issue too. I'm working on a pull request for a workaround.

@tucnak I think that the error checking function is fundamentally broken. The Go JSON parser can be used to detect whether the JSON contains an error or not

**Comment by demget** [comment]
We can catch it similarly to the flood error like here: https://github.com/tucnak/telebot/commit/315d880be7eac113df384902ee6cfda3606146be. But it's getting too cumbersome to handle using regexes, so it'll be great to move to the JSON unmarshaling. PRs are welcome.

**Comment by Enrico204** [comment]
I wrote the #335 for this. However I think that the code needs some major refactoring in that section

**Comment by demget** [comment]
#335 9805b1f622d8161ed5615d0738c8071066ed7dea
