### ISSUE TITLE
Q: forward with reply_to_message as quoted

### ISSUE THREAD

**Issue by suntong** [tucnak/telebot#339]
When I do message forwarding from one group to another, the "reply_to_message" is lost in the forward, which means a very important part of the conversation is missing, viewed from the receiving group.

Is there any easy way to include the "reply_to_message" part in the forwarded message? Else, if I need to add that feature on my own, please give me a hint on how to do it.

thanks!

**Comment by demget** [comment]
You can't as Telegram do not give us such information. `reply_to_message` is for replies only.
