### ISSUE TITLE
Types.go error possible?

### ISSUE THREAD

**Issue by grunmax** [tucnak/telebot#34]
type Video struct {
	Audio // File ???

	Width  int `json:"width"`
	Height int `json:"height"`
.....

**Comment by tucnak** [comment]
Back to first versions of Bots API, `Video` was essentially inheriting all the values from `Audio`. They've introduced a couple more fields recently.

I'll revisit telebot's API and make it up-to-date soon.

**Comment by grunmax** [comment]
Thanks!
