### ISSUE TITLE
enable opt-in for debug mode and stack traces

### ISSUE THREAD

**Issue by mhrivnak** [tucnak/telebot#342]
By default when the poller has an error (such as a reset connection to the telegram API, which seems to happen regularly), it logs two stack traces like this:

```
2020/12/26 10:42:05 Post "https://api.telegram.org/<redacted>": read tcp [<redacted>]:39200->[2001:67c:4e8:f004::9]:443: read: connection reset by peer
telebot
gopkg.in/tucnak/telebot%2ev2.wrapError
	/home/mhrivnak/gopath/src/github.com/mhrivnak/preheatbot/vendor/gopkg.in/tucnak/telebot.v2/util.go:46
gopkg.in/tucnak/telebot%2ev2.(*Bot).Raw
	/home/mhrivnak/gopath/src/github.com/mhrivnak/preheatbot/vendor/gopkg.in/tucnak/telebot.v2/api.go:32
gopkg.in/tucnak/telebot%2ev2.(*Bot).getUpdates
	/home/mhrivnak/gopath/src/github.com/mhrivnak/preheatbot/vendor/gopkg.in/tucnak/telebot.v2/api.go:219
gopkg.in/tucnak/telebot%2ev2.(*LongPoller).Poll
	/home/mhrivnak/gopath/src/github.com/mhrivnak/preheatbot/vendor/gopkg.in/tucnak/telebot.v2/poller.go:100
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
gopkg.in/tucnak/telebot%2ev2.(*Bot).debug
	/home/mhrivnak/gopath/src/github.com/mhrivnak/preheatbot/vendor/gopkg.in/tucnak/telebot.v2/util.go:14
gopkg.in/tucnak/telebot%2ev2.(*LongPoller).Poll
	/home/mhrivnak/gopath/src/github.com/mhrivnak/preheatbot/vendor/gopkg.in/tucnak/telebot.v2/poller.go:102
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
2020/12/26 10:42:05 telebot: could not fetch new updates
gopkg.in/tucnak/telebot%2ev2.init
	/home/mhrivnak/gopath/src/github.com/mhrivnak/preheatbot/vendor/gopkg.in/tucnak/telebot.v2/telebot.go:36
runtime.doInit
	/usr/local/go/src/runtime/proc.go:5625
runtime.doInit
	/usr/local/go/src/runtime/proc.go:5620
runtime.doInit
	/usr/local/go/src/runtime/proc.go:5620
runtime.main
	/usr/local/go/src/runtime/proc.go:191
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
gopkg.in/tucnak/telebot%2ev2.(*Bot).debug
	/home/mhrivnak/gopath/src/github.com/mhrivnak/preheatbot/vendor/gopkg.in/tucnak/telebot.v2/util.go:14
gopkg.in/tucnak/telebot%2ev2.(*LongPoller).Poll
	/home/mhrivnak/gopath/src/github.com/mhrivnak/preheatbot/vendor/gopkg.in/tucnak/telebot.v2/poller.go:103
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
```

The stack trace is not helpful in this case and just makes logs harder to read, so it would be wonderful if there's a way to stop logging the stack trace.

The poller calls the [debug function](https://github.com/tucnak/telebot/blob/0edece47c90fc697ea89edf00f9b7e1330db3d9c/util.go#L13-L20), which always attaches the stack trace. Maybe here it could check for a "debug" setting of some kind rather than always assume it should add the trace.

Making matters worse, the poller [calls debug twice in a row](https://github.com/tucnak/telebot/blob/b51e06e25d0aac728ad6091251402a139ae4d6df/poller.go#L102-L103), which results in two stack traces getting logged. Even if a stack trace were helpful with the first message, it's probably not helpful for the second one.

**Comment by demget** [comment]
I'm thinking how to solve the logging at all in `v3`. We already have `Logger` middleware, possibly there will be the way to pass it to the bot directly, or most likely the bot will use it implicitly on middleware defining. Well both ways have some contradictions...

**Comment by egorsmkv** [comment]
@demget hello, the work on this is still in progress?

**Comment by demget** [comment]
Just did it in https://github.com/tucnak/telebot/commit/73e51e50e67e4e2fd3cf96dd4014e8d7d01b2e95 for `v3`.

**Comment by egorsmkv** [comment]
The logger is in v3 as well?
