### ISSUE TITLE
Handle message deletions

### ISSUE THREAD

**Issue by t3mp14r3** [tucnak/telebot#345]
Hello!

So, i'm looking for a way to handle message deletion, but there are no such thing as `OnDelete`.

Is there a way to do that?

**Comment by rusq** [comment]
Have you tried getting raw updates from the Telegram Bot API?

i.e. curling https://api.telegram.org/bot{{botToken}}/getUpdates

Do you see those updates coming through?

**Comment by rusq** [comment]
Just checked, there's were no updates from the API when the message was deleted.

@demget I suppose this can be closed.
