### ISSUE TITLE
Handle command with image

### ISSUE THREAD

**Issue by rustzz** [tucnak/telebot#346]
I send message `/dem`
Response: "Hello world!"
But when send message `/dem` with image i don't gets response

```golang
package main

import (
	"log"
	"os"
	"time"

	tb "gopkg.in/tucnak/telebot.v2"
)

func main() {
	bot, err := tb.NewBot(tb.Settings{
		Token:  os.Getenv("TGT"),
		Poller: &tb.LongPoller{Timeout: 10 * time.Second},
	})

	if err != nil {
		log.Fatal(err)
		return
	}

	bot.Handle("/dem", func(message *tb.Message) {
		bot.Send(message.Sender, "Hello World!")
	})

	bot.Start()
}
```
![2020-12-31_11-46](https://user-images.githubusercontent.com/74064444/103409279-fc305600-4b5d-11eb-9bf1-c6439c139648.png)

**Comment by rusq** [comment]
That's not exactly how it should work, in the second case you're sending a photo with caption, not a command, so command handler won't be executed.  Have you tried handling "OnPhoto" and check the text/caption for the command (in your case '/dem')?

**Comment by rustzz** [comment]
Now I understand, I'll check it later. I apologize for the long wait for an answer.

**Comment by rusq** [comment]
@rustzz no worries.

Hey @stek29, why thumbs down?  Was my reply invalid?

**Comment by demget** [comment]
In fact, it's possible to implement commands handling inside a caption and maybe is right

**Comment by stek29** [comment]
@rusq because I disagree that photo caption can't have command in it

**Comment by rusq** [comment]
> @rusq because I disagree that photo caption can't have command in it

Thanks Victor, then let me explain, as I may have not conveyed my message properly.

What I meant is that current handler does not process a photo with a command caption as a "command", as `m.Text` of the update that arrives when a user sends the photo with caption is empty, see for youself:
```
(dlv) p m.Text
""
(dlv) p m.Caption
"/dem"
```

 therefore [this condition][1] in `ProcessUpdates` is not satisfied and execution continues up until [this condition][2],  where it's being handled as a [media][3].

This is the sample image I was sending:
![image](https://user-images.githubusercontent.com/16064414/110526537-c9689680-817a-11eb-9091-00791192cb6e.png)

[1]: https://github.com/tucnak/telebot/blob/v2/bot.go#L212
[2]: https://github.com/tucnak/telebot/blob/v2/bot.go#L242
[3]: https://github.com/tucnak/telebot/blob/66cc553e4d2d44a59acda372f52aa7d6d154faf1/bot.go#L471

**Comment by rusq** [comment]
Also, as I stepped on this turf, let me do a bit of a preaching on maintainers behalf.

@stek29, Victor, I'm sure you know this, as I can see that you're participating in a number of projects, but I will reiterate for the context: github is like an online "колхоз" - the people are building their bright future together (or at least they like to believe that they do), therefore - if you feel that current implementation does not implement something that you feel is right, and you strongly believe that this particular way will benefit the wider community, you are most welcome to submit a PR and others will be grateful.  You have a nice day!

**Comment by rustzz** [comment]
Apparently the topic continues with the fact that you plan to do the processing of the command through the caption of image. Should I close the topic?

**Comment by rustzz** [comment]
I think we can close the question
