### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by mateusrmoreira** [tucnak/telebot#351]
I've been looking for this program wiki but I couldn't find it, it would be easier for us who develop using telebot to have a wiki and a group on telegram. I needed help with some features today that weren't on issues here and I found support on telegram-bot-api group. I think it would be fine.

**Comment by demget** [comment]
Hi! We can have a talk here: https://t.me/go_telebot

**Comment by demget** [comment]
Here is it https://github.com/tucnak/telebot/commit/f5ff424b8f2434764e261c88f1996d2d7756abe1. Feel free to ask any question there.
