### ISSUE TITLE
Inline mode from examples not working

### ISSUE THREAD

**Issue by FinecoFinit** [tucnak/telebot#352]
I keep getting "No results" in telegram client. Am I stupid, or is it just not working?

**Comment by FinecoFinit** [comment]
Worked after adding other variables:
```
result := &tb.PhotoResult{
				ResultBase:  tb.ResultBase{},
				URL:         url,
				Width:       0,
				Height:      0,
				Title:       "",
				Description: "",
				Caption:     "",
				ParseMode:   "",
				ThumbURL:    url,
				Cache:       "",
			}
```

**Comment by xzcxzcyy** [comment]
Still not working for me. Any ideas? Some URLs work, while others do not. When sending the photo first to some chat, the same URL works magically.
