### ISSUE TITLE
can I send a keyboard without sending a text along ?

### ISSUE THREAD

**Issue by renathoaz** [tucnak/telebot#354]
Hi there,
I have a handler that sends a inline keyboard calendar

```
func (h handler) calendar(m *tb.Message) {
	today := time.Now()
	cal := calendar.GenerateCalendar(today.Year(), today.Month())
	// on reply button pressed
	if _, err := h.b.Send(m.Sender, "Calendar" /* I don't want to send it*/, cal); err != nil {
		h.l.Error(err)
	}
}

```

if I remove second argument or send empty string, the calendar doesn't show up,
If send nil, it returns` telebot: unsupported what argument`
If send just the cal variable, the calendar doesn't show up.

Sorry about the question but I couldn't get it work without sending a text along with it.
may someone help me on this ?

**Comment by demget** [comment]
You just can't. The message itself must contain text or media, that's why a keyboard is an _Option_.

**Comment by NolPixel** [comment]
> You just can't. The message itself must contain text or media, that's why a keyboard is the _Option_.

dont know why, but other repo like [this](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/docs/examples/keyboard.md). Can sent without any text. Is other way to do that? I cannot even edit and add Keyboard option. Only sent can do that
