### ISSUE TITLE
Question: Why InlineButton.Unique is not the same as Callback.Data

### ISSUE THREAD

**Issue by koteyur** [tucnak/telebot#357]
Hi! I'm figuring out with inline buttons and noticed this weird thing.

What I'm trying to do:
```go
// Message with inline buttons:
inlineKeys := [][]tb.InlineButton{{tb.InlineButton{
	Unique: "foo_btn",
	Text:   "foo",
}, tb.InlineButton{
	Unique: "bar_btn",
	Text:   "btn",
},
}}
msg, _ := bot.Reply(m, "Test message", &tb.ReplyMarkup{InlineKeyboard: inlineKeys})
...
// Handle reply with buttons
func handleMessage(c *tb.Callback) {
	if c.Data != "foo_btn" && c.Data != "bar_btn" {
		log.Fatal("Wrong message!") // This is what I see
		return
	}
	...
}
```

After some investigation I've found that the reason is because of extra `"\f"` character in the begging of Data.
It seems the reason is this line of telebot:
https://github.com/tucnak/telebot/blob/0edece47c90fc697ea89edf00f9b7e1330db3d9c/callbacks.go#L95

So, my question is: Why is this `"\f"` needed? I haven't found about it in telegram docs, but I could miss something...
If it's required, maybe it makes sense to add something like tb.Callback.Unique() method which reverts this modification (removes "\f")?

**Comment by rusq** [comment]
If you step the code in the debugger, you'll discover that "Unique" is used to create a handler for that button, so that when the callback arrives, the related callback function is called.

* Text - displayed on the button
* Unique - used to create a handler for that button
* Data - used to send an arbitrary payload to callback

Therefore, you need to use Data for any stuff you want to use as a payload in the callback handler:

```go
// Message with inline buttons:
inlineKeys := [][]tb.InlineButton{{tb.InlineButton{
	Unique: "foo_btn",
	Text:   "foo",
    Data:   "foo_btn",
}, tb.InlineButton{
	Unique: "bar_btn",
	Text:   "btn",
    Data:   "bar_btn",
},
}}
msg, _ := bot.Reply(m, "Test message", &tb.ReplyMarkup{InlineKeyboard: inlineKeys})
...
// Handle reply with buttons
func handleMessage(c *tb.Callback) {
	if c.Data != "foo_btn" && c.Data != "bar_btn" {
		log.Fatal("Wrong message!") // This is what I see
		return
	}
	...
}
```

**Comment by koteyur** [comment]
Ah, indeed. I missed, that I can set Data for inline button... That's what I needed, thank you!
