### ISSUE TITLE
Question: Missing sendSticker method

### ISSUE THREAD

**Issue by seupedro** [tucnak/telebot#358]
Hi, first of all. Thanks for this library it's awesome! 🚀

I was looking the [stickers.go](https://github.com/tucnak/telebot/blob/v2/stickers.go) file and there is no method [sendSticker](https://core.telegram.org/bots/api#sendsticker). But why not?

**Comment by seupedro** [comment]
Is this the only way to send?

```go
sticker := &tb.Sticker{
    File: tb.File{
	FileID:     "CAACAgIAAxkBAAEErs1gFzM8ZnW5oBobN7euqPnuWSLmrgACTgIAAladvQow_mttgTIDbx4E",
	UniqueID:   "AgADTgIAAladvQo",
    },
    Width:    512,
    Height:   512,
    Animated: true,
  }

 b.Send(chat, sticker, sendOptions)
```

**Comment by demget** [comment]
`Send` is for sendable objects, `Sticker` is sendable. So yes, if you want to send something, the only way is to use `Send`.

**Comment by seupedro** [comment]
But why the sendSticker method is not implemented while the sticker object is?
