### ISSUE TITLE
Scheduled messages

### ISSUE THREAD

**Issue by stromperton** [tucnak/telebot#359]
How I can send [scheduled messages](https://telegram.org/blog/scheduled-reminders-themes#:~:text=Hold%20the%20'Send'%20button%20in,your%20planned%20posts%20into%20reminders.)? I am sorry for my carelessness, if method is on the surface.

**Comment by rusq** [comment]
I'd think that implementing this in this library would be out of scope.

Depending on your needs you could utilise the following:
1. `postTimer := time.NewTicker(<duration>)`
2. https://github.com/robfig/cron

In the first instance, have a goroutine running that receives from `<-postTimer.C` and do the `telebot.Send()` when timer ticks, i.e. every several hours.

In the second instance, using the cron library, you define a function that sends the message with `telebot.Send()`, i.e.
```go
c := cron.New()
c.AddFunc("30 * * * *", func() { telebot.Send(<chat>, "sends this message every 30 min") })
```

Hope that answers your question.

**Comment by demget** [comment]
Or simply:
```go
time.AfterFunc(time.Minute, func() {
  b.Send(m.Sender, "I'm back!")
})
```
