### ISSUE TITLE
Question: Is there an example for handling payments somewhere ?

### ISSUE THREAD

**Issue by alkanna** [tucnak/telebot#362]
I am trying to understand how to proceed after sending an invoice to a user, but the process using this library is not very clear to me.

**Comment by alkanna** [comment]
Found out myself, I needed to do `b.Accept(*PrecheckoutQuery)`

**Comment by Sagleft** [comment]
I join the question. it is completely unclear how to create a payment give some example how to create invoice and send it to user

**Comment by AlexanderMatveev** [comment]
@alkanna, how did you handle PrecheckoutQuery?

**Comment by alkanna** [comment]
It's been a while, but I had to look for it in the source of this lib to
get it to work, sorry I don't really have anything related to this anymore.

**Comment by AlexanderMatveev** [comment]
I just posted my question and found out answer myself, it's just `b.Handle(telebot.OnCheckout,...`

@alkanna thank you for the reply
