### ISSUE TITLE
Callbacks not handled when Unique contains "-"

### ISSUE THREAD

**Issue by rusq** [tucnak/telebot#363]
Consider this sample:
```go
func main() {
	b, _ := tb.NewBot(tb.Settings{...})

	var (
		// Universal markup builders.
		menu     = &ReplyMarkup{ResizeReplyKeyboard: true}
		selector = &ReplyMarkup{}

		// Reply buttons.
		btnHelp     = menu.Text("ℹ Help")
		btnSettings = menu.Text("⚙ Settings")

		// Inline buttons.
		//
		// Pressing it will cause the client to
		// send the bot a callback.
		//
		// Make sure Unique stays unique as per button kind,
		// as it has to be for callback routing to work.
		//
		btnPrev = selector.Data("English", "en-US", ...)
		btnNext = selector.Data("Russian", "ru-RU", ...)
	)

	menu.Reply(
		menu.Row(btnHelp),
		menu.Row(btnSettings),
	)
	selector.Inline(
		selector.Row(btnPrev, btnNext),
	)

	// Command: /start <PAYLOAD>
	b.Handle("/start", func(m *tb.Message) {
		if !m.Private() {
			return
		}

		b.Send(m.Sender, "Hello!", menu)
	})

	// On reply button pressed (message)
	b.Handle(&btnHelp, func(m *tb.Message) {...})

	// On inline button pressed (callback)
	b.Handle(&btnPrev, func(c *tb.Callback) {
		// ...
		// Always respond!
		b.Respond(c, &tb.CallbackResponse{...})
	})

	b.Start()
}
```

The callback will never be called because in `*Bot.ProcessUpdate`, 
```go
			if data[0] == '\f' {
				match := cbackRx.FindAllStringSubmatch(data, -1)
```
cbackRx will not match anything.

Solution is to change
```go
cbackRx = regexp.MustCompile(`^\f(\w+)(\|(.+))?$`)
```
to
```go
cbackRx = regexp.MustCompile(`^\f([-\w]+)(\|(.+))?$`)
```

I'll submit the PR shortly.

**Comment by demget** [comment]
You can use underscore instead. And I also would recommend changing the way you apply uniques. In your example, you have two buttons regarding Russian and English. Knowing that you can combine the logic to handle language switching at once, you're able to pass `language` as unique, and create two buttons with data `en` and `ru` accordingly. Inside the handler, you will have `c.Data` with the language code you specified earlier.

**Comment by rusq** [comment]
@demget thank you for your suggestion!  In my implementation these values are generated from the list that is returned by a third party API, and I worked around it by replacing "-" with "".

My argument in why dashes should work is the following:
1. The update with the correct values arrives, but it's not handled by the library just because it doesn't match the Regexp.
2. UUIDs are unique by definition. What if someone decides to use the UUID (in string form) as a Unique?  Not including dashes in processing sets an artificial boundary to that, making a necessity additional processing (like replacing "-"), making library usage less convenient.

I would like to hear the argument against using dashes in unique, maybe I don't see something obvious?

**Comment by rusq** [comment]
Ended up using this approach:
```go
var hasher = sha1.New

func hash(s string) string {
	h := hasher()
	h.Write([]byte(s))
	return fmt.Sprintf("%x", h.Sum(nil))
}

func (p *Picklist) inlineMarkup(values []string) *tb.ReplyMarkup {
	selector := new(tb.ReplyMarkup)
	var btns []tb.Btn
	for _, label := range values {
		btn := selector.Data(label, hash(label), label)  // unique - hash
		btns = append(btns, btn)
		p.b.Handle(&btn, p.Callback())
	}

	selector.Inline(organizeButtons(selector, btns, p.maxButtons)...)
	return selector
}

```

**Comment by demget** [comment]
Ok, maybe dashes really make sense. Thanks
