### ISSUE TITLE
Forward multi-media messages

### ISSUE THREAD

**Issue by suntong** [tucnak/telebot#367]
https://github.com/tucnak/telebot/blob/0edece47c90fc697ea89edf00f9b7e1330db3d9c/bot_test.go#L170-L175

How to forward multi-media messages like picture, voices, and videos?

I'm [doing](https://github.com/suntong/shuttlebot/blob/cb54f5665e27305905ae9825bd9eaf65e2dcf583/main.go#L94-L103):

	bot.Handle(tb.OnText, app.ForwardHandler)
	bot.Handle(tb.OnAudio, app.ForwardHandler)
	bot.Handle(tb.OnContact, app.ForwardHandler)
	bot.Handle(tb.OnDocument, app.ForwardHandler)
	bot.Handle(tb.OnLocation, app.ForwardHandler)
	bot.Handle(tb.OnPhoto, app.ForwardHandler)
	bot.Handle(tb.OnVenue, app.ForwardHandler)
	bot.Handle(tb.OnVideo, app.ForwardHandler)
	bot.Handle(tb.OnVideoNote, app.ForwardHandler)
	bot.Handle(tb.OnVoice, app.ForwardHandler)

and then,

	app.bot.Forward(chat, message)

But that's not working for me for picture, voices, and videos. How to fix it? Thx!

**Comment by dexter3k** [comment]
Following code:
```golang
b.Handle(tb.OnPhoto, func(m *tb.Message) {
    b.Forward(m.Chat, m)
})
```
works perfectly for me, maybe something is broken inside your ForwardHandler?

UPD: I looked into your code. If normal messages work then maybe problem is with your text length > 2 check? Pictures, voices, videos often have no text attached

**Comment by suntong** [comment]
Oh, indeed! Thanks.
