### ISSUE TITLE
Detect message type within message handler

### ISSUE THREAD

**Issue by suntong** [tucnak/telebot#368]
Is there any way to detect message type within message handler?

As I'm using a universal message handler (see #367), https://pkg.go.dev/github.com/tucnak/telebot#Message alone seems unable to tell me that. And I'd hope to avoid writing individual message handler for each message type, if possible.

**Comment by demget** [comment]
I was thinking about general `OnMessage`callback, PRs are welcome here.

**Comment by suntong** [comment]
> a general OnMessagecallback

Yeah, that's a better idea! 

Can we have it in V3, ***if*** not in V2 pls!

**Comment by suntong** [comment]
> PRs are welcome here

Looking at the fate of previous PRs, @demget, I doubt that mine would be accepted. E.g., what's happening to

https://github.com/tucnak/telebot/pull/335

that seems to be a pretty good one to me.

**Comment by demget** [comment]
Since 10b70148f75fd3383850bc9c2aad3fcd777ed3f1 you can do:

```go
func main() {
  // ...
  b.Handle(tele.OnText, forwardMessage)
  b.Handle(tele.OnMedia, forwardMessage)
  // ...
)

func forwardMessage(c tele.Context) error {
  return c.ForwardTo(r)
}
```
