### ISSUE TITLE
Defining and adding the language_code parameter

### ISSUE THREAD

**Issue by ElectroMyStyle** [tucnak/telebot#372]
Hello, Telegram is currently transmitting the user's **language_code**, are you planning to add this parameter to **Chat** and/or **Sender**? It seems that if the user accesses from the web version, the code is not transmitted during the first command - /start or first message. The bug is already open, I think it will be fixed in the near future.

Perhaps now it is possible to add this field with validation. If the code is given set it to a variable, if not leave an empty string or nil.
This parameter would be a good helper for localization.

![image](https://user-images.githubusercontent.com/5159210/109052711-f9308c80-76ec-11eb-93b0-49709f6c9b90.png)

**Comment by rusq** [comment]
Hello.

I'm not sure whether language is present in the raw API output for Chats (how do you even set it?), but it's already there for User struct, see:

https://github.com/tucnak/telebot/blob/v2.3.5/chat.go#L12

Sometimes it's empty, you need to accomodate for that in the implementation.

**Comment by rusq** [comment]
@demget i hope you don't mind me going through these issues helping you out.

**Comment by ElectroMyStyle** [comment]
It looks like I downloaded the wrong version of the package and I didn't have this field. Now updated and now it is available.

**Comment by ElectroMyStyle** [comment]
I think I'll close it
