### ISSUE TITLE
Support Get and Set value in Context

### ISSUE THREAD

**Issue by lcd1232** [tucnak/telebot#374]
Context interface should have `Get` and `Set` functions for passing values via context.
An example of an interface - https://github.com/labstack/echo/blob/45870c75c3b3fb20edec25cb09dc14ab17df59b9/context.go#L100-L104 

For what? For example, you can create middleware that adds a user to the context:
```go
func User(manager account.Interface) telebot.MiddlewareFunc {
	return func(next telebot.HandlerFunc) telebot.HandlerFunc {
		return func(c telebot.Context) error {
			user, err := manager.GetTelegramUser(context.Background(), int64(c.Sender().ID))
			if err != nil {
				return err
			}
			c.Set("user", user)

			return next(c)
		}
	}
}
```

**Comment by demget** [comment]
Yeah, it is right for the context, but what I was thinking about is the way to somehow allow custom context passing with predefined typed content. So that we can avoid an annoying problem of runtime casting every time we need to use the values.

```go
db := c.Get("db").(*sql.DB)
// possible nil 

db, ok := c.Get("db").(*sql.DB)
if !ok {
  // not ok ??
}

```
instead:
```go
// MyContext implements telebot.Context.
type MyContext struct {
  tele.NativeContext
  db *sql.DB
}

func onStart(c *MyContext) error {
  c.db.AddUser(c.Sender())
}

b.Handle("/start", onStart)
```

Surely, it's impossible now to make it compile-time, but once we have generics in Go, we'll be able to do something like [this](https://go2goplay.golang.org/p/VnVn8HxMdBs).

**Comment by lcd1232** [comment]
For permanent things like DB you can use something like this:
```go
type Handler struct {
	DB   *sql.DB
}

func (h *Handler) Start(c telebot.Context) error {
	if err := c.db.AddUser(c.Sender()); err != nil {
		return errors.WithStack(err)
	}

	return nil
}

b.Handle("/start", h.Start)
```

Using custom context you cannot use `c *MyContext` as an argument because they are different types and you get a compile-time error: `Cannot use 'h.Start' (type func(c *MyContext) error) as type HandlerFunc`

**Comment by demget** [comment]
Right, that's the approach I use right now. But with generics, so with a single context parameter, it'll be much more handsome.

> Using custom context you cannot use c *MyContext as an argument because they are different types and you get a compile-time error

As I mentioned before:
> Surely, it's impossible now to make it compile-time, but once we have generics in Go, we'll be able to do something like [this](https://go2goplay.golang.org/p/VnVn8HxMdBs).

**Comment by lcd1232** [comment]
But what will you do if I wrap your context in middleware?
