### ISSUE TITLE
How can I get Phone number of the user?

### ISSUE THREAD

**Issue by Velnbur** [tucnak/telebot#376]
I need to save a phone number of the sender if one is open. How I can do that?

**Comment by rusq** [comment]
Check [this section of Telegram Bot API](https://core.telegram.org/bots/2-0-intro#locations-and-numbers)

**Comment by TheGolurk** [comment]
```go
		r := &tb.ReplyMarkup{}
		contact := r.Contact("Share phone")
		r.Reply(r.Row(contact))

		Bot.Send(m.Sender, "test", r)

```

> I need to save a phone number of the sender if one is open. How I can do that?
