### ISSUE TITLE
Send message by ID

### ISSUE THREAD

**Issue by D3vl0per** [tucnak/telebot#380]
Maybe it will be a silly question, but how can I send a message by user ID (int)?

**Comment by tucnak** [comment]
It is a silly question, but thank you for asking.

Telebot allows you to construct arbitrary User structs by setting the ID field

```go
// import tele "github.com/tucnak/telebot"
var userID int
u := &tele.User{ID: userID}
tele.Send(u, "Hello world")
```

**Comment by NovikovRoman** [comment]
not working (((
