### ISSUE TITLE
TDD approach

### ISSUE THREAD

**Issue by Pandry** [tucnak/telebot#381]
Hello!
First of all, thanks for this great project.

I was wondering a couple of things:
I'm trying to learn the Test-Driven Development workflow, and I wondered if you have some guidelines on how to write the unit tests.

As a "bonus" question, I also wondered if the framework manages the telegram's limits or not (as far as I saw, it does not).
Note that for limits, I intend:
 - The rate limits
 - The eventual timeouts (When `ok` is false and `parameters.retry_after` indicate how much time to wait before attempting to send a new message
 - The maximum text length of a message

Thanks!

**Comment by demget** [comment]
1. It's impossible to write unit tests at the moment. I can imagine a testing framework that implements a context so you can record the responses and check them afterward, but it won't apply to ordinary bot calls.

2. A rate limiter #487 eventually will be merged.

3. A `FloodError` https://github.com/tucnak/telebot/blob/2f38e4952f73956086bce65260eac75def793ae8/errors.go#L15C2-L15C12 contains the `RetryAfter` field.

4.  The maximum text length of a message is not handled at the moment
