### ISSUE TITLE
Error uploading big files

### ISSUE THREAD

**Issue by suntong** [tucnak/telebot#393]
Telegram now lets you send 2GB files, see
https://tech.hindustantimes.com/tech/news/telegram-now-lets-you-send-2gb-files-trolls-whatsapp-s-16mb-limit-71595828235910.html#:~:text=The%20latest%20update%20has%20now,file%20size%20up%20to%20100MB.

However, when I upload a video file merely 54M, I'm getting:

`Request Entity Too Large`

Why is that and how to fix it?

I'm using `gopkg.in/tucnak/telebot.v2` BTW.

**Comment by demget** [comment]
Bots are still limited to 50MB

**Comment by labulakalia** [comment]
you can use local server api ->> https://github.com/tdlib/telegram-bot-api#usage
```
Download files without a size limit.
Upload files up to 2000 MB.
Upload files using their local path and the file URI scheme.
Use an HTTP URL for the webhook.
Use any local IP address for the webhook.
Use any port for the webhook.
Set max_webhook_connections up to 100000.
Receive the absolute local path as a value of the file_path field without the need to download the file after a getFile request.
```

@suntong

**Comment by suntong** [comment]
Thanks a lot @labulaka521 !

@demget / @tucnak , is it possible to enable such local mode of the Bot API via this telebot project?

thx
