### ISSUE TITLE
Telegram now lets you send 2GB files

### ISSUE THREAD

**Issue by freqmand** [tucnak/telebot#397]
in readme file : 
```
Telegram allows files up to 20 MB in size.
```
Telegram increase the limit to 2GB, is this automatically updated in the library ? means telebot now allows files up to 2GB?
second question : can I send files from 1 channel to another on the fly? or I need to download them from the first channel then upload them to the second ? 
and can I do this if the channel is private?

thanks.

**Comment by demget** [comment]
#393
