### ISSUE TITLE
Support audio and document as Album

### ISSUE THREAD

**Issue by Provissy** [tucnak/telebot#398]
## Description

According to https://core.telegram.org/bots/api#sendmediagroup , telegram accepts four types of `InputMedia`, however, current `bot.SendAlbum` only parses Photo and Video.

When sending audios as album you get `telebot: album entry #0 is not valid`

**Comment by Provissy** [comment]
What is the reason commit https://github.com/tucnak/telebot/commit/206507e3865e9e8cae3e428aaca683d15c64546e being reverted?

Thank you!

**Comment by demget** [comment]
I will return it back soon and retest the behavior again.

**Comment by demget** [comment]
[v2.4](https://github.com/tucnak/telebot/releases/tag/v2.4.0)
