### ISSUE TITLE
Sending a message to a someone's phone number

### ISSUE THREAD

**Issue by elbek** [tucnak/telebot#399]
If I know someone's phone number can I send a message to the phone number? Or it only works for user id (something like @abc)

**Comment by rusq** [comment]
This might answer your question:
https://stackoverflow.com/questions/41686463/how-to-get-user-id-of-a-phone-number-in-telegram

TL;DR
* You can't send a message with the Telegram Bot to a user that has not initiated conversation with your bot.
* You can request the phone number from a user once the user started a conversation, and only then you're able to link the phone number to a user id.
