### ISSUE TITLE
Cannot get image url

### ISSUE THREAD

**Issue by KevinZonda** [tucnak/telebot#400]
![image](https://user-images.githubusercontent.com/33132228/118026091-5afdab80-b358-11eb-8e31-9aa227bbc836.png)

I'm using v2.3.5 and tried to get URL, but it's empty. I tried ro search the document but found nothing.

**Comment by demget** [comment]
There is no public photo URL. You can use `FileByID` function to get the full photo's File structure, or use `Download` to save the file in your local filesystem.

**Comment by KevinZonda** [comment]
Thanks :)
