### ISSUE TITLE
API: support 5.x for v2

### ISSUE THREAD

**Issue by setval** [tucnak/telebot#404]
https://github.com/tucnak/telebot/pull/405
https://github.com/tucnak/telebot/pull/401

**Comment by demget** [comment]
https://github.com/tucnak/telebot/commit/206507e3865e9e8cae3e428aaca683d15c64546e

**Comment by setval** [comment]
https://github.com/tucnak/telebot/pull/407

**Comment by setval** [comment]
https://github.com/tucnak/telebot/pull/408
