### ISSUE TITLE
Consider changing StoredMessage ID's type

### ISSUE THREAD

**Issue by demget** [tucnak/telebot#412]
Personally, I encountered several situations in which more useful would be to have `int` type instead of `string`, and as the original `Message` struct has integer ID, it makes more sense to have the same in `StoredMessage`.

```go
type StoredMessage struct {
  MessageID string `sql:"message_id" json:"message_id"`	
  ChatID    int64  `sql:"chat_id" json:"chat_id"`
}
```

#343 related.

**Comment by AkkiaS7** [comment]
The type of MessageID in StoredMessage still conflicts with the type in the ReadMe document,
should we update the README or reopen the pr #343 ?

https://github.com/tucnak/telebot/blob/7f660b85347625d392a2355014687c069ad07eca/README.md?plain=1#L329-L332

https://github.com/tucnak/telebot/blob/7f660b85347625d392a2355014687c069ad07eca/editable.go#L23-L26

**Comment by prokher** [comment]
Well, there is still contradiction between `README.md` and `editable.go`. Why so?
