### ISSUE TITLE
sendDocument cause stream error PROTOCOL_ERROR

### ISSUE THREAD

**Issue by cheshir** [tucnak/telebot#416]
Hi there!

Sending document randomly leads to error: `telebot: Post "https://api.telegram.org/bot<token>/sendDocument": stream error: stream ID 267; PROTOCOL_ERROR`.

Document format: epub

Size < 10Mb

The same file can be uploaded and failed, I can't understand the logic behind this behaviour.

**Comment by vmintam** [comment]
the same with you. Content is only text but still ERROR.

**Comment by thanhgiangleo** [comment]
same issue. Everything still worked fine until Sep 13. From Sep 14 I can't sendDocument anymore. Don't know what's wrong with that.
