### ISSUE TITLE
Sent Message by Chat ID

### ISSUE THREAD

**Issue by AngelCareaga** [tucnak/telebot#421]
Hello, I am migrating to this library, before I used _tgbotapi_, but the detail of what would be the simile to send a message only with the **chat id** of the user has come up, I leave the example of how it is done in _tgbotapi_.

`msg := tgbotapi.NewMessage(update.Message.Chat.ID, update.Message.Text)`

Thanks :D

**Comment by matinhimself** [comment]
You can do it by creating a new `tb.Chat` struct with specifying its chat id and passing it as `Recipient`  to send functions.
example:
```msg, err := b.Send(&tb.Chat{ID: chatId}, "Message")```

**Comment by demget** [comment]
Or simply `tb.ChatID(...)`.
