### ISSUE TITLE
[Question] how to program a handler interactive?

### ISSUE THREAD

**Issue by rogerBridge** [tucnak/telebot#434]
Dear developer:
    I am a beginner in bot develop, I want to implement a function that could handle user input, for example, user input: "/test", then bot response: "ok, input please", then user input sth, and bot process, at end, exit the command: "/test".
    I have tried:
```go
	b.Handle("/test", func(m *tb.Message) {
		b.Send(m.Sender,"ok, input please")
                b.Handle(OnText, func(m *tb.Message) {
                    output := process(m.Text)
                    b.Send(m.Sender, process(m.Text))
                })
	})
```

this is worked, but after bot response, when I input sth to bot, it always handle input using `process()`, could you tell me how to exit "/test" after process user input? thank you : )

**Comment by rogerBridge** [comment]
Dear developer:
I found a way to answer this question, below is code:
```go
	waitMap := make(map[int]struct{})
	b.Handle(tb.OnText, func(m *tb.Message) {
		if _, ok := waitMap[m.Sender.ID]; ok {
			b.Send(m.Sender, fmt.Sprintf("your input is:%v\n", m.Text))
			delete(waitMap, m.Sender.ID)
		}
	})
	b.Handle("/test", func(m *tb.Message) {
		b.Send(m.Sender, "input your content:")
		waitMap[m.Sender.ID] = struct{}{}
	})
```

**Comment by rusq** [comment]
You may want to add a mutex guard on map operations, otherwise you may get concurrent map writes panic.

**Comment by rogerBridge** [comment]
> You may want to add a mutex guard on map operations, otherwise you may get concurrent map writes panic.

Thank you bro
