### ISSUE TITLE
how to deploy on Vercel

### ISSUE THREAD

**Issue by ghost** [tucnak/telebot#442]
I referenced the code in the example
https://github.com/tucnak/telebot/blob/93c5ba7136a6f82d848be1775db3350b266079f3/examples/awslambdaechobot/main.go#L12-L30
but it didn't work on Vercel.
```
func Handler(w http.ResponseWriter, r *http.Request) {
	b, err := tb.NewBot(tb.Settings{
		Token:       os.Getenv("TELEBOT_SECRET"),
		Synchronous: true,
	})
	if err != nil {
		panic(err)
	}

	b.Handle(tb.OnText, func(m *tb.Message) { b.Send(m.Chat, m.Text) })

	var u tb.Update
	resp, _ := io.ReadAll(r.Body)
	if err = json.Unmarshal(resp, &u); err == nil {
		b.ProcessUpdate(u)
	}
	return
}
```

**Comment by code-withAshish** [comment]
Just to answer you question in short 
I would like to say that vercel only supports web apps as of now which means your code when running needs to be binded to a port to run, and in general telegram bot polling method it's not the case.

I would recommend you using telegram webhooks and using vercel serverless functions, and for that matter a very good article that i found is  [this](https://dev.to/jj/create-a-serverless-telegram-bot-using-go-and-vercel-4fdb)

hope it helps!!!!
