### ISSUE TITLE
Quality of life suggestion for handlers

### ISSUE THREAD

**Issue by graynk** [tucnak/telebot#444]
Hi! I love your library, however either I'm missing something, or there's a fairly easy way to remove some of the boilerplate.
Right now handlers receive only `tb.Message` as the argument. But most of the time you'd want to reply from said handler. If the handler is fairly big - you'd want to separate it into it's own function as well. So this (for me) results into a boilerplate code like this, where I pass the bot to the handler manually:
```Go
b.Handle(tb.OnPhoto, func(m *tb.Message) {
    actualHandler(b, m)
})
```

Wouldn't it be nicer if handlers either received the bot instance as a separate argument, or `tb.Message` kept the bot instance inside of itself, so users could just do `m.Reply(...)` (python-telegram-bot does it this way, for example)?

**Comment by demget** [comment]
**Telebot V3** has context-based handling, which allows you to directly interact with the user as well as to get the original bot instance.

```go
b.Handle("/start", func(c tele.Context) error {
  msg, err := c.Bot().Reply(c.Message(), "Hello!")
  // or simply
  return c.Reply("Hello!")
})

**Comment by graynk** [comment]
Ah, I knew I missed something, thanks!
Is v3 ready for usage? README.MD mentions v2 only

**Comment by demget** [comment]
It hasn't been released yet, but is ready for use, with a minor chance of breaking changes before the full-fledged release. README is also updated.
