### ISSUE TITLE
How to stop a b.Handle and does it run in goroutine?

### ISSUE THREAD

**Issue by gelerum** [tucnak/telebot#448]
Hello, i am writing a bot for save my expenses/income
I have such a function, but i can't stop b.Handle inside it, and function inside b.Handle works forever. How i can stop handler?
```go
func howMuchSpend(b *tb.Bot, m *tb.Message) float64 {
	var amount float64
	b.Send(m.Sender, "How much did you spend?")
	b.Handle(tb.OnText, func(m *tb.Message) {
               // these lines like in loop
		amountTransformed, err := strconv.ParseFloat(m.Text, 64)
		if err != nil {
			b.Send(m.Sender, "Send me amount (example: 100 or 100.2)")
		} else {
			amount = amountTransformed
			return // this return can't stop b.Handle()
		}
	})
	return amount
}
```
There is my full code - [full code](play.golang.org/p/8hqNVXRZLum) . Maybe i use wrong your library. Do you have a good examples of large branch bot?

**Comment by rusq** [comment]
Now, I'm just a passer by, but it looks like you're misusing the Handle.

There's a map of handlers, where telebot keeps all the handlers. It looks like this:  handlers = map[EVENT]func()

When you call `Handle(OnText,func(...) {} )`, it does this ` handlers[OnText] = func(...) {} `.  You **can't** have several different functions on the same event.

What happens is this:
1. In the `main()` you are calling `Handle(OnText, ....)`, that adds this handler to the internal handlers map.
2. The moment you call it the second time, in `howMuchSpend()`, you're overwriting the existing `OnText` handler in with the new one.

If you want your code to work, you need to implement a simple state machine, and branch in OnText depending on the current state (i.e. has user already entered category? has user entered the amount?).

I'm never tired of repeating this simple truth: debugger is your friend.  Step through your code, see what happens.
