### ISSUE TITLE
error with telebot

### ISSUE THREAD

**Issue by tierline1** [tucnak/telebot#458]
i do nothing with my bot, but it started to log errors:

 /usr/local/go/src/runtime/asm_amd64.s:1337
2021/11/09 21:48:44 telegram unknown: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
gopkg.in/tucnak/telebot%2ev2.(*Bot).debug
        /root/go/src/gopkg.in/tucnak/telebot.v2/util.go:14
gopkg.in/tucnak/telebot%2ev2.(*LongPoller).Poll
        /root/go/src/gopkg.in/tucnak/telebot.v2/poller.go:102
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
2021/11/09 21:48:44 telebot: could not fetch new updates
gopkg.in/tucnak/telebot%2ev2.init.ializers
        /root/go/src/gopkg.in/tucnak/telebot.v2/telebot.go:36
runtime.main
        /usr/local/go/src/runtime/proc.go:188
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
gopkg.in/tucnak/telebot%2ev2.(*Bot).debug
        /root/go/src/gopkg.in/tucnak/telebot.v2/util.go:14
gopkg.in/tucnak/telebot%2ev2.(*LongPoller).Poll
        /root/go/src/gopkg.in/tucnak/telebot.v2/poller.go:103
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
2021/11/09 21:48:47 telegram unknown: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
gopkg.in/tucnak/telebot%2ev2.(*Bot).debug
        /root/go/src/gopkg.in/tucnak/telebot.v2/util.go:14
gopkg.in/tucnak/telebot%2ev2.(*LongPoller).Poll
        /root/go/src/gopkg.in/tucnak/telebot.v2/poller.go:102
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
2021/11/09 21:48:47 telebot: could not fetch new updates
gopkg.in/tucnak/telebot%2ev2.init.ializers
        /root/go/src/gopkg.in/tucnak/telebot.v2/telebot.go:36
runtime.main
        /usr/local/go/src/runtime/proc.go:188
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
gopkg.in/tucnak/telebot%2ev2.(*Bot).debug
        /root/go/src/gopkg.in/tucnak/telebot.v2/util.go:14
gopkg.in/tucnak/telebot%2ev2.(*LongPoller).Poll
        /root/go/src/gopkg.in/tucnak/telebot.v2/poller.go:103
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337

**Comment by demget** [comment]
It means you have two simultaneously running instances of your bot.

**Comment by tierline1** [comment]
> It means you have two simultaneously running instances of your bot.

no, i start only one instance and after it i do `PS -aux | grep word` and see only one instance, but it start throwing errors:

tier@ubuntu-2gb-nbg1-1:~/go/src/wordamentbot_new$ ./word
2021/11/10 20:20:36 telegram unknown: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2021/11/10 20:20:39 telegram unknown: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)

**Comment by Manuele99** [comment]
maybe you're starting the bot twice
