### ISSUE TITLE
int64 UserID's break telebot v2

### ISSUE THREAD

**Issue by callebtc** [tucnak/telebot#461]
Hi,
some users have userID's going up to `5005031991`. If any of such a user writes a message anywhere, telebot will get stuck and there is no way of getting it back up. 

`json: cannot unmarshal number 5005031991 into Go struct field User.Result.message.from.id of type int
telebot`

Possible solutions:
* Switch to int64 asap (I see v3 has this, but I'm on v2 still and there are no tags for v3). 
* Increment `LongPoller.LastUpdateID` even in the case of a failed `b.getUpdates`
* Do a manual: `curl <telegram_bot_endpoint>/getUpdates?offset=123456` where `123456` is the message that crashes telebot, will only work until next crash.

**Comment by demget** [comment]
[Telebot V2.5](https://github.com/tucnak/telebot/releases/tag/v2.5.0)
