### ISSUE TITLE
GetUpdates JSON parsing error

### ISSUE THREAD

**Issue by iyear** [tucnak/telebot#466]
ver: 2.4.1

```
telebot: json: cannot unmarshal number 5018594437 into Go struct field User.Result.message.from.id of type int
```

At present, it is because telegram used the ID of int64 before, and telebot has not followed up

**Comment by 499602D2** [comment]
Same error on 2.4.1, first popped up ≈10 hours ago:

`2021/12/08 03:50:40 telebot: json: cannot unmarshal number 5086911197 into Go struct field User.Result.message.from.id of type int`

**Comment by iyear** [comment]
I create a new telebot repo: https://github.com/iyear/telebot-64

it's based on telebot v2.4.1 and simply replace the data type of the User ID to int64

Telegram User ID needs int64, telebot.v2 is still using int

you can temporarily use this library, but this library will not be compatible with tucnak/telebot.v2,so I wouldn't PR for the original repo.

you need to manually handle all User.ID in your project

```shell
go get -u github.com/iyear/telebot-64
```

**Comment by demget** [comment]
[Telebot V2.5](https://github.com/tucnak/telebot/releases/tag/v2.5.0)
