### ISSUE TITLE
int64 user ID causes JSON parse errors on 2.4.1

### ISSUE THREAD

**Issue by 499602D2** [tucnak/telebot#467]
`2021/12/08 03:50:40 telebot: json: cannot unmarshal number 5086911197 into Go struct field User.Result.message.from.id of type int`

**Comment by demget** [comment]
[Telebot V2.5](https://github.com/tucnak/telebot/releases/tag/v2.5.0)

**Comment by khoss** [comment]
Still error in v3
` 2021/12/17 14:42:03 telebot: json: cannot unmarshal number XXXXXXXXXXXX into Go struct field Contact.Result.message.contact.user_id of type int`
