### ISSUE TITLE
regex Handler

### ISSUE THREAD

**Issue by AmarnathCJD** [tucnak/telebot#469]
b.Handle(regexp.MustCompile("\#(\S+)"), rgtest)

gives panic error unsupported handle enpoint.

**Comment by Russia9** [comment]
Hi. You should use `b.Handle(telebot.OnText, ...)`, and match regexp manually. b.Handle currently only [allows](https://github.com/tucnak/telebot/blob/v2/bot.go#L159) you to use string and CallbackEndpoint as a handler.

**Comment by AmarnathCJD** [comment]
Yeah Found MiddleWare + OnText thanks

**Comment by NabiKAZ** [comment]
In my opinion, Regex support can be useful.

We sometimes need to add command in the middle of our texts. That we cannot use the space between the command and the parameter and they must stick together.
For example: `/myCommand_123`

For example something like this in JS:
```js
bot.onText(/\/myCommand_(\d+)/, function(msg, match) {
   callFuction(msg.chat.id , match[1]);
});
```
[ref](https://github.com/yagop/node-telegram-bot-api/issues/406)

![image](https://github.com/tucnak/telebot/assets/246721/81154611-653f-42e3-8d83-e70c756755d5)

Is there no plans to add it?

**Comment by NabiKAZ** [comment]
@AmarnathCJD 
How did you implement Middle Ware?
Can you share the code?
