### ISSUE TITLE
V2: How to remove bot handler

### ISSUE THREAD

**Issue by jjnesbitt** [tucnak/telebot#470]
I have a bot in which I temporarily want to handle a type of message (in my case `OnText`), and upon a certain condition, I want to remove this handler, so that `OnText` doesn't run any function. Currently, I don't see a way to do this, so I've just placed an empty function when that condition is fulfilled. If this does not exist, I think a simple `Unhandle` method would be sufficient.

Also, love the library!

**Comment by demget** [comment]
It's wrong to rely on whether handlers exist or not. You cannot use `Handle` after the bot start simply because it's unprotected for concurrent access. Instead, add a specific check to the start of the `OnText` handler so it will exit when needed before executing a logic.

```go
func onText(c tele.Context) error {
  if !canProcessText(c) {
    return nil
  }
}
```
