### ISSUE TITLE
Add support for socks5 proxy

### ISSUE THREAD

**Issue by amirhossein-ka** [tucnak/telebot#474]
hello! i wanted to ask if it's possible to add socks5 support ? because in my country telegram api is blocked and VPNs doesnt work correctly ):

**Comment by demget** [comment]
You can set your custom `*http.Client` in the `Settings` with the transport and proxy you'd like.

**Comment by jjhesk** [comment]
```

	pref1 := tb.Settings{
		Token:  key,
		Poller: spamProtected,
		Client: &http.Client{
			Transport: &http.Transport{
				Proxy: http.ProxyURL(proxyURL),
			},
		},
	}

	pref2 := tb.Settings{
		Token:  key,
		Poller: spamProtected,
	}
```
