### ISSUE TITLE
The project is not golang style and there are too many `interface {}`

### ISSUE THREAD

**Issue by alsotang** [tucnak/telebot#475]
I read the readme and found some APIs are very flexible such as `Handle` and `Send`. When jumping to the implements, I don't think they are designed fine.

Though the API seems beautiful in a way, it lost the protection of the type system. The type system can't prevent the programmer to call the function with wrong types. All type errors occur at runtime. It makes me feel that I am using a dynamic language but not a statically typed compile language.

A golang project should not sacrifice the beauty of internal(e.g. statically typed) for beauty of the surface.

The type system of golang is straight and simple. It doesn't have function overloading. I think the ideal way is to provide a wrapper that implemented `Sendable` for string.

**Comment by tucnak** [comment]
Your opinion is very important to us.
