### ISSUE TITLE
Document FileReader is nil

### ISSUE THREAD

**Issue by geoirb** [tucnak/telebot#476]
If i send document to my bot, in backend document filereader is nil 

```golang
func(c tele.Context) error {
		document := c.Message().Document 
                ....
}
```
FileURL is empty

I use gopkg.in/tucnak/telebot.v3 

Same problem with gopkg.in/tucnak/telebot.v2

**Comment by Sagleft** [comment]
Same problem

**Comment by setval** [comment]
Hello. FileReader is used only to upload the data files that we have io.Reader from client to server. If you want to download a file, you can use the Download function

https://github.com/tucnak/telebot/blob/3ae6ec85d5509548fa7455b27750f015d6e984d2/bot.go#L1117
