### ISSUE TITLE
Use client with timeout instead of go DefaultClient

### ISSUE THREAD

**Issue by becheran** [tucnak/telebot#478]
Telebot will use the DefaultClient from the golang http lib if no client is explicitly passed.

As many others have already noticed, using the default client in go can be dangerous since no timeout is defined. See for example: https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779

I know that it's up to the user to pass a client to the constructor, though I think it might make sense to either use a client with a timeout in the example readme, or use a custom client as default if non is provided. Such as:

``` go
 &http.Client{
	Timeout: time.Second * 30,
}
```

**Comment by demget** [comment]
I'm thinking what timeout value will be reliable enough. Is there any chance that a particular Bot API request could be executing for more than 10 seconds for example? First endpoint that comes to mind is `getUpdates` potentially can be quite a time-consuming operation.

**Comment by demget** [comment]
https://github.com/tucnak/telebot/commit/2e4664a387fed179efd2eaeca28ac665c0ec71b2

**Comment by becheran** [comment]
Thx for fixing. One minute should be more than enough. But definitely better than no timeouts

**Comment by becheran** [comment]
Thx for fixing. One minute should be more than enough. But definitely better than no timeouts
