### ISSUE TITLE
Video cover is not displayed correctly

### ISSUE THREAD

**Issue by jw-star** [tucnak/telebot#479]
The size and width have been changed according to the regulations，but the video cover displayed is not my own aa.jpg

 The thumbnail should be in JPEG format and less than 200 kB in size. A thumbnail's width and height should not exceed 320. Ignored if the file is not uploaded using multipart/form-data.
```
		v := &tele.Video{
			File:     tele.FromDisk("./aa.mp4"),
			Duration: 23,
			Caption:  "22222222222",
			Thumbnail: &tele.Photo{
				File:   tele.FromDisk("./aa.jpeg"),
				Width:  160,
				Height: 90,
			},
			Streaming: true,
			FileName:  "aa.mp4",
			Width:     1920,
			Height:    1080,
			MIME:      "image/jpeg",
		}
	
		B.Send(&tele.Chat{
			ID: m.Sender().ID,
		}, v, tele.ModeMarkdown)
```

**Comment by demget** [comment]
Probably Telegram decided itself which thumbnail is better. Nothing to do with telebot.
