### ISSUE TITLE
nil pointer dereference when sending video file as Document

### ISSUE THREAD

**Issue by Qusic** [tucnak/telebot#481]
I run into an error of `runtime error: invalid memory address or nil pointer dereference` [here](https://github.com/tucnak/telebot/blob/f0291132d3c33f66eb0dd0db28ef5951925b45d3/sendable.go#L99)

I am sending `Document`, but the file happens to be a mp4 video file, and the `msg` returned from `sendMedia` call now has `msg.Document` being `nil`, and `msg.Video` field gets updated with the `File` instead. I guess we will need some checks like [this](https://github.com/tucnak/telebot/blob/f0291132d3c33f66eb0dd0db28ef5951925b45d3/sendable.go#L151-L162) as well.

**Comment by Berezhnyk** [comment]
The same for me

**Comment by demget** [comment]
The fix is merged but not released yet, you can use the `@latest` version temporarily.

https://github.com/tucnak/telebot/pull/507
