### ISSUE TITLE
More documentation?

### ISSUE THREAD

**Issue by kirillDanshin** [tucnak/telebot#49]
Hi.
I see that you're cheating with documentation to silently pass linters.
Please, fix that doc parts. 
For example look into [that line](https://github.com/tucnak/telebot/blob/master/inline.go#L12).

Thanks.

**Comment by tucnak** [comment]
Yeah, I forget about these from time to time. During active development iterations, lint messages are annoying and `...` is an easy way to make it shut up!

And the whole thing is why Go is cancer, apparently. Unused imports, unused variables, comment-less public members. I don't wanna see these errors/warnings during active development session, I'd rather resolve them all right before the commit.
