### ISSUE TITLE
How to get the chat_id when the update is a new poll

### ISSUE THREAD

**Issue by nicolasassi** [tucnak/telebot#490]
Is there any way we could infer in which chat the poll was created as the update when a new poll is created does not have any indication of that?

**Comment by code-withAshish** [comment]
Everything that we can get is contained in the context object returned in the updates received by the bot and as you mentioned

> when a new poll is created does not have any indication of that?

in that case , no we cannot get the chat id

**Comment by nicolasassi** [comment]
Thanks!
