### ISSUE TITLE
Running both a bot Handler and Send messages from same bot instance?

### ISSUE THREAD

**Issue by msj33** [tucnak/telebot#492]
Hi

I'm trying to have both a Bot handler and want to send messages from Telebot - But I keep getting 
_telegram unknown: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)_

Reason is most likely that I initiate two bots like this.
	`pref := tele.Settings{
		Token:     config.BotConfig.Password,
		Poller:    &tele.LongPoller{Timeout: 10 * time.Second},
		ParseMode: tele.ModeHTML,
	}

	B, err := tele.NewBot(pref)
	if err != nil {
		log.Fatal(err)
		return
	}`
	
One bot is used for sending messages to Group chat, whereas the other is a bot handler for the bot menu.

The latter is iniatiated  with B.Start

How do I initiate only one Bot instance, that handles both the Menu and support sending messages from the bot to Telegram group chat?

Note: I tried initiating a bot in a function of it own - But whenever i try calling the function from outside the function, I end up with a null pointer error message - Maybe i'm doing something wrong.....(still learning Golang here)

**Comment by amirhossein-ka** [comment]
You cant have two bot instances with one bot Token

Can you provide how you add your handlers ?

BTW, You can have more than two handlers like this:
``` golang
// removed error handling
B, _ := tele.NewBot(pref)

B.Handle("/someCommand", handlers.SendMessagHandler)
B.Handle("", handlers.SendMenu) // handler to send keyboard or inline buttons etc
// and more handlers

```

**Comment by asta788** [comment]
print("asta")
