### ISSUE TITLE
Cannot delete some message

### ISSUE THREAD

**Issue by NolPixel** [tucnak/telebot#493]
I create middleware to delete any message, works fine. But not with sticker, GIF, file, photos, videos. Anyway, its on private message.

```
b.Use(func(hf telebot.HandlerFunc) telebot.HandlerFunc {
	return func(ctx telebot.Context) error {
		log.Println(ctx.Delete())

		return hf(ctx)
	}
})
```

**Comment by demget** [comment]
You need to register these media handlers to be able to process them in middleware.

```go
b.Handle(tele.OnMedia, func(c tele.Context) error { return nil })
```
