### ISSUE TITLE
Bot crashes when opening multiple instances

### ISSUE THREAD

**Issue by ghost** [tucnak/telebot#494]
hi, im currently developing a telegram bot with this library, and when i start it from multiple terminals it says the following:

2022/03/13 13:26:12 telegram unknown: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2022/03/13 13:26:15 telegram unknown: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)

some os info:
im running arch linux (64 bit), and my go version is "go version go1.17.7 linux/amd64"

i think this issue happens because of an auto-update feature, is there a way to temporarily disable it?

edit: i thought that for some reason the poller option may be responsible for this, i tried to launch the program without a poller and it says " panic: telebot: can't start without a poller "

**Comment by ImFound** [comment]
Simple, the bot is already running somewhere else. It does not depend on the telebot library, but from telegram apis.
