### ISSUE TITLE
Delete the message if a message includes a certain string or a message starts with a certain string

### ISSUE THREAD

**Issue by jeonghoyeo7** [tucnak/telebot#499]
Hello.

I'm now using this telebot in a group chat room. I need to delete some kind of messages coming up in the chat room, if a message includes some specific string value or starts with the specific string.

In my knowledge, the current version supports that, if the specific string value is exactly the same as the message coming up in the chat room, that message can be deleted by using 
```
b.Handle("delete this?", func(c tele.Context) error {
		time.Sleep(10 * time.Second)
		return c.Delete()
	})
```
In the above example, if someone types exactly "delete this?", then the telebot deletes the message 10 sec later.
This is the case that the text is the exactly the same as what I indicate.

Is there any way to delete the message if if a message includes some specific string value or starts with the specific string?

There are some reasons I want this functionality:
 1) the certain string has many lines.
 2) the certain string includes unicode character that GO does not allow.

If there is no functionality like this, I can contribute to modify telebot codes and make PR.

**Comment by Clashkid155** [comment]
Maybe try
```
b.Handle(tb.OnText, func(c tele.Context) error {
		time.Sleep(10 * time.Second)
		return c.Delete()
	})

```
This should get all messages. Then implement something check for the string like `strings.Contains("team", "i")`.
You can get more info of strings.Contains at [pkg](https://cs.opensource.google/go/go/+/go1.18:src/strings/strings.go;l=61)
