### ISSUE TITLE
Can't handle message of type "any"

### ISSUE THREAD

**Issue by Dominux** [tucnak/telebot#525]
I wanna write one of my handlers to get specific messages from users. But their type may be any! And going through the docs didn't help me at all, it's misserable!

Even tho I decided to go to see how Bot.Handle works, and if there any wildcard implementation out there, but found only [this function](https://github.com/tucnak/telebot/blob/v3/bot.go#L179):

```go
func (b *Bot) Handle(endpoint interface{}, h HandlerFunc, m ...MiddlewareFunc) {
	if len(b.group.middleware) > 0 {
		m = append(b.group.middleware, m...)
	}

	handler := func(c Context) error {
		return applyMiddleware(h, m...)(c)
	}

	switch end := endpoint.(type) {
	case string:
		b.handlers[end] = handler
	case CallbackEndpoint:
		b.handlers[end.CallbackUnique()] = handler
	default:
		panic("telebot: unsupported endpoint")
	}
}
```

As I can see, there's no any way to implement it.

Hope I'm wrong, cause it's really the place where there's the problem of any amateur framework with so bad architecture. The problem is that a framework cuts off some low level functional from a developer by making so high-level abstraction

**Comment by demget** [comment]
Please elaborate on what are you trying to achieve...

**Comment by kmou424** [comment]
You can implement a custom poller to hook any message, then you can do anything with it or send it to default message channel of `telebot`.
```go
func init() {
	hookUpdates()
}

var updatesHookChan = make(chan telebot.Update, botPerf.Updates) // use len of updates channel from your default bot settings

func hookUpdates() {
	go func() {
		for {
			select {
			case update := <-updatesHookChan:
				// hook message, and do anything you want

				// by default, send to telebot default updates then call ProcessUpdate
				// "Bot" is a instance of your telebot
				Bot.Updates <- update
			}
		}
	}()
}

type CustomPoller struct {
	telebot.LongPoller
}

func (c *CustomPoller) Poll(b *telebot.Bot, _ chan telebot.Update, stop chan struct{}) {
	c.LongPoller.Poll(b, updatesHookChan, stop)
}

func NewDefaultCustomPoller() (poller *CustomPoller) {
	poller = &CustomPoller{}
	poller.Timeout = 10 * time.Second
	return
}
```
