### ISSUE TITLE
How to handle reply to bot message?

### ISSUE THREAD

**Issue by avivasyuta** [tucnak/telebot#527]
Hello.

I didn't understand how to handle replies to bot messages.
Could you give an example or point to a place in the documentation?

**Comment by demget** [comment]
```go
b.Handle(tele.OnText, func(c. tele.Context) error {
  if c.Message().IsReply() {
    reply := c.Message().ReplyTo
    // reply is a Message
  }
})
```

Although it makes sense to have `OnReply` handler to catch only the replies. Feel free to create such a PR if you'd like to.

**Comment by avivasyuta** [comment]
Thank you.
