### ISSUE TITLE
Editing Channel Post's Caption

### ISSUE THREAD

**Issue by akshettrj** [tucnak/telebot#529]
Hi, I was trying to use this library to edit the caption of a media when posted in some telegram channel but am not able to find any way to do so

I tried using the `context.EditCaption()` function but it gives an error that:

```context does not contain message```

Even the `context.Edit()` function is not useful in this case.

Is it possible to do so with this library ?

**Comment by ghost** [comment]
how did you solve it?

**Comment by akshettrj** [comment]
https://github.com/tucnak/telebot/blob/v2.5.0/bot.go#L971

**Comment by ghost** [comment]
> https://github.com/tucnak/telebot/blob/v2.5.0/bot.go#L971

~~what should i see there? i've tried `bot.edit(ctx.message(), "edited")`, but it didn't sense.
i think here's no real difference between `edit` and `editcaption`.~~

**[telegram doesn't let bots change someone else's posts](https://stackoverflow.com/questions/41373752/telegram-bot-api-error-when-try-to-edit-message-bad-request-message-not-found#answer-42579242)**, even though admins can do this
