### ISSUE TITLE
Outdated pkg.go.dev documentation

### ISSUE THREAD

**Issue by Duality1k** [tucnak/telebot#530]
The pkg.go.dev documentation for this repository is outdated:
https://pkg.go.dev/gopkg.in/tucnak/telebot.v3

In the 'Overview' section the readme shows the following import:

`tele "gopkg.in/tucnak/telebot.v3"` ( go-pls can't recognize this import )

which should actually be `tele "gopkg.in/telebot.v3"`

**Comment by demget** [comment]
Feel free to create a PR
