### ISSUE TITLE
Cannot create a menu using your docs 

### ISSUE THREAD

**Issue by will-x86** [tucnak/telebot#534]
I cannot for the life of me create a button, or a menu at all from the documents.

			r := b.NewMarkup()
			r.Text("idk")

This doesn't work
Neither do your menu docs

**Comment by Kohinor46** [comment]
read doc:
https://pkg.go.dev/gopkg.in/tucnak/telebot.v3#section-readme:~:text=m%2C%20%22new%20caption%22)-,Keyboards,-Telebot%20supports%20both
