### ISSUE TITLE
Usage without listening to updates?

### ISSUE THREAD

**Issue by freak12techno** [tucnak/telebot#538]
I am writing a Telegram bot to just send messages, without any interactivity. So I don't basically need to listen for any updates.
However, I can't use the same bot in 2 binaries at once, because although I'm not using updates info, if I have two binaries using the same bot, one of then stops working because it starts receiving 409 Conflict responses.
So, is it possible to use telebot to just send messages, basically disabling any updates fetching?

**Comment by demget** [comment]
Yes, don't call `bot.Start()` if you don't want to receive updates.
