### ISSUE TITLE
docs: telebot/layout

### ISSUE THREAD

**Issue by Googlom** [tucnak/telebot#541]
Hello. First of all, thanks for amazing library :)

I'm wondering if there are some how-tos about layout package? As far as I understand this package helps to handle multiple locales
I'm building multilangual bot that replies depending on language that user sets at the start/settings.

**Comment by Googlom** [comment]
Anyway, figured it out myself.
1) You need to create your layout YAML file (can take template from [example.yml](https://github.com/tucnak/telebot/blob/v3/layout/example.yml))
2) Put your localized texts YAML file into locales dir (by default its `./locales`). File name (without extension) must match the locale you return in `LocaleFunc` (see below). Example of texts file:

`en.yml` 
```yaml
greeting: Hello
good_bye: Bye
```
3) Implement your own [LocaleFunc](https://github.com/tucnak/telebot/blob/937288568d60643dc66b8633f4b45fd9ca402820/layout/middleware.go#L9). In short: this function must return string value of a locale name, for example `"en"` or `"ru"` and also your texts file must be named `en.yml` or `ru.yml` 
4) Put it all together:
```go

import (
	tele "gopkg.in/telebot.v3"
	"gopkg.in/telebot.v3/layout"
)

var tgbot *tele.Bot
var lt *layout.Layout

func InitBot(settings tele.Settings) {
	var err error
	tgbot, err = tele.NewBot(settings)
	if err != nil {
		panic(err)
	}

	lt, err = layout.New("layout.yml")
	if err != nil {
		panic(err)
	}

	// Middlewares first argument is 'fallback' locale
	tgbot.Use(lt.Middleware("en", getUserLocale))
}

func getUserLocale(r tele.Recipient) string {
	// your get locale logic
	return "en"
}
```
5) And in your handlers:
```go
func handler(c tele.Context) error {
	tgbot.Send(c.Sender(), lt.Text(c, "greeting"))
	return err
}
```

You can find other methods in [layout/layout.go](https://github.com/tucnak/telebot/blob/937288568d60643dc66b8633f4b45fd9ca402820/layout/layout.go)

**Comment by demget** [comment]
- You can find the basic documentation [here](https://pkg.go.dev/gopkg.in/telebot.v3@v3.0.0/layout)
- And many examples built on the newest telebot [here](https://github.com/handybots)
- Also you can use this [template](https://github.com/massbots/template) for your future bots
