### ISSUE TITLE
gopkg.in: go-telebot/telebot vs. tucnak/telebot

### ISSUE THREAD

**Issue by bikbah** [tucnak/telebot#542]
What's the correct way to import `telebot` package?
`gopkg.in/telebot.v3` resolves to [go-telebot/telebot](https://github.com/go-telebot/telebot) repo.

**Comment by demget** [comment]
The `gopkg.in/telebot.v3` is used for stable releases, but if you need the latest logic from the repo that is not released yet, use `github.com/tucnak/telebot` import path.
