### ISSUE TITLE
facilitating the use of middleware.Whitelist.

### ISSUE THREAD

**Issue by ghost** [tucnak/telebot#551]
To use, you need to pass several id people:
middleware.Whitelist(1, 2, 3, 4)
all due to the fact that the code is written like this:
func Whitelist(chats ...int64) tele.MiddlewareFunc {..}

But in the end it all converts to an array. Because of this, it will not be possible to run normally and pass the id of people to middleware.Whitelist() from another function, which, for example, loads this list of people from another file.

So I ask you to change func Whitelist(chats ...int64) tele.MiddlewareFunc {..} to
func Whitelist(chats []int64) tele.MiddlewareFunc {..}

**Comment by demget** [comment]
```go
admins := []int64{1, 2, 3}
middleware.Whitelist(admins...)
```
