### ISSUE TITLE
bot: add support for the test environment

### ISSUE THREAD

**Issue by demget** [tucnak/telebot#556]
JFYI, tried to use [bot test environment](https://core.telegram.org/bots/webapps#using-bots-in-the-test-environment), it does not work because of the URL construction. Telebot constructs URL as `url := b.URL + "/bot" + b.Token + "/" + method`, but for test server it should be `url := b.URL + "/bot" + b.Token + "/test/" + method` — note the **test** suffix.

_Originally posted by @prokher in https://github.com/tucnak/telebot/issues/508#issuecomment-1104446503_

**Comment by caalberts** [comment]
@demget  I created #558 to add the test environment.
