### ISSUE TITLE
Scheduling messages

### ISSUE THREAD

**Issue by GabriFila** [tucnak/telebot#561]
Hello! Loving this library 😍 

Are built-in scheduled messages available with telebot? The telegram documentation says [here](https://core.telegram.org/api/scheduled-messages) they should be fairly straightforward, is there a way to achieve it? I saw [this issue](https://github.com/tucnak/telebot/issues/359) but it doesn't seem to use the mentioned method.

In case it is not possible at the moment, I would like to try to add it to the library

Thank you!

**Comment by demget** [comment]
Scheduled messages are not built into the Bot API, it's impossible to have them in `telebot`. Implement your own scheduler with desired behavior and use `telebot` for sending messages.

**Comment by GabriFila** [comment]
You are right sorry! I thought that the core API applied also to bots

Thank you
