### ISSUE TITLE
URL Inline button handler doesnt work

### ISSUE THREAD

**Issue by 19thFeb** [tucnak/telebot#562]
Hi, i have problem with handle url button click:

`
        
        m := tb.ReplyMarkup{}
	btnAdvNavigate := m.URL(messageInNavigationButtonAdv, urlOfNavigationButtonAdv)
	b.Handle(&btnAdvNavigate, func(c tb.Context) error { // doesnt calling
		return c.Respond()
	})

	btnAdvNavigateDataUrl := m.Data("123", "123")
	btnAdvNavigateDataUrl.URL = "https://123.ru"
	b.Handle(&btnAdvNavigateDataUrl, func(c tb.Context) error { // doesnt calling
		return c.Respond()
	})

	btnAdvNavigateData := m.Data("123", "123")
	b.Handle(&btnAdvNavigateData, func(c tb.Context) error { // ok, its working
		return c.Respond()
	})

`
after click on URL button callback was not calling

**Comment by roreng** [comment]
> Hi, i have problem with handle url button click:
> 
> `
> 
> ```
>     m := tb.ReplyMarkup{}
> btnAdvNavigate := m.URL(messageInNavigationButtonAdv, urlOfNavigationButtonAdv)
> b.Handle(&btnAdvNavigate, func(c tb.Context) error { // doesnt calling
> 	return c.Respond()
> })
> 
> btnAdvNavigateDataUrl := m.Data("123", "123")
> btnAdvNavigateDataUrl.URL = "https://123.ru"
> b.Handle(&btnAdvNavigateDataUrl, func(c tb.Context) error { // doesnt calling
> 	return c.Respond()
> })
> 
> btnAdvNavigateData := m.Data("123", "123")
> b.Handle(&btnAdvNavigateData, func(c tb.Context) error { // ok, its working
> 	return c.Respond()
> })
> ```
> 
> ` after click on URL button callback was not calling

In the first two cases, you use URL buttons. Telegram does not allow using URL buttons in conjunction with Callback buttons.

This is indicated in the official [API documentation](https://core.telegram.org/bots/api#inlinekeyboardbutton).

> This object represents one button of an inline keyboard. 
> You must use exactly one of the optional fields.

You can have one thing.

**Comment by 19thFeb** [comment]
Oh! Big thanks
