### ISSUE TITLE
[Question] How to ignore previous message when bot is restarted

### ISSUE THREAD

**Issue by Clashkid155** [tucnak/telebot#563]
I want to discard any command sent when the bot wasn't active. I'm assuming this has something to do with polling?

**Comment by demget** [comment]
Try using `b.RemoveWebhook(true)`, it has `drop_pending_updates` option.

**Comment by Clashkid155** [comment]
So I'm guessing it'll be
`b.drop_pending_updates` instead of `b.RemoveWebhook`?

**Edit:** 
Thanks! Seems I didn't read your reply well at first.
