### ISSUE TITLE
How can I handle any user message?

### ISSUE THREAD

**Issue by sorohimm** [tucnak/telebot#564]
I ran into such a problem that when the bot receives a message where there is, for example, both a photo and a text, then none of the endpoints catches this message. How can this problem be solved?

**Comment by demget** [comment]
Give a code example.

**Comment by sorohimm** [comment]
> Give a code example.

In this example, the bot responds correctly to a message with a photo, but the problem is that there is no text in the message that I send along with the photo

`
b.Handle(tele.OnPhoto, func(c tele.Context) error {
	completeMsg := fmt.Sprintf("Reply Example")

	submitter.Inline(
		submitter.Row(btnUserSubmit),
	)

        return c.Send(completeMsg, submitter)
})
`
<img width="619" alt="изображение" src="https://user-images.githubusercontent.com/70841592/198851307-1e2def00-68c7-476d-a386-a0014bb05738.png">

**Comment by demget** [comment]
Media do not have a **text**, check the `Caption` field. You won't be able to simultaneously handle media and text attached to the media. Also, this is a bad UI design to process the command from a media caption, for this reason you don't have a list of commands to choose from when editing the caption. Reconsider your UI/UX.

**Comment by sorohimm** [comment]
Thank you, it helped me
