### ISSUE TITLE
Providing data to to WebApp upon open

### ISSUE THREAD

**Issue by hoos** [tucnak/telebot#575]
Is is possible to provide arbitrary data to a WebApp that is opened using either an inline button or menu button? Ideally I would like my bot to provide a full list of contacts to my WebApp when it is opened in this way. Alternatively once the WebApp is open is could request a list of contacts from the bot if that is possible.

**Comment by demget** [comment]
Yes, it is possible to provide arbitrary data to a WebApp in Telegram, but there are specific ways to do this:

1. **Using Query Parameters**: When you create a `WebApp` object and set its `URL`, you can include query parameters in the URL that the WebApp can read upon loading. For example, you could serialize your list of contacts into a query string and append it to the URL.

    ```go
    webApp := &telebot.WebApp{
        URL: "https://your-webapp-url.com?contacts=" + url.QueryEscape(serializedContacts),
    }
    ```

    In this case, `serializedContacts` would be a string that represents your contacts in a URL-friendly format (like JSON, encoded in Base64, etc.).

2. **WebApp to Bot Communication**: Once the WebApp is open, it can communicate with the bot to request data. This is typically done using the `WebAppData` object, which can be sent to the bot when the user performs certain actions in the WebApp. However, this is more of a way for the WebApp to send data back to the bot, not for the bot to send data to the WebApp.

3. **Fetching Data from the Bot**: If the WebApp needs to fetch data after it has been opened, you would need to implement an API endpoint in your bot's server that the WebApp can call to retrieve the contacts. The WebApp would make a standard web request to this endpoint, and your bot would respond with the list of contacts.

    For security reasons, you should authenticate these requests to ensure that only your WebApp can request sensitive data like contacts.

---

_Answered via getonboardai.com_
