### ISSUE TITLE
How can I make multiple handlers at once?

### ISSUE THREAD

**Issue by dubrovskyself** [tucnak/telebot#576]
how can i make multiple handlers at once? i want to make a dialog between a user and a bot

i want the user to be able to perform authorization in the service in stages, that is:

> Bot: Enter the username.
> User: username
> Bot: Enter the password.
> User: password
> Bot: Authorization completed

how can i do this?

to communicate with the user, i use a Poller:
```
pref := tele.Settings{
   
Token:   cfg.Telegram.TelegramToken,
   
Poller:  &tele.LongPoller{Timeout: 10 * time.Second},
  
 OnError: a.OnBotError,
}

bot, err := tele.NewBot(pref)
```

i have a handler for authorization in some service:
`a.bot.Handle(&btnAuth, func(c tele.Context) error {
}`

**Comment by ergoz** [comment]
You should use something like State Machine and store state in your storage (cache/db/etc.) for each user. I've seen some state machines on golang, you can search them and implement in your code.
