### ISSUE TITLE
Some questions from bot in one session 

### ISSUE THREAD

**Issue by AntonYurchenko** [tucnak/telebot#577]
Hello! I have a next case:
1. Bot asks: *What is you name?*
2. User answers: *Tom*
3. Bot asks: *What is your age?*
4. User answers: 25
5. Bot sends a result of two questions to user: *Tom, 25*

Do you have something like session for implementation this algorithm?

Or I need to implement a session on backend myself?

**Comment by dubrovskyself** [comment]
Is there an answer to this question?
I've also been wondering this question recently

**Comment by coremodmc** [comment]
You can refer to this repository.
https://github.com/gotelebot/session

**Comment by ergoz** [comment]
Same answer like here https://github.com/tucnak/telebot/issues/576#issuecomment-1416298994
