### ISSUE TITLE
Get number of seen in channel

### ISSUE THREAD

**Issue by ahmdrz** [tucnak/telebot#58]
Hi everybody
I have a question !!!
How can I get number of seen in channels ?
Does telegram have any way to read number of seen in channels ?
I use github.com/tucnak/telebot for my telegram bot. special tnx :+1:

**Comment by G07cha** [comment]
Unfortunately, there is no way to see a number of seen messages in the chat.
And as far as I know it's not telebot's lack of functionality, Telegram API itself doesn't expose such properties for bots.
