### ISSUE TITLE
How handle joining to private channel

### ISSUE THREAD

**Issue by alexander-storozhenko** [tucnak/telebot#581]
`  @bot.message_handler(func=lambda message: True, chat_member_join=True)` - not works
`  @bot.message_handler(content_types=['new_chat_members'])` - not works
help pls

**Comment by roreng** [comment]
> ` @bot.message_handler(func=lambda message: True, chat_member_join=True)` - not works ` @bot.message_handler(content_types=['new_chat_members'])` - not works help pls

I think you are using a different framework in a different programming language. This framework written in the GO (Golang). If you need GO code, it can be like this... 

```
b.Handle(tele.OnUserJoined, func(c tele.Context) error {
	if c.Chat().Type != tele.ChatChannelPrivate {
		return nil
	}

	// your code here...
})
```
