### ISSUE TITLE
I cant get text-data from tg WebApp use command sendData

### ISSUE THREAD

**Issue by SanJiSon** [tucnak/telebot#590]
webApp := &tele.WebApp{
		URL: "https://myUrl.com",
	}

	b.Handle("/start", func(c tele.Context) error {
		markup := b.NewMarkup()
		markup.Inline(markup.WebApp("Open", webApp))
		return c.Send("Open this app!", markup)
	})
	
	b.Handle(tele.OnWebApp, func(c tele.Context) error {
		msg := c.Message().WebAppData.Text
		chatID := tele.ChatID(c.Chat().ID)
		_, err := b.Send(chatID, msg)
		return err
	})
	
	.\main.go:37:17: cannot use markup.WebApp("Open", webApp) (value of type telebot.Btn) as telebot.Row value in argument to markup.Inline
	
	pls help me, how i can handel WebAppData from tg.SendData()

**Comment by demget** [comment]
The error message `cannot use markup.WebApp("Open", webApp) (value of type telebot.Btn) as telebot.Row value in argument to markup.Inline` suggests that you are attempting to use a `telebot.Btn` value as a `telebot.Row` value.

To resolve this issue, you can create a new `telebot.Row` and pass it to the `markup.Inline` method like this:

```go
webApp := &tele.WebApp{
	URL: "https://myUrl.com",
}

b.Handle("/start", func(c tele.Context) error {
	markup := b.NewMarkup()
	btn := markup.WebApp("Open", webApp)
	row := markup.Row(btn)
	markup.Inline(row)
	return c.Send("Open this app!", markup)
})
```

_Answer generated by ChatGPT, an AI language model trained on GPT-3.5_
