### ISSUE TITLE
Migrate from v2 to v3

### ISSUE THREAD

**Issue by suntong** [tucnak/telebot#592]
Hi, 

What are the things that need to be changed, if I have a code for/from v2, and need to migrate it to v3? thx

**Comment by roreng** [comment]
> Hi,
> 
> What are the things that need to be changed, if I have a code for/from v2, and need to migrate it to v3? thx

In telebot v3 there are quite a lot of changes. 
You can familiarize yourself with them here: https://github.com/tucnak/telebot/releases/tag/v3.0.0.

**Comment by suntong** [comment]
Ah, thanks, that's good enough (except the layout part, :) ).
