### ISSUE TITLE
A call for Telegram community

### ISSUE THREAD

**Issue by tobyweb3x** [tucnak/telebot#594]
What we have here is a framework, a fully knowledge of codebase that can be dazzling for some of us. We should should have a Telegram community, it would help with the adoption of the framework. Simple framework or library like [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot) and [golang-telegram-bot-api](https://github.com/go-telegram-bot-api/telegram-bot-api) has such community.
If mentaining is an issue, a volunteer to help. Thanks.

**Comment by roreng** [comment]
> What we have here is a framework, a fully knowledge of codebase that can be dazzling for some of us. We should should have a Telegram community, it would help with the adoption of the framework. Simple framework or library like [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot) and [golang-telegram-bot-api](https://github.com/go-telegram-bot-api/telegram-bot-api) has such community. If mentaining is an issue, a volunteer to help. Thanks.

This project has a community in Telegram Messenger. Look at the main page of the project.

**Comment by tobyweb3x** [comment]
Please, if you would help me, I've  checked I can't find it. Thanks.

When you say the Project main page - this git repo? the gopkg?

**Comment by roreng** [comment]
> Please, if you would help me, I've checked I can't find it. Thanks. When you say the Project main page - this git repo? the gopkg?

[README.md](https://github.com/tucnak/telebot#telebot)
[![Discuss on Telegram](https://img.shields.io/badge/telegram-discuss-0088cc.svg)](https://t.me/go_telebot)
