### ISSUE TITLE
WebHook support

### ISSUE THREAD

**Issue by Ronmi** [tucnak/telebot#6]
Is it okay to add support to update message from webhook?
I did some research by adding a new method to type Bot
```go
func (b *Bot) WebHook(url string, subscription chan Message) http.HandlerFunc
```
and seems working fine.

If you think it's acceptable to add such method, I can send a PR for you. Thanks

**Comment by tucnak** [comment]
I don't really think that we do **really** need this and can't think of a good usecase, can you?

**Comment by Ronmi** [comment]
It's impossible to use long polling mode in restricted environment like google app engine.

But you are right. After some refactoring to my code, I found that in webhook mode we need an "API wrapper" not a "bot" instance. So it might be better to create another project forked/rewrote from here to do this.

Thank's for your reply :)

**Comment by tucnak** [comment]
Thaaaat's what I was talking about, alright.
