### ISSUE TITLE
telebot hide forward message

### ISSUE THREAD

**Issue by Ran-Xing** [tucnak/telebot#604]
```code
if msg, err := bot.Forward(&config.SendToGroup, c.Message()); err != nil {
		log.Println("forwardMessage error", err)
		return err
	}
```

I'm trying to use the robot to forward the user's reply message to the group, but I want to hide the user's information, how can I do it

**Comment by Ran-Xing** [comment]
tks,very much😂

**Comment by demget** [comment]
You can simply extract the text and resend it on behalf of the bot.

**Comment by Ran-Xing** [comment]
@demget But I want to be able to forward some buttons together like postcode

i use'd send now

**Comment by awohsen** [comment]
use [copyMessage](https://core.telegram.org/bots/api#copymessage)

**Comment by Ran-Xing** [comment]
@awohsen 

```go
	if msg, err := bot.Copy(GroupID, c.Message()); err != nil {
		log.Println("forwardMessage error", err)
		return err
	} else {
		if _, err := bot.Send(c.Chat(), fmt.Sprintf("[Forward success!](t.me/%s/%d)", msg.Chat.Username, msg.ID), &SendOptions{ParseMode: "markdown"}); err != nil {
			log.Println("replyMessage error", err)
			return err
		}
	}
```

```tg
📃 Create post
Text
Test For PostBot
[change language+https://t.me/setlanguage/classic-zh-cn]
▶️ Ready
Share
```
<img width="230" alt="image" src="https://github.com/tucnak/telebot/assets/73819467/7f2ec0d1-d255-4de0-b233-f8650e9dbeb3">

<img width="344" alt="image" src="https://github.com/tucnak/telebot/assets/73819467/3ae59898-c00f-4512-9243-99d13b43af87">


```log
runtime error: invalid memory address or nil pointer dereference
```

**Comment by Ran-Xing** [comment]
@tucnak help me, tks😂
