### ISSUE TITLE
Dialog Support [New Feature]

### ISSUE THREAD

**Issue by TangMonk** [tucnak/telebot#608]
I found there is bot can send dialog to me:

<img width="648" alt="image" src="https://github.com/tucnak/telebot/assets/3498786/a550aec3-a21b-46ab-86a0-ee4e7cf8e043">

When click inline keyboard, it send me a dialog, is it new in telegram api? Dose telebot support this?

**Comment by roreng** [comment]
> I found there is bot can send dialog to me:
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/3498786/246073512-a550aec3-a21b-46ab-86a0-ee4e7cf8e043.png">
> When click inline keyboard, it send me a dialog, is it new in telegram api? Dose telebot support this?

This is Alert. Only for Callbacks. Example. 
```
// ShowAlert sends a text response for the current callback query.
func (b *Bot) ShowAlert(c tele.Context, text string) error {
    resp := &tele.CallbackResponse{
        Text:      text,
        ShowAlert: true,
    }
 
    return c.Respond(resp)
}
```

**Comment by TangMonk** [comment]
thanks, it is awesome
