### ISSUE TITLE
What is the best way to edit HTML message?

### ISSUE THREAD

**Issue by estw272** [tucnak/telebot#621]
For example, I have a telegram message with a callback button:

```
Hello,\n
Here is some link:\n
<a href="https://x.com">link</a>
```

When the button is pressed, the callback is called,
then (c: tele.Context) 
c.Message().Text has this text:

```
Hello,\n
Here is some link:\n
link
```

and I can get the link itself from Entities.

I need to edit this message by adding some text, for example the result should be:

```
Mr. Jason,
Hello,\n
Here is some link:\n
<a href="https://x.com">link</a>
```

c.Edit("Mr. Jason\n" + c.Message().Text, tele.ParseHTML) obviously doesn't work since there is no link in original Text.
Is there a better way to do the edit, other than manually recomposing and inserting all links from Entities for each edit? Is there a way to get original message in HTML with all elements in place?

**Comment by demget** [comment]
To edit an HTML message in Telegram while preserving the original formatting, you indeed need to reconstruct the message using the entities provided by the Telegram API. Unfortunately, Telegram's Bot API does not provide the original message in a pre-formatted HTML version. You have to manually reconstruct the HTML by using the entities (like links, bold text, etc.) to reapply the formatting.

Here's a general approach you could take:

1. Use the `EntityText` function from `message.go` to extract the text for each entity.
2. Reconstruct the message by concatenating the plain text with the entities' text, wrapping them with the appropriate HTML tags.
3. Use the `Edit` method from `context.go` to send the edited message back.

Remember to handle escaping of HTML characters properly to avoid injection issues. The `html.EscapeString` function is used here to escape any HTML special characters in the text that is not part of an HTML entity.

---
_Answered via getonboardai.com_
