### ISSUE TITLE
about zh-CN

### ISSUE THREAD

**Issue by WendellWater05376s** [tucnak/telebot#626]
b.Handle("/你好", func(c tele.Context) error {
		return c.Send("你好!")
	})

it's not work！

**Comment by AnyCPU** [comment]
cite from https://core.telegram.org/bots/features#commands:
```
Commands must always start with the / symbol and contain up to 32 characters. They can use Latin letters, numbers and underscores, though simple lowercase text is recommended for a cleaner look.
```

@WendellWater05376s 
No **Latin letters**, no luck!
