### ISSUE TITLE
How to use inline keyboards ?

### ISSUE THREAD

**Issue by ahmdrz** [tucnak/telebot#64]
Hi everybody,
How can i use inline keyboards with this library ?
Is it enough that i fill InlineKeyboard in ReplyMarkup ?

**Comment by G07cha** [comment]
Hi @ahmdrz,
There is basic example of using inline keyboard with telebot:

```go
bot.SendMessage(chatId, "Inline keyboard", &telebot.SendOptions{
	ReplyMarkup: telebot.ReplyMarkup{
		InlineKeyboard: [][]telebot.KeyboardButton{
			[]telebot.KeyboardButton{
				telebot.KeyboardButton{
					Text: "Inline button",
					Data: "/callback", // Callback query
				},
			},
		},
	},
})
```

Be aware, callback queries act differently from regular messages. You can also use `InlineQuery` or `URL` instead of `Data`, see [docs](https://godoc.org/github.com/tucnak/telebot#KeyboardButton).

**Comment by ahmdrz** [comment]
@G07cha Thx.
