### ISSUE TITLE
Skipping pending updates using LongPoller

### ISSUE THREAD

**Issue by dani0854** [tucnak/telebot#640]
Sometimes for bots behavior when it doesn't process pending updates since its last `getUpdates` request is desired.

I could find a clean way to do it using `telebot.LongPoller`
It has `LastUpdateID`, but no matter what values it set to, it still processes at least 1 update (minimum at value `-2`, since it passes `-1` to `offset`)

According to bot api docs, the best way to do it, is to request `getUpdates` with `offset=-1`, same as `LastUpdateID=-2`. And ignore the 1st update while long polling.

Can this be achieved in current veriosn of library? If not, then this is a feature request.

**Comment by JK19** [comment]
If I understand correctly you need to discard all updates with a timestamp older than the bot start time.
I solved this using `MiddlewarePoller`
```
...
var startTime = time.now()
...
func main() {
...
// discards updates older than client start time
poller := &tele.MiddlewarePoller {
    Poller: &tele.LongPoller{ Timeout: 10 * time.Second },

    Filter: func(u *tele.Update) bool {
        return u.Message.Time().After(startTime)
    },
}
b, err := tele.NewBot(tele.Settings{
    Token: <token>,
    Poller: poller,
})
...
```
I hope it fits your use case

**Comment by dani0854** [comment]
> If I understand correctly you need to discard all updates with a timestamp older than the bot start time. I solved this using `MiddlewarePoller`
> 
> ```
> ...
> var startTime = time.now()
> ...
> func main() {
> ...
> // discards updates older than client start time
> poller := &tele.MiddlewarePoller {
>     Poller: &tele.LongPoller{ Timeout: 10 * time.Second },
> 
>     Filter: func(u *tele.Update) bool {
>         return u.Message.Time().After(startTime)
>     },
> }
> b, err := tele.NewBot(tele.Settings{
>     Token: <token>,
>     Poller: poller,
> })
> ...
> ```
> 
> I hope it fits your use case

That is actually a neat solution, thanks

**Comment by nullcache** [comment]
> If I understand correctly you need to discard all updates with a timestamp older than the bot start time.如果我理解正确的话，您需要丢弃所有时间戳早于机器人启动时间的更新。 I solved this using `MiddlewarePoller`我使用 `MiddlewarePoller` 解决了这个问题
> 
> ```
> ...
> var startTime = time.now()
> ...
> func main() {
> ...
> // discards updates older than client start time
> poller := &tele.MiddlewarePoller {
>     Poller: &tele.LongPoller{ Timeout: 10 * time.Second },
> 
>     Filter: func(u *tele.Update) bool {
>         return u.Message.Time().After(startTime)
>     },
> }
> b, err := tele.NewBot(tele.Settings{
>     Token: <token>,
>     Poller: poller,
> })
> ...
> ```
> 
> I hope it fits your use case我希望它适合你的用例

Thx, it works.
I think it should be added to readme.

**Comment by nullcache** [comment]
> If I understand correctly you need to discard all updates with a timestamp older than the bot start time.如果我理解正确的话，您需要丢弃所有时间戳早于机器人启动时间的更新。 I solved this using `MiddlewarePoller`我使用 `MiddlewarePoller` 解决了这个问题
> 
> ```
> ...
> var startTime = time.now()
> ...
> func main() {
> ...
> // discards updates older than client start time
> poller := &tele.MiddlewarePoller {
>     Poller: &tele.LongPoller{ Timeout: 10 * time.Second },
> 
>     Filter: func(u *tele.Update) bool {
>         return u.Message.Time().After(startTime)
>     },
> }
> b, err := tele.NewBot(tele.Settings{
>     Token: <token>,
>     Poller: poller,
> })
> ...
> ```
> 
> I hope it fits your use case我希望它适合你的用例

Actually, there should be a nil pointer check before using u.Message.Time(). If there are some missing button click callback updates, the bot will panic.
Here is the fixed code.
```
...
var startTime = time.now()
...
func main() {
...
// discards updates older than client start time
poller := &tele.MiddlewarePoller {
    Poller: &tele.LongPoller{ Timeout: 10 * time.Second },

    Filter: func(u *tele.Update) bool {
        //  nil pointer check
        if u.Message != nil {
            return u.Message.Time().After(startTime)
        }
        return true // let other types pass
    },
}
b, err := tele.NewBot(tele.Settings{
    Token: <token>,
    Poller: poller,
})
...
```
