### ISSUE TITLE
How to check that user blocked and stop bot?

### ISSUE THREAD

**Issue by region23** [tucnak/telebot#649]
How to check that user blocked and stop bot?
Can't found this in docs or code.

**Comment by ae5259** [comment]
You can try sending a message and check if the err is equal to `ErrBlockedByUser`.

```go
msg, err := b.Send(&tele.User{ID: id}, "Hello")

if err != nil {
fmt.Println(err)
}

fmt.Println(err == tele.ErrBlockedByUser)
```

I blocked the bot and tried to send a Message, and in this case, it printed true in console:

![image](https://i.imgur.com/8wDd1oh.png)
