### ISSUE TITLE
Provide example of callbacks

### ISSUE THREAD

**Issue by JJ** [tucnak/telebot#66]
Provide, if possible, an example on how to use callbacks

**Comment by ngopher** [comment]
Hi, Thank you for your very very very awesome implementation.
Please Edit 2 wrong syntax in example and readme. one of them is in Keyboard section and the other is in inlinemode section.
Change 
c.Respond(c,&tb.CallbackResponse{... To Bot.Respond.....
respectfully, Nima Ghoroubi

**Comment by irgendwr** [comment]
The inline section appears correct to me according to the [doc](https://godoc.org/gopkg.in/tucnak/telebot.v2#Bot.Answer).

**Comment by ngopher** [comment]
Thank you so much
