### ISSUE TITLE
UserJoined Event can't be catched with hidden members group

### ISSUE THREAD

**Issue by hlee4real** [tucnak/telebot#668]
Hey, I'm making a bot to count user joined by invite links.

It works well with private groups with members not hidden, but for groups that members are hidden, I can't catch OnUserJoined event.

Any suggestion for that please? Thanks team :)

**Comment by hlee4real** [comment]
I tried to handle user join by OnChatMember as well, but when a new user joined, it doesn't show anything

**Comment by XiaolinLeo** [comment]
> Hey, I'm making a bot to count user joined by invite links.
> 
> It works well with private groups with members not hidden, but for groups that members are hidden, I can't catch OnUserJoined event.
> 
> Any suggestion for that please? Thanks team :)

Hello, I have the same problem as you,for groups that members are hidden, I  also can't catch OnUserJoined event.. How did you solve it?
