### ISSUE TITLE
Gaming platform?

### ISSUE THREAD

**Issue by tucnak** [tucnak/telebot#67]
https://telegram.org/blog/games

God bless the Queen!

**Comment by G07cha** [comment]
I personally think this is awesome.
It exposes 3 API endpoints and 4 objects which are listed [here](https://core.telegram.org/bots/api#games).

**Comment by ohenepee** [comment]
@tucnak Do we have an ETA on this?

**Comment by tucnak** [comment]
Not happening, at least not of v2.0
