### ISSUE TITLE
How to forward a message to a specific topic in other groups. please help me

### ISSUE THREAD

**Issue by x95555** [tucnak/telebot#679]
I tried this, but it didn't work

```
		topic, err := c.Bot().CreateTopic(&tele.Chat{ID: chatID}, &tele.Topic{Name: "OrderNum"})
		_, err = c.Bot().Forward(&tele.Chat{ID:chatID}, c.Message())
```

**Comment by ghost** [comment]
@x95555 This is not implemented at the telegram API level. You can neither copy nor forward a message from a super chat (chat with topics)

**Comment by x95555** [comment]
Thank you. Maybe I didn't express it clearly. What I need is to forward the message to a fixed topic in a group, not to forward the topic message.

**Comment by ghost** [comment]
> Thank you. Maybe I didn't express it clearly. What I need is to forward the message to a fixed topic in a group, not to forward the topic message.

So just specify message_thread_id (ThreadId in the structure) and that's it. The theme ID can be found in the web version

**Comment by x95555** [comment]
> > Thank you. Maybe I didn't express it clearly. What I need is to forward the message to a fixed topic in a group, not to forward the topic message.
> 
> 
> 
> So just specify message_thread_id (ThreadId in the structure) and that's it. The theme ID can be found in the web version

Yes. I checked the update, and there is this field in json, but it was not parsed into the structure, which caused the error. I customized it and solved it.
