### ISSUE TITLE
when i use img html tag, telegram: Bad Request: can't parse entities: Unsupported start tag "img" at byte offset 1 (400)

### ISSUE THREAD

**Issue by cocoyes** [tucnak/telebot#688]
telegram: Bad Request: can't parse entities: Unsupported start tag "img" at byte offset 1 (400)
 
 var TgGamePlay = `
<img src="https://xxx.xxxxxxxxx.ai/static/image/20240531-155925.jpg"/>
- xxxI .ai is an interactive game platform
`

**Comment by cocoyes** [comment]
c.Send(common.TgGamePlay, tele.ModeHTML)

**Comment by demget** [comment]
`img` is not supported by Telegram Bot API
