### ISSUE TITLE
does bot.Start work?

### ISSUE THREAD

**Issue by mpirbay** [tucnak/telebot#70]
The inline example provided does not work although it does not crash. It just is silentt!
Also, I cannot get bot.Start to work, as if it were in an infinite loop

**Comment by tucnak** [comment]
Do you care to elaborate? `Bot.Start()` does work for me.

**Comment by mpirbay** [comment]
Sorry for coming back late.
First of all the inline example crashes as it is because of the sequence:
`    go messages(bot)
    go queries(bot)
    bot.Start(1 * time.Second)`

I had to put the line ` bot.Start(1 * time.Second)` before the call to messages and queries.

Then, after that change, simply nothing happens.
I tried the code on a mac and on a win7 machine. same behaviour in both cases.

I also tried to use bot.Start () in other programs but it has always the same behaviour: it simply never returns anything

**Comment by tucnak** [comment]
Alright, let's see what's going on. First of all, can you provide your full code please? I just tried the inline example in the initial order and it works just fine here.

Can you please provide the stack trace of the crash you're talking about?

**Comment by mpirbay** [comment]
the code I am using is an exact copy of the inline example with of course a valid token and the line log.Fatalln(err) commented out.
here is what I get:

> panic: runtime error: invalid memory address or nil pointer derefere
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x40119c]
goroutine 1 [running]:
panic(0x5ed900, 0x12500030)
C:/Go/src/runtime/panic.go:500 +0x331
main.main()
C:/Users/mp/Dropbox/GoProgs/src/inline/inline.go:16 +0x15c

line 16 in the code is:  bot.Messages = make(chan telebot.Message, 100)

**Comment by tucnak** [comment]
>First of all the inline example crashes as it is because of the sequence:

Can you provide a stack trace please?

**Comment by mpirbay** [comment]
I am sincerely embarrassed, but I cannot reproduce the crash. I have the same behaviour whether I put the line bot.Start(1 * time.Second) before or after the call to messages(bot).
I apologize for the confusion.
However, as stated previously, when I execute the inline example, I have no response. Can you please tell me what I should expect?

**Comment by tucnak** [comment]
Well, you definitely shouldn't do `bot.Start` in the last place. It blocks on polling internally. Can you please add some debug prints and see whether it gets stuck on `bot.Start` precisely. If it is `bot.Start` indeed, as it seems to me, you might be running in some networking issues or whatever.

And please make sure the bot you testing is the one you put in `BOT_TOKEN`.

**Comment by tucnak** [comment]
Closing for the time being.
