### ISSUE TITLE
Have 'Validating data received via the Mini App' ?

### ISSUE THREAD

**Issue by gif-gif** [tucnak/telebot#717]
[https://core.telegram.org/bots/webapps#validating-data-received-via-the-web-app](url)
<img width="839" alt="image" src="https://github.com/user-attachments/assets/694e2f8a-3873-42f3-80fc-5bf8cf9baffd">

any func for ValidateWebAppQuery ? thks

**Comment by mario027044** [comment]
I didn't find any func too

**Comment by gif-gif** [comment]
> I didn't find any func too

https://github.com/PaulSonOfLars/gotgbot/blob/v2/ext/queryvalidation.go
