### ISSUE TITLE
Unable to retrieve user profile photos using ProfilePhotosOf method

### ISSUE THREAD

**Issue by nk-bm** [tucnak/telebot#755]
I am trying to retrieve a user’s profile photo using the Telebot library, but the [**ProfilePhotosOf**](https://github.com/tucnak/telebot/blob/v4/bot.go#L1124) method always returns an empty array. I’ve tried different approaches, but the result remains the same:

1. WebApp InitData - returns empty photo_url.
2. ProfilePhotosOf method - always returns an empty array, regardless of the account. The user has set profile photo visibility to public, and their profile photo displays correctly in other bots. 

**Code Example:**
```
const BotToken = "YOUR_TOKEN"
const UserID int64 = 0    // telegram users id

func Example_GetUsersProfilePhotos() {
    pref := telebot.Settings{
        Token:  BotToken,
        Poller: &telebot.LongPoller{Timeout: 10 * time.Second},
    }
    bot, err := telebot.NewBot(pref)
    if err != nil {
        fmt.Println(err)
    }

    user := telebot.User{ID: int64(UserID)}
    photos, err := bot.ProfilePhotosOf(&user)
    if err != nil {
        fmt.Println("Error retrieving photos")
        return
    }

    fmt.Println(photos) // always returns an empty array
}
```

**Question:**

Why does the ProfilePhotosOf method always return an empty array? Am I missing something in the settings or initialization? Any advice or ideas on how to solve this issue would be appreciated.

**Comment by BelovN** [comment]
@nk-bm
More information is needed
What version did you try?
I've checked your code on v3.3.6, and everything works fine.
Does your bot recognize your user? If not, you'll get a 404 from the Telegram API.

**Comment by nk-bm** [comment]
@BelovN All good! Telegram has supported it since Bot API 8.0 (https://core.telegram.org/bots/api#november-17-2024). Released on November 17, 2024
![image](https://github.com/user-attachments/assets/0b55f536-2d94-48d2-8656-4e92730b829c)
