### ISSUE TITLE
"telebot: result is True"

### ISSUE THREAD

**Issue by ofstudio** [tucnak/telebot#758]
Success edit an `InlineResult` message always returns error `ErrTrueResult`

```go

if _, err := c.Edit(c.InlineResult(), "foo bar"); err != nil {
    fmt.Println(err)
}
```
Output: `telebot: result is True`

What the purpose for `ErrTrueResult`?

gopkg.in/telebot.v4 v4.0.0-beta.4
go 1.23

**Comment by andriibeee** [comment]
telebot has ergonomic error flow handling, see how callbacks for new message must yield an error, i suppose the ErrTrueResult thing was made to distinguish successful response from nil without needing to return (error err, ok bool)-like tuple from handlers
