### ISSUE TITLE
gopkg.in

### ISSUE THREAD

**Issue by zoni** [tucnak/telebot#78]
With the master branch having recently received (potentially?) backwards-incompatible changes, it might be a good idea to adopt a good tagging strategy and link to [gopkg.in](http://labix.org/gopkg.in) (like http://gopkg.in/tucnak/telebot.v1) in the README.

I personally use [govendor](https://github.com/kardianos/govendor) so it doesn't affect me as much, but not everyone does so it may be beneficial, especially to people more new to go.

**Comment by tucnak** [comment]
I plan on merging #79, which does introduce some super braking changes real soon, how do you think we should handle it?

P.S. I can say I'm finally back to coding and I intent to maintain telebot properly from now on. I'm fairly sure I can trust you at this point, so let me know if you'd like to join the maintainer team. Cheers.

**Comment by zoni** [comment]
> I plan on merging #79, which does introduce some super braking changes real soon, how do you think we should handle it?

I'm a bit short on time right now to come up with a very solid approach, but here's some suggestions which come to mind in semi-structured order:

1. I would probably start a `v2`/`next` branch in which to iterate on the next version of the API, with these breaking changes. This will allow some forward progress and iteration without breaking all current bots at this moment in time.
2. Perhaps point to the v2 in the README file, inviting people to check it out and weigh in if they want their voices heard before it becomes the next official version.
3. Once satisfied with the new API design, we can merge that branch into master. I would consider tagging as v1.0 just before that and tagging this new API as v2.0.
4. Any significant new functionality could bump the version number from v2.0 to v2.1, v2.2, etc. unless it again introduces breaking changes, in which case it would go to v3.0. You could go full [semver](http://semver.org/) but I don't think the size of this project warrants it right now.
5. Not everyone uses it, but I personally think [gopkg.in](http://labix.org/gopkg.in) makes for nice import paths and avoids unexpectedly breaking people's code if they don't vendor their dependencies. With the above version scheme in place, it can be used, and I'd recommend advertising the `gopkg.in/` import paths in the README/examples instead of the `github.com/` ones.
6. More importantly however, I think that, with any non-backward compatible change, a changelog/migration section should be supplied (either in the README or as a separate document), briefly explaining the change and providing an example of what people should do to upgrade to the new version. In my experience, it takes a little bit of work providing this documentation, but providing this makes upgrading a lot simpler for end users, which helps avoid alienating them because their code suddenly broke.

> P.S. I can say I'm finally back to coding and I intent to maintain telebot properly from now on. I'm fairly sure I can trust you at this point, so let me know if you'd like to join the maintainer team. Cheers.

Awesome! :)

I'd be happy to join the maintainer team, with the understanding that maintaining [errbot](http://www.errbot.io/en/latest/) takes a lot of my time already as well, so I definitely won't always be able to respond to all issues that come up. :)
