### ISSUE TITLE
Failed to get updates: Terminated by Long Poll or Webhook

### ISSUE THREAD

**Issue by bharat72007** [tucnak/telebot#81]
While executing the program, I'm getting  
failed to get updates: telebot: Conflict: terminated by other long poll or web hook

The code which I used is same which is being used in the readme document.
Something like as mentioned below:
```
telebottoken := os.Getenv("TELEBOT_TOKEN")
	bot, err := telebot.NewBot(telebottoken)

	if err != nil {
		fmt.Print(err)
		return
	}

	bot.Messages = make(chan telebot.Message, 100)
	pluginframework.Bot = bot
	go HandleMessages(bot)
	bot.Start(1 * time.Second)

```

**Comment by zoni** [comment]
Make sure you aren't accidentally starting two bots simultaneously. When one bot is connected to the long-polling endpoint and another bot connects as well, the first instance is disconnected with the error message you describe.

**Comment by bharat72007** [comment]
Since I'm new to Telegram,  I would like to know is there a way to restart Bot? This situation arise (as I was re running the bot after making code changes). Are there any life cycle method to stop/restart cleanly in telebot. How we can do that through code ? Is there any better way to achieve the same?

**Comment by tucnak** [comment]
No there's no way to hot start/stop Telegram bot from the code at the time. I'd be happy to implement such functionality if only you could provide some viable use cases.

I'm closing the issue for now.
