### ISSUE TITLE
Does Telebot support Webhooks?

### ISSUE THREAD

**Issue by LightVolk** [tucnak/telebot#82]
I see,that  bot shoud listen telegramm per time,but as i understand it uses cpu (simple while loop).
Does Telebot support Webhooks?

**Comment by tucnak** [comment]
Telebot uses long polling with provided poll timeout interval (see `Bot.Start` or `Bot.Listen`). It is not supposed to use much CPU.

I fail to see any benefit in implementing Webhooks at this point or later.

**Comment by zoni** [comment]
> I fail to see any benefit in implementing Webhooks at this point or later.

I think it may be interesting to keep the possibility of adding such support in the future open. Primarily, I see two advantages of incoming webhooks over the outgoing long-polling alternative:

1. **Load balancing & high availability**: Long polling only supports a single active instance. A second connection immediately disconnects the first (which, with the current implementation, will immediately reconnect, disconnecting the other, creating a connect/disconnect storm). This makes running a reduntant instance technically challenging.

	With webhooks, the above becomes a lot easier to do. You just run your bot across two or more servers and stick a loadbalancer in front of them. Assuming a properly configured loadbalancer, instances may come and go without users noticing.

	It is unlikely hobby projects would go this route, however, if a commercial company were to build a bot atop telebot which provides some kind of service to customers, the above quickly becomes relevant.

2. **Compatibilty with serverless architectures**: [Serverless](https://en.wikipedia.org/wiki/Serverless_computing) computing is slowly gaining in popularity. A persistent process cannot run in such an environment, however, coupled with something like the [Amazon API Gateway](https://aws.amazon.com/api-gateway/) it should be possible to build a Telegram bot that can. Mind you, no current commercial serverless solutions offer native Go runtimes so this is more crazy talk than anything right now. :)
