### ISSUE TITLE
Failed to run example: not go 1.3 version

### ISSUE THREAD

**Issue by LightVolk** [tucnak/telebot#83]
I try to execute example with go1.7 ubuntu 16.04:

`package main

import (
	"log"
	"os"
	"time"

	"github.com/tucnak/telebot"
)

func main() {
	bot, err := telebot.NewBot(os.Getenv("BOT_TOKEN"))
	if err != nil {
		log.Fatalln(err)
	}

	messages := make(chan telebot.Message, 100)
	bot.Listen(messages, 1*time.Second)

	for message := range messages {
		if message.Text == "/hi" {
			bot.SendMessage(message.Chat,
				"Hello, "+message.Sender.FirstName+"!", nil)
		}
	}
}
`

But,when i run i get error:

`./mybot.go:8: import /home/user/golang/pkg/linux_amd64/github.com/tucnak/telebot.a: object is [linux amd64 go1.7.4 X:framepointer] expected [linux amd64 go1.3.3 X:precisestack]
exit status 2
`

I use VS Code 1.8.1.

Can you help me?
Thank you!

**Comment by tucnak** [comment]
It doesn't seem to have anything to do with Telebot. No worries though, it happens from time to time, just clean your `$GOPATH/pkg` and 99% it'd be good!
