### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by miroslav-lee** [tucnak/telebot#85]
When sending a message, I put in the variable answer in the form of json. Then I'm decoding it and I get the error "<telebot.types.Message instance at 0x29cc0e0> is not JSON serializable". This trouble is in the key of "Entity".

**Comment by tucnak** [comment]
Can you provide some extended info from [json.UnmarshalTypeError](https://golang.org/pkg/encoding/json/#UnmarshalTypeError)?

**Comment by tucnak** [comment]
Closing for the time being.
