### ISSUE TITLE
handler description & help

### ISSUE THREAD

**Issue by irgendwr** [tucnak/telebot#91]
I would find it useful if the handlers introduced with #89 had an option to set a description and a category.
This would mean that you could automatically generate a 'help' handler.

The main problem that I see is that adding more arguments to the Handle func would be a breaking change (but on the other hand it's not that bad as the handler was only introduced 5 days ago).

**Comment by tucnak** [comment]
Automatic `/help` handler is a sound idea very much indeed. That said, I find myself implementing `/help` differently every single time. Sometimes you want to have some sort of a FAQ, sometimes it's just a brief explanation of core mechanics, but usually you don't want it auto-generated.

I also believe that such auto-generated `/help` implementation must also account for Telegram's recent i18n support (see `language_code` within [User](https://core.telegram.org/bots/api#user)) and at this point I can't really tell whether such feature is worth it.

>adding more arguments to the Handle func would be a breaking change

Not necessarily. Handle is a set-up function and isn't supposed to be used heavily (only a handful of times, during the bot init process), we can rely on reflection to add "optional" arguments:

```go
// Definition
func (b *Bot) Handle(prefix string, features ...interface{}) {}

// Uses
bot.Handle("/action", func (c Context) {})
bot.Handle("/action", "Description", func (c Context) {})
```

**Comment by tucnak** [comment]
Closing for the time being. We might bring it back for `v2.1` or whatever.
