### ISSUE TITLE
Testing capabilities?

### ISSUE THREAD

**Issue by varunpatro** [tucnak/telebot#94]
Hey @tucnak, thanks for creating this wonderful tool.

I'm using `telebot` for a project and I had questions about testing my code. Are there good ways to mock `SendMessage` and equivalent methods?

**Comment by ssalvatori** [comment]
Hi

I'm not sure if it is the best way to do it but I'm doing this on my test

code
```
func processing(db db.ZbotDatabase, msg telebot.Message) string {
}
```

test
```
botMsg := telebot.Message{Text: "text"}
result := processing(dbMock, botMsg)
```

**Comment by m1ome** [comment]
Just create interface that will implements methods you using.
And test it.

**Comment by tucnak** [comment]
@m1ome cheers. Closing this for now.
