### ISSUE TITLE
Error trying to get gopkg.in/tucnak/telebot.v0

### ISSUE THREAD

**Issue by saifulwebid** [tucnak/telebot#95]
It returns:

```
GitHub repository at https://github.com/tucnak/telebot has no branch or tag "v0", "v0.N" or "v0.N.M"
```

I can get from `gopkg.in/tucnak/telebot.v1` anyway.

**Comment by irgendwr** [comment]
There is no "Version 0".
I don't get what you're trying to achieve, just use v1.

**Comment by saifulwebid** [comment]
https://github.com/tucnak/telebot/blob/master/README.md told me to get Version 0.

**Comment by irgendwr** [comment]
Ahh sorry, this is a mistake in the readme.

**Comment by tucnak** [comment]
@saifulwebid, I just changed the `v1` version tag, make sure to get the latest version!
