### ISSUE TITLE
Functionality for `request_location` in `reply_keyboard` markups

### ISSUE THREAD

**Issue by varunpatro** [tucnak/telebot#97]
The Telegram Bot API guide allows for:

![screen shot 2017-10-09 at 11 04 03 pm](https://user-images.githubusercontent.com/6943308/31344760-31d9e53c-ad46-11e7-9576-3d160b1d61b8.png)

But the current API available only allows for buttons to be `strings` without being able to specify that the button can directly send a location.

@tucnak: can you extend the library to allow for this to happen? Or if you can guide me towards a possible solution, I can create a PR.

**Comment by tucnak** [comment]
Commit d4f3a16 in `v2/next` made it possible for v2. As of v1, I have no idea how to implement it well. Initially keyboard buttons were just text, so I had decided not to make a distinct struct for them.
